//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.catalogos.Pagos;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_TipoCadenaPago.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="c_TipoCadenaPago">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <whiteSpace value="collapse"/>
 *     <enumeration value="01"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "c_TipoCadenaPago", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Pagos")
@XmlEnum
public enum CTipoCadenaPago {

    @XmlEnumValue("01")
    VALUE_1("01");
    private final String value;

    CTipoCadenaPago(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CTipoCadenaPago fromValue(String v) {
        for (CTipoCadenaPago c: CTipoCadenaPago.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
