//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.sat.gob.mx/CartaPorte", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package mx.grupocorasa.sat.common.CartaPorte10;
