//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.acreditamiento10;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_TAR.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="c_TAR">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="617"/>
 *     <enumeration value="619"/>
 *     <enumeration value="624"/>
 *     <enumeration value="652"/>
 *     <enumeration value="654"/>
 *     <enumeration value="655"/>
 *     <enumeration value="656"/>
 *     <enumeration value="658"/>
 *     <enumeration value="659"/>
 *     <enumeration value="660"/>
 *     <enumeration value="661"/>
 *     <enumeration value="667"/>
 *     <enumeration value="693"/>
 *     <enumeration value="602"/>
 *     <enumeration value="603"/>
 *     <enumeration value="604"/>
 *     <enumeration value="605"/>
 *     <enumeration value="606"/>
 *     <enumeration value="607"/>
 *     <enumeration value="608"/>
 *     <enumeration value="609"/>
 *     <enumeration value="611"/>
 *     <enumeration value="612"/>
 *     <enumeration value="613"/>
 *     <enumeration value="614"/>
 *     <enumeration value="615"/>
 *     <enumeration value="620"/>
 *     <enumeration value="621"/>
 *     <enumeration value="622"/>
 *     <enumeration value="623"/>
 *     <enumeration value="625"/>
 *     <enumeration value="657"/>
 *     <enumeration value="664"/>
 *     <enumeration value="665"/>
 *     <enumeration value="666"/>
 *     <enumeration value="669"/>
 *     <enumeration value="695"/>
 *     <enumeration value="696"/>
 *     <enumeration value="697"/>
 *     <enumeration value="699"/>
 *     <enumeration value="627"/>
 *     <enumeration value="628"/>
 *     <enumeration value="629"/>
 *     <enumeration value="630"/>
 *     <enumeration value="631"/>
 *     <enumeration value="632"/>
 *     <enumeration value="633"/>
 *     <enumeration value="636"/>
 *     <enumeration value="637"/>
 *     <enumeration value="638"/>
 *     <enumeration value="639"/>
 *     <enumeration value="640"/>
 *     <enumeration value="641"/>
 *     <enumeration value="644"/>
 *     <enumeration value="645"/>
 *     <enumeration value="646"/>
 *     <enumeration value="647"/>
 *     <enumeration value="648"/>
 *     <enumeration value="649"/>
 *     <enumeration value="650"/>
 *     <enumeration value="663"/>
 *     <enumeration value="668"/>
 *     <enumeration value="672"/>
 *     <enumeration value="673"/>
 *     <enumeration value="674"/>
 *     <enumeration value="675"/>
 *     <enumeration value="676"/>
 *     <enumeration value="677"/>
 *     <enumeration value="678"/>
 *     <enumeration value="681"/>
 *     <enumeration value="682"/>
 *     <enumeration value="683"/>
 *     <enumeration value="684"/>
 *     <enumeration value="685"/>
 *     <enumeration value="688"/>
 *     <enumeration value="689"/>
 *     <enumeration value="690"/>
 *     <enumeration value="698"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "c_TAR")
@XmlEnum
public enum CTAR {

    @XmlEnumValue("617")
    VALUE_1("617"),
    @XmlEnumValue("619")
    VALUE_2("619"),
    @XmlEnumValue("624")
    VALUE_3("624"),
    @XmlEnumValue("652")
    VALUE_4("652"),
    @XmlEnumValue("654")
    VALUE_5("654"),
    @XmlEnumValue("655")
    VALUE_6("655"),
    @XmlEnumValue("656")
    VALUE_7("656"),
    @XmlEnumValue("658")
    VALUE_8("658"),
    @XmlEnumValue("659")
    VALUE_9("659"),
    @XmlEnumValue("660")
    VALUE_10("660"),
    @XmlEnumValue("661")
    VALUE_11("661"),
    @XmlEnumValue("667")
    VALUE_12("667"),
    @XmlEnumValue("693")
    VALUE_13("693"),
    @XmlEnumValue("602")
    VALUE_14("602"),
    @XmlEnumValue("603")
    VALUE_15("603"),
    @XmlEnumValue("604")
    VALUE_16("604"),
    @XmlEnumValue("605")
    VALUE_17("605"),
    @XmlEnumValue("606")
    VALUE_18("606"),
    @XmlEnumValue("607")
    VALUE_19("607"),
    @XmlEnumValue("608")
    VALUE_20("608"),
    @XmlEnumValue("609")
    VALUE_21("609"),
    @XmlEnumValue("611")
    VALUE_22("611"),
    @XmlEnumValue("612")
    VALUE_23("612"),
    @XmlEnumValue("613")
    VALUE_24("613"),
    @XmlEnumValue("614")
    VALUE_25("614"),
    @XmlEnumValue("615")
    VALUE_26("615"),
    @XmlEnumValue("620")
    VALUE_27("620"),
    @XmlEnumValue("621")
    VALUE_28("621"),
    @XmlEnumValue("622")
    VALUE_29("622"),
    @XmlEnumValue("623")
    VALUE_30("623"),
    @XmlEnumValue("625")
    VALUE_31("625"),
    @XmlEnumValue("657")
    VALUE_32("657"),
    @XmlEnumValue("664")
    VALUE_33("664"),
    @XmlEnumValue("665")
    VALUE_34("665"),
    @XmlEnumValue("666")
    VALUE_35("666"),
    @XmlEnumValue("669")
    VALUE_36("669"),
    @XmlEnumValue("695")
    VALUE_37("695"),
    @XmlEnumValue("696")
    VALUE_38("696"),
    @XmlEnumValue("697")
    VALUE_39("697"),
    @XmlEnumValue("699")
    VALUE_40("699"),
    @XmlEnumValue("627")
    VALUE_41("627"),
    @XmlEnumValue("628")
    VALUE_42("628"),
    @XmlEnumValue("629")
    VALUE_43("629"),
    @XmlEnumValue("630")
    VALUE_44("630"),
    @XmlEnumValue("631")
    VALUE_45("631"),
    @XmlEnumValue("632")
    VALUE_46("632"),
    @XmlEnumValue("633")
    VALUE_47("633"),
    @XmlEnumValue("636")
    VALUE_48("636"),
    @XmlEnumValue("637")
    VALUE_49("637"),
    @XmlEnumValue("638")
    VALUE_50("638"),
    @XmlEnumValue("639")
    VALUE_51("639"),
    @XmlEnumValue("640")
    VALUE_52("640"),
    @XmlEnumValue("641")
    VALUE_53("641"),
    @XmlEnumValue("644")
    VALUE_54("644"),
    @XmlEnumValue("645")
    VALUE_55("645"),
    @XmlEnumValue("646")
    VALUE_56("646"),
    @XmlEnumValue("647")
    VALUE_57("647"),
    @XmlEnumValue("648")
    VALUE_58("648"),
    @XmlEnumValue("649")
    VALUE_59("649"),
    @XmlEnumValue("650")
    VALUE_60("650"),
    @XmlEnumValue("663")
    VALUE_61("663"),
    @XmlEnumValue("668")
    VALUE_62("668"),
    @XmlEnumValue("672")
    VALUE_63("672"),
    @XmlEnumValue("673")
    VALUE_64("673"),
    @XmlEnumValue("674")
    VALUE_65("674"),
    @XmlEnumValue("675")
    VALUE_66("675"),
    @XmlEnumValue("676")
    VALUE_67("676"),
    @XmlEnumValue("677")
    VALUE_68("677"),
    @XmlEnumValue("678")
    VALUE_69("678"),
    @XmlEnumValue("681")
    VALUE_70("681"),
    @XmlEnumValue("682")
    VALUE_71("682"),
    @XmlEnumValue("683")
    VALUE_72("683"),
    @XmlEnumValue("684")
    VALUE_73("684"),
    @XmlEnumValue("685")
    VALUE_74("685"),
    @XmlEnumValue("688")
    VALUE_75("688"),
    @XmlEnumValue("689")
    VALUE_76("689"),
    @XmlEnumValue("690")
    VALUE_77("690"),
    @XmlEnumValue("698")
    VALUE_78("698");
    private final String value;

    CTAR(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CTAR fromValue(String v) {
        for (CTAR c: CTAR.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
