//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.catalogos.CartaPorte;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_ClaveUnidadPeso.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="c_ClaveUnidadPeso">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <whiteSpace value="collapse"/>
 *     <enumeration value="Tu"/>
 *     <enumeration value="X1A"/>
 *     <enumeration value="X1B"/>
 *     <enumeration value="X1D"/>
 *     <enumeration value="X1F"/>
 *     <enumeration value="X1G"/>
 *     <enumeration value="X1w"/>
 *     <enumeration value="X2C"/>
 *     <enumeration value="X3A"/>
 *     <enumeration value="X3H"/>
 *     <enumeration value="X43"/>
 *     <enumeration value="X44"/>
 *     <enumeration value="X4A"/>
 *     <enumeration value="X4B"/>
 *     <enumeration value="X4C"/>
 *     <enumeration value="X4D"/>
 *     <enumeration value="X4F"/>
 *     <enumeration value="X4G"/>
 *     <enumeration value="X4H"/>
 *     <enumeration value="X5H"/>
 *     <enumeration value="X5L"/>
 *     <enumeration value="X5M"/>
 *     <enumeration value="X6H"/>
 *     <enumeration value="X6P"/>
 *     <enumeration value="X7A"/>
 *     <enumeration value="X7B"/>
 *     <enumeration value="X8A"/>
 *     <enumeration value="X8B"/>
 *     <enumeration value="X8C"/>
 *     <enumeration value="XAA"/>
 *     <enumeration value="XAB"/>
 *     <enumeration value="XAC"/>
 *     <enumeration value="XAD"/>
 *     <enumeration value="XAE"/>
 *     <enumeration value="XAF"/>
 *     <enumeration value="XAG"/>
 *     <enumeration value="XAH"/>
 *     <enumeration value="XAI"/>
 *     <enumeration value="XAJ"/>
 *     <enumeration value="XAL"/>
 *     <enumeration value="XAM"/>
 *     <enumeration value="XAP"/>
 *     <enumeration value="XAT"/>
 *     <enumeration value="XAV"/>
 *     <enumeration value="XB4"/>
 *     <enumeration value="XBA"/>
 *     <enumeration value="XBB"/>
 *     <enumeration value="XBC"/>
 *     <enumeration value="XBD"/>
 *     <enumeration value="XBE"/>
 *     <enumeration value="XBF"/>
 *     <enumeration value="XBG"/>
 *     <enumeration value="XBH"/>
 *     <enumeration value="XBI"/>
 *     <enumeration value="XBJ"/>
 *     <enumeration value="XBK"/>
 *     <enumeration value="XBL"/>
 *     <enumeration value="XBM"/>
 *     <enumeration value="XBN"/>
 *     <enumeration value="XBO"/>
 *     <enumeration value="XBP"/>
 *     <enumeration value="XBQ"/>
 *     <enumeration value="XBR"/>
 *     <enumeration value="XBS"/>
 *     <enumeration value="XBT"/>
 *     <enumeration value="XBU"/>
 *     <enumeration value="XBV"/>
 *     <enumeration value="XBW"/>
 *     <enumeration value="XBX"/>
 *     <enumeration value="XBY"/>
 *     <enumeration value="XBZ"/>
 *     <enumeration value="XCA"/>
 *     <enumeration value="XCB"/>
 *     <enumeration value="XCC"/>
 *     <enumeration value="XCD"/>
 *     <enumeration value="XCE"/>
 *     <enumeration value="XCF"/>
 *     <enumeration value="XCG"/>
 *     <enumeration value="XCH"/>
 *     <enumeration value="XCI"/>
 *     <enumeration value="XCJ"/>
 *     <enumeration value="XCK"/>
 *     <enumeration value="XCL"/>
 *     <enumeration value="XCM"/>
 *     <enumeration value="XCN"/>
 *     <enumeration value="XCO"/>
 *     <enumeration value="XCP"/>
 *     <enumeration value="XCQ"/>
 *     <enumeration value="XCR"/>
 *     <enumeration value="XCS"/>
 *     <enumeration value="XCT"/>
 *     <enumeration value="XCU"/>
 *     <enumeration value="XCV"/>
 *     <enumeration value="XCW"/>
 *     <enumeration value="XCX"/>
 *     <enumeration value="XCY"/>
 *     <enumeration value="XCZ"/>
 *     <enumeration value="XDA"/>
 *     <enumeration value="XDB"/>
 *     <enumeration value="XDC"/>
 *     <enumeration value="XDG"/>
 *     <enumeration value="XDH"/>
 *     <enumeration value="XDI"/>
 *     <enumeration value="XDJ"/>
 *     <enumeration value="XDK"/>
 *     <enumeration value="XDL"/>
 *     <enumeration value="XDM"/>
 *     <enumeration value="XDN"/>
 *     <enumeration value="XDP"/>
 *     <enumeration value="XDR"/>
 *     <enumeration value="XDS"/>
 *     <enumeration value="XDT"/>
 *     <enumeration value="XDU"/>
 *     <enumeration value="XDV"/>
 *     <enumeration value="XDW"/>
 *     <enumeration value="XDX"/>
 *     <enumeration value="XDY"/>
 *     <enumeration value="XEC"/>
 *     <enumeration value="XED"/>
 *     <enumeration value="XEE"/>
 *     <enumeration value="XEF"/>
 *     <enumeration value="XEG"/>
 *     <enumeration value="XEH"/>
 *     <enumeration value="XEI"/>
 *     <enumeration value="XEN"/>
 *     <enumeration value="XFB"/>
 *     <enumeration value="XFC"/>
 *     <enumeration value="XFD"/>
 *     <enumeration value="XFE"/>
 *     <enumeration value="XFI"/>
 *     <enumeration value="XFL"/>
 *     <enumeration value="XFO"/>
 *     <enumeration value="XFP"/>
 *     <enumeration value="XFR"/>
 *     <enumeration value="XFT"/>
 *     <enumeration value="XFW"/>
 *     <enumeration value="XFX"/>
 *     <enumeration value="XGB"/>
 *     <enumeration value="XGI"/>
 *     <enumeration value="XGL"/>
 *     <enumeration value="XGR"/>
 *     <enumeration value="XGU"/>
 *     <enumeration value="XGY"/>
 *     <enumeration value="XGZ"/>
 *     <enumeration value="XHA"/>
 *     <enumeration value="XHB"/>
 *     <enumeration value="XHC"/>
 *     <enumeration value="XHG"/>
 *     <enumeration value="XHN"/>
 *     <enumeration value="XHR"/>
 *     <enumeration value="XIA"/>
 *     <enumeration value="XIB"/>
 *     <enumeration value="XIC"/>
 *     <enumeration value="XID"/>
 *     <enumeration value="XIE"/>
 *     <enumeration value="XIF"/>
 *     <enumeration value="XIG"/>
 *     <enumeration value="XIH"/>
 *     <enumeration value="XIK"/>
 *     <enumeration value="XIL"/>
 *     <enumeration value="XIN"/>
 *     <enumeration value="XIZ"/>
 *     <enumeration value="XJB"/>
 *     <enumeration value="XJC"/>
 *     <enumeration value="XJG"/>
 *     <enumeration value="XJR"/>
 *     <enumeration value="XJT"/>
 *     <enumeration value="XJY"/>
 *     <enumeration value="XKG"/>
 *     <enumeration value="XKI"/>
 *     <enumeration value="XLE"/>
 *     <enumeration value="XLG"/>
 *     <enumeration value="XLT"/>
 *     <enumeration value="XLU"/>
 *     <enumeration value="XLV"/>
 *     <enumeration value="XLZ"/>
 *     <enumeration value="XMA"/>
 *     <enumeration value="XMB"/>
 *     <enumeration value="XMC"/>
 *     <enumeration value="XME"/>
 *     <enumeration value="XMR"/>
 *     <enumeration value="XMS"/>
 *     <enumeration value="XMT"/>
 *     <enumeration value="XMW"/>
 *     <enumeration value="XMX"/>
 *     <enumeration value="XNA"/>
 *     <enumeration value="XNE"/>
 *     <enumeration value="XNF"/>
 *     <enumeration value="XNG"/>
 *     <enumeration value="XNS"/>
 *     <enumeration value="XNT"/>
 *     <enumeration value="XNU"/>
 *     <enumeration value="XNV"/>
 *     <enumeration value="XOA"/>
 *     <enumeration value="XOB"/>
 *     <enumeration value="XOC"/>
 *     <enumeration value="XOD"/>
 *     <enumeration value="XOE"/>
 *     <enumeration value="XOF"/>
 *     <enumeration value="XOK"/>
 *     <enumeration value="XOT"/>
 *     <enumeration value="XP2"/>
 *     <enumeration value="XPA"/>
 *     <enumeration value="XPB"/>
 *     <enumeration value="XPC"/>
 *     <enumeration value="XPD"/>
 *     <enumeration value="XPE"/>
 *     <enumeration value="XPF"/>
 *     <enumeration value="XPG"/>
 *     <enumeration value="XPH"/>
 *     <enumeration value="XPI"/>
 *     <enumeration value="XPJ"/>
 *     <enumeration value="XPK"/>
 *     <enumeration value="XPL"/>
 *     <enumeration value="XPN"/>
 *     <enumeration value="XPO"/>
 *     <enumeration value="XPR"/>
 *     <enumeration value="XPT"/>
 *     <enumeration value="XPU"/>
 *     <enumeration value="XPV"/>
 *     <enumeration value="XPX"/>
 *     <enumeration value="XPY"/>
 *     <enumeration value="XPZ"/>
 *     <enumeration value="XQA"/>
 *     <enumeration value="XQB"/>
 *     <enumeration value="XQC"/>
 *     <enumeration value="XQD"/>
 *     <enumeration value="XQF"/>
 *     <enumeration value="XQG"/>
 *     <enumeration value="XQH"/>
 *     <enumeration value="XQJ"/>
 *     <enumeration value="XQK"/>
 *     <enumeration value="XQL"/>
 *     <enumeration value="XQM"/>
 *     <enumeration value="XQN"/>
 *     <enumeration value="XQP"/>
 *     <enumeration value="XQQ"/>
 *     <enumeration value="XQR"/>
 *     <enumeration value="XQS"/>
 *     <enumeration value="XRD"/>
 *     <enumeration value="XRG"/>
 *     <enumeration value="XRJ"/>
 *     <enumeration value="XRK"/>
 *     <enumeration value="XRL"/>
 *     <enumeration value="XRO"/>
 *     <enumeration value="XRT"/>
 *     <enumeration value="XRZ"/>
 *     <enumeration value="XSA"/>
 *     <enumeration value="XSB"/>
 *     <enumeration value="XSC"/>
 *     <enumeration value="XSD"/>
 *     <enumeration value="XSE"/>
 *     <enumeration value="XSH"/>
 *     <enumeration value="XSI"/>
 *     <enumeration value="XSK"/>
 *     <enumeration value="XSL"/>
 *     <enumeration value="XSM"/>
 *     <enumeration value="XSO"/>
 *     <enumeration value="XSP"/>
 *     <enumeration value="XSS"/>
 *     <enumeration value="XSU"/>
 *     <enumeration value="XSV"/>
 *     <enumeration value="XSW"/>
 *     <enumeration value="XSY"/>
 *     <enumeration value="XSZ"/>
 *     <enumeration value="XT1"/>
 *     <enumeration value="XTB"/>
 *     <enumeration value="XTC"/>
 *     <enumeration value="XTD"/>
 *     <enumeration value="XTG"/>
 *     <enumeration value="XTI"/>
 *     <enumeration value="XTK"/>
 *     <enumeration value="XTL"/>
 *     <enumeration value="XTN"/>
 *     <enumeration value="XTO"/>
 *     <enumeration value="XTR"/>
 *     <enumeration value="XTS"/>
 *     <enumeration value="XTT"/>
 *     <enumeration value="XTU"/>
 *     <enumeration value="XTV"/>
 *     <enumeration value="XTW"/>
 *     <enumeration value="XTY"/>
 *     <enumeration value="XTZ"/>
 *     <enumeration value="XUC"/>
 *     <enumeration value="XUN"/>
 *     <enumeration value="XVA"/>
 *     <enumeration value="XVG"/>
 *     <enumeration value="XVI"/>
 *     <enumeration value="XVK"/>
 *     <enumeration value="XVL"/>
 *     <enumeration value="XVN"/>
 *     <enumeration value="XVO"/>
 *     <enumeration value="XVP"/>
 *     <enumeration value="XVQ"/>
 *     <enumeration value="XVR"/>
 *     <enumeration value="XVS"/>
 *     <enumeration value="XVY"/>
 *     <enumeration value="XWA"/>
 *     <enumeration value="XWB"/>
 *     <enumeration value="XWC"/>
 *     <enumeration value="XWD"/>
 *     <enumeration value="XWF"/>
 *     <enumeration value="XWG"/>
 *     <enumeration value="XWH"/>
 *     <enumeration value="XWJ"/>
 *     <enumeration value="XWK"/>
 *     <enumeration value="XWL"/>
 *     <enumeration value="XWM"/>
 *     <enumeration value="XWN"/>
 *     <enumeration value="XWP"/>
 *     <enumeration value="XWQ"/>
 *     <enumeration value="XWR"/>
 *     <enumeration value="XWS"/>
 *     <enumeration value="XWT"/>
 *     <enumeration value="XWU"/>
 *     <enumeration value="XWV"/>
 *     <enumeration value="XWW"/>
 *     <enumeration value="XWX"/>
 *     <enumeration value="XWY"/>
 *     <enumeration value="XWZ"/>
 *     <enumeration value="XXA"/>
 *     <enumeration value="XXB"/>
 *     <enumeration value="XXC"/>
 *     <enumeration value="XXD"/>
 *     <enumeration value="XXF"/>
 *     <enumeration value="XXG"/>
 *     <enumeration value="XXH"/>
 *     <enumeration value="XXJ"/>
 *     <enumeration value="XXK"/>
 *     <enumeration value="XYA"/>
 *     <enumeration value="XYB"/>
 *     <enumeration value="XYC"/>
 *     <enumeration value="XYD"/>
 *     <enumeration value="XYF"/>
 *     <enumeration value="XYG"/>
 *     <enumeration value="XYH"/>
 *     <enumeration value="XYJ"/>
 *     <enumeration value="XYK"/>
 *     <enumeration value="XYL"/>
 *     <enumeration value="XYM"/>
 *     <enumeration value="XYN"/>
 *     <enumeration value="XYP"/>
 *     <enumeration value="XYQ"/>
 *     <enumeration value="XYR"/>
 *     <enumeration value="XYS"/>
 *     <enumeration value="XYT"/>
 *     <enumeration value="Xyv"/>
 *     <enumeration value="XYW"/>
 *     <enumeration value="XYX"/>
 *     <enumeration value="XYY"/>
 *     <enumeration value="XYZ"/>
 *     <enumeration value="XZA"/>
 *     <enumeration value="XZB"/>
 *     <enumeration value="XZC"/>
 *     <enumeration value="XZD"/>
 *     <enumeration value="XZF"/>
 *     <enumeration value="XZG"/>
 *     <enumeration value="XZH"/>
 *     <enumeration value="XZJ"/>
 *     <enumeration value="XZK"/>
 *     <enumeration value="XZL"/>
 *     <enumeration value="XZM"/>
 *     <enumeration value="XZN"/>
 *     <enumeration value="XZP"/>
 *     <enumeration value="XZQ"/>
 *     <enumeration value="XZR"/>
 *     <enumeration value="XZS"/>
 *     <enumeration value="XZT"/>
 *     <enumeration value="XZU"/>
 *     <enumeration value="XZV"/>
 *     <enumeration value="XZW"/>
 *     <enumeration value="XZX"/>
 *     <enumeration value="XZY"/>
 *     <enumeration value="KGM"/>
 *     <enumeration value="MC"/>
 *     <enumeration value="DJ"/>
 *     <enumeration value="DG"/>
 *     <enumeration value="GRM"/>
 *     <enumeration value="CGM"/>
 *     <enumeration value="TNE"/>
 *     <enumeration value="DTN"/>
 *     <enumeration value="MGM"/>
 *     <enumeration value="HGM"/>
 *     <enumeration value="KTN"/>
 *     <enumeration value="2U"/>
 *     <enumeration value="LBR"/>
 *     <enumeration value="GRN"/>
 *     <enumeration value="ONZ"/>
 *     <enumeration value="CWI"/>
 *     <enumeration value="CWA"/>
 *     <enumeration value="LTN"/>
 *     <enumeration value="STI"/>
 *     <enumeration value="STN"/>
 *     <enumeration value="APZ"/>
 *     <enumeration value="F13"/>
 *     <enumeration value="K64"/>
 *     <enumeration value="L69"/>
 *     <enumeration value="L87"/>
 *     <enumeration value="M85"/>
 *     <enumeration value="M86"/>
 *     <enumeration value="J33"/>
 *     <enumeration value="L32"/>
 *     <enumeration value="NA"/>
 *     <enumeration value="M29"/>
 *     <enumeration value="M91"/>
 *     <enumeration value="Q29"/>
 *     <enumeration value="MTQ"/>
 *     <enumeration value="MAL"/>
 *     <enumeration value="LTR"/>
 *     <enumeration value="MMQ"/>
 *     <enumeration value="CMQ"/>
 *     <enumeration value="DMQ"/>
 *     <enumeration value="MLT"/>
 *     <enumeration value="HLT"/>
 *     <enumeration value="CLT"/>
 *     <enumeration value="DMA"/>
 *     <enumeration value="H19"/>
 *     <enumeration value="H20"/>
 *     <enumeration value="M71"/>
 *     <enumeration value="DLT"/>
 *     <enumeration value="4G"/>
 *     <enumeration value="K6"/>
 *     <enumeration value="A44"/>
 *     <enumeration value="G94"/>
 *     <enumeration value="G95"/>
 *     <enumeration value="G96"/>
 *     <enumeration value="G97"/>
 *     <enumeration value="5I"/>
 *     <enumeration value="INQ"/>
 *     <enumeration value="FTQ"/>
 *     <enumeration value="YDQ"/>
 *     <enumeration value="GLI"/>
 *     <enumeration value="GLL"/>
 *     <enumeration value="PT"/>
 *     <enumeration value="PTI"/>
 *     <enumeration value="QTI"/>
 *     <enumeration value="PTL"/>
 *     <enumeration value="QTL"/>
 *     <enumeration value="PTD"/>
 *     <enumeration value="OZI"/>
 *     <enumeration value="QT"/>
 *     <enumeration value="J57"/>
 *     <enumeration value="K21"/>
 *     <enumeration value="K23"/>
 *     <enumeration value="L43"/>
 *     <enumeration value="L61"/>
 *     <enumeration value="L62"/>
 *     <enumeration value="L84"/>
 *     <enumeration value="L86"/>
 *     <enumeration value="M11"/>
 *     <enumeration value="M14"/>
 *     <enumeration value="OZA"/>
 *     <enumeration value="BUI"/>
 *     <enumeration value="BUA"/>
 *     <enumeration value="BLL"/>
 *     <enumeration value="BLD"/>
 *     <enumeration value="GLD"/>
 *     <enumeration value="QTD"/>
 *     <enumeration value="G26"/>
 *     <enumeration value="G21"/>
 *     <enumeration value="G24"/>
 *     <enumeration value="G25"/>
 *     <enumeration value="G23"/>
 *     <enumeration value="M67"/>
 *     <enumeration value="M68"/>
 *     <enumeration value="M69"/>
 *     <enumeration value="M70"/>
 *     <enumeration value="Q32"/>
 *     <enumeration value="Q33"/>
 *     <enumeration value="Q34"/>
 *     <enumeration value="NM3"/>
 *     <enumeration value="SM3"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "c_ClaveUnidadPeso", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte")
@XmlEnum
public enum CClaveUnidadPeso {

    @XmlEnumValue("Tu")
    VALUE_1("Tu"),
    @XmlEnumValue("X1A")
    VALUE_2("X1A"),
    @XmlEnumValue("X1B")
    VALUE_3("X1B"),
    @XmlEnumValue("X1D")
    VALUE_4("X1D"),
    @XmlEnumValue("X1F")
    VALUE_5("X1F"),
    @XmlEnumValue("X1G")
    VALUE_6("X1G"),
    @XmlEnumValue("X1w")
    VALUE_7("X1w"),
    @XmlEnumValue("X2C")
    VALUE_8("X2C"),
    @XmlEnumValue("X3A")
    VALUE_9("X3A"),
    @XmlEnumValue("X3H")
    VALUE_10("X3H"),
    @XmlEnumValue("X43")
    VALUE_11("X43"),
    @XmlEnumValue("X44")
    VALUE_12("X44"),
    @XmlEnumValue("X4A")
    VALUE_13("X4A"),
    @XmlEnumValue("X4B")
    VALUE_14("X4B"),
    @XmlEnumValue("X4C")
    VALUE_15("X4C"),
    @XmlEnumValue("X4D")
    VALUE_16("X4D"),
    @XmlEnumValue("X4F")
    VALUE_17("X4F"),
    @XmlEnumValue("X4G")
    VALUE_18("X4G"),
    @XmlEnumValue("X4H")
    VALUE_19("X4H"),
    @XmlEnumValue("X5H")
    VALUE_20("X5H"),
    @XmlEnumValue("X5L")
    VALUE_21("X5L"),
    @XmlEnumValue("X5M")
    VALUE_22("X5M"),
    @XmlEnumValue("X6H")
    VALUE_23("X6H"),
    @XmlEnumValue("X6P")
    VALUE_24("X6P"),
    @XmlEnumValue("X7A")
    VALUE_25("X7A"),
    @XmlEnumValue("X7B")
    VALUE_26("X7B"),
    @XmlEnumValue("X8A")
    VALUE_27("X8A"),
    @XmlEnumValue("X8B")
    VALUE_28("X8B"),
    @XmlEnumValue("X8C")
    VALUE_29("X8C"),
    @XmlEnumValue("XAA")
    VALUE_30("XAA"),
    @XmlEnumValue("XAB")
    VALUE_31("XAB"),
    @XmlEnumValue("XAC")
    VALUE_32("XAC"),
    @XmlEnumValue("XAD")
    VALUE_33("XAD"),
    @XmlEnumValue("XAE")
    VALUE_34("XAE"),
    @XmlEnumValue("XAF")
    VALUE_35("XAF"),
    @XmlEnumValue("XAG")
    VALUE_36("XAG"),
    @XmlEnumValue("XAH")
    VALUE_37("XAH"),
    @XmlEnumValue("XAI")
    VALUE_38("XAI"),
    @XmlEnumValue("XAJ")
    VALUE_39("XAJ"),
    @XmlEnumValue("XAL")
    VALUE_40("XAL"),
    @XmlEnumValue("XAM")
    VALUE_41("XAM"),
    @XmlEnumValue("XAP")
    VALUE_42("XAP"),
    @XmlEnumValue("XAT")
    VALUE_43("XAT"),
    @XmlEnumValue("XAV")
    VALUE_44("XAV"),
    @XmlEnumValue("XB4")
    VALUE_45("XB4"),
    @XmlEnumValue("XBA")
    VALUE_46("XBA"),
    @XmlEnumValue("XBB")
    VALUE_47("XBB"),
    @XmlEnumValue("XBC")
    VALUE_48("XBC"),
    @XmlEnumValue("XBD")
    VALUE_49("XBD"),
    @XmlEnumValue("XBE")
    VALUE_50("XBE"),
    @XmlEnumValue("XBF")
    VALUE_51("XBF"),
    @XmlEnumValue("XBG")
    VALUE_52("XBG"),
    @XmlEnumValue("XBH")
    VALUE_53("XBH"),
    @XmlEnumValue("XBI")
    VALUE_54("XBI"),
    @XmlEnumValue("XBJ")
    VALUE_55("XBJ"),
    @XmlEnumValue("XBK")
    VALUE_56("XBK"),
    @XmlEnumValue("XBL")
    VALUE_57("XBL"),
    @XmlEnumValue("XBM")
    VALUE_58("XBM"),
    @XmlEnumValue("XBN")
    VALUE_59("XBN"),
    @XmlEnumValue("XBO")
    VALUE_60("XBO"),
    @XmlEnumValue("XBP")
    VALUE_61("XBP"),
    @XmlEnumValue("XBQ")
    VALUE_62("XBQ"),
    @XmlEnumValue("XBR")
    VALUE_63("XBR"),
    @XmlEnumValue("XBS")
    VALUE_64("XBS"),
    @XmlEnumValue("XBT")
    VALUE_65("XBT"),
    @XmlEnumValue("XBU")
    VALUE_66("XBU"),
    @XmlEnumValue("XBV")
    VALUE_67("XBV"),
    @XmlEnumValue("XBW")
    VALUE_68("XBW"),
    @XmlEnumValue("XBX")
    VALUE_69("XBX"),
    @XmlEnumValue("XBY")
    VALUE_70("XBY"),
    @XmlEnumValue("XBZ")
    VALUE_71("XBZ"),
    @XmlEnumValue("XCA")
    VALUE_72("XCA"),
    @XmlEnumValue("XCB")
    VALUE_73("XCB"),
    @XmlEnumValue("XCC")
    VALUE_74("XCC"),
    @XmlEnumValue("XCD")
    VALUE_75("XCD"),
    @XmlEnumValue("XCE")
    VALUE_76("XCE"),
    @XmlEnumValue("XCF")
    VALUE_77("XCF"),
    @XmlEnumValue("XCG")
    VALUE_78("XCG"),
    @XmlEnumValue("XCH")
    VALUE_79("XCH"),
    @XmlEnumValue("XCI")
    VALUE_80("XCI"),
    @XmlEnumValue("XCJ")
    VALUE_81("XCJ"),
    @XmlEnumValue("XCK")
    VALUE_82("XCK"),
    @XmlEnumValue("XCL")
    VALUE_83("XCL"),
    @XmlEnumValue("XCM")
    VALUE_84("XCM"),
    @XmlEnumValue("XCN")
    VALUE_85("XCN"),
    @XmlEnumValue("XCO")
    VALUE_86("XCO"),
    @XmlEnumValue("XCP")
    VALUE_87("XCP"),
    @XmlEnumValue("XCQ")
    VALUE_88("XCQ"),
    @XmlEnumValue("XCR")
    VALUE_89("XCR"),
    @XmlEnumValue("XCS")
    VALUE_90("XCS"),
    @XmlEnumValue("XCT")
    VALUE_91("XCT"),
    @XmlEnumValue("XCU")
    VALUE_92("XCU"),
    @XmlEnumValue("XCV")
    VALUE_93("XCV"),
    @XmlEnumValue("XCW")
    VALUE_94("XCW"),
    @XmlEnumValue("XCX")
    VALUE_95("XCX"),
    @XmlEnumValue("XCY")
    VALUE_96("XCY"),
    @XmlEnumValue("XCZ")
    VALUE_97("XCZ"),
    @XmlEnumValue("XDA")
    VALUE_98("XDA"),
    @XmlEnumValue("XDB")
    VALUE_99("XDB"),
    @XmlEnumValue("XDC")
    VALUE_100("XDC"),
    @XmlEnumValue("XDG")
    VALUE_101("XDG"),
    @XmlEnumValue("XDH")
    VALUE_102("XDH"),
    @XmlEnumValue("XDI")
    VALUE_103("XDI"),
    @XmlEnumValue("XDJ")
    VALUE_104("XDJ"),
    @XmlEnumValue("XDK")
    VALUE_105("XDK"),
    @XmlEnumValue("XDL")
    VALUE_106("XDL"),
    @XmlEnumValue("XDM")
    VALUE_107("XDM"),
    @XmlEnumValue("XDN")
    VALUE_108("XDN"),
    @XmlEnumValue("XDP")
    VALUE_109("XDP"),
    @XmlEnumValue("XDR")
    VALUE_110("XDR"),
    @XmlEnumValue("XDS")
    VALUE_111("XDS"),
    @XmlEnumValue("XDT")
    VALUE_112("XDT"),
    @XmlEnumValue("XDU")
    VALUE_113("XDU"),
    @XmlEnumValue("XDV")
    VALUE_114("XDV"),
    @XmlEnumValue("XDW")
    VALUE_115("XDW"),
    @XmlEnumValue("XDX")
    VALUE_116("XDX"),
    @XmlEnumValue("XDY")
    VALUE_117("XDY"),
    @XmlEnumValue("XEC")
    VALUE_118("XEC"),
    @XmlEnumValue("XED")
    VALUE_119("XED"),
    @XmlEnumValue("XEE")
    VALUE_120("XEE"),
    @XmlEnumValue("XEF")
    VALUE_121("XEF"),
    @XmlEnumValue("XEG")
    VALUE_122("XEG"),
    @XmlEnumValue("XEH")
    VALUE_123("XEH"),
    @XmlEnumValue("XEI")
    VALUE_124("XEI"),
    @XmlEnumValue("XEN")
    VALUE_125("XEN"),
    @XmlEnumValue("XFB")
    VALUE_126("XFB"),
    @XmlEnumValue("XFC")
    VALUE_127("XFC"),
    @XmlEnumValue("XFD")
    VALUE_128("XFD"),
    @XmlEnumValue("XFE")
    VALUE_129("XFE"),
    @XmlEnumValue("XFI")
    VALUE_130("XFI"),
    @XmlEnumValue("XFL")
    VALUE_131("XFL"),
    @XmlEnumValue("XFO")
    VALUE_132("XFO"),
    @XmlEnumValue("XFP")
    VALUE_133("XFP"),
    @XmlEnumValue("XFR")
    VALUE_134("XFR"),
    @XmlEnumValue("XFT")
    VALUE_135("XFT"),
    @XmlEnumValue("XFW")
    VALUE_136("XFW"),
    @XmlEnumValue("XFX")
    VALUE_137("XFX"),
    @XmlEnumValue("XGB")
    VALUE_138("XGB"),
    @XmlEnumValue("XGI")
    VALUE_139("XGI"),
    @XmlEnumValue("XGL")
    VALUE_140("XGL"),
    @XmlEnumValue("XGR")
    VALUE_141("XGR"),
    @XmlEnumValue("XGU")
    VALUE_142("XGU"),
    @XmlEnumValue("XGY")
    VALUE_143("XGY"),
    @XmlEnumValue("XGZ")
    VALUE_144("XGZ"),
    @XmlEnumValue("XHA")
    VALUE_145("XHA"),
    @XmlEnumValue("XHB")
    VALUE_146("XHB"),
    @XmlEnumValue("XHC")
    VALUE_147("XHC"),
    @XmlEnumValue("XHG")
    VALUE_148("XHG"),
    @XmlEnumValue("XHN")
    VALUE_149("XHN"),
    @XmlEnumValue("XHR")
    VALUE_150("XHR"),
    @XmlEnumValue("XIA")
    VALUE_151("XIA"),
    @XmlEnumValue("XIB")
    VALUE_152("XIB"),
    @XmlEnumValue("XIC")
    VALUE_153("XIC"),
    @XmlEnumValue("XID")
    VALUE_154("XID"),
    @XmlEnumValue("XIE")
    VALUE_155("XIE"),
    @XmlEnumValue("XIF")
    VALUE_156("XIF"),
    @XmlEnumValue("XIG")
    VALUE_157("XIG"),
    @XmlEnumValue("XIH")
    VALUE_158("XIH"),
    @XmlEnumValue("XIK")
    VALUE_159("XIK"),
    @XmlEnumValue("XIL")
    VALUE_160("XIL"),
    @XmlEnumValue("XIN")
    VALUE_161("XIN"),
    @XmlEnumValue("XIZ")
    VALUE_162("XIZ"),
    @XmlEnumValue("XJB")
    VALUE_163("XJB"),
    @XmlEnumValue("XJC")
    VALUE_164("XJC"),
    @XmlEnumValue("XJG")
    VALUE_165("XJG"),
    @XmlEnumValue("XJR")
    VALUE_166("XJR"),
    @XmlEnumValue("XJT")
    VALUE_167("XJT"),
    @XmlEnumValue("XJY")
    VALUE_168("XJY"),
    @XmlEnumValue("XKG")
    VALUE_169("XKG"),
    @XmlEnumValue("XKI")
    VALUE_170("XKI"),
    @XmlEnumValue("XLE")
    VALUE_171("XLE"),
    @XmlEnumValue("XLG")
    VALUE_172("XLG"),
    @XmlEnumValue("XLT")
    VALUE_173("XLT"),
    @XmlEnumValue("XLU")
    VALUE_174("XLU"),
    @XmlEnumValue("XLV")
    VALUE_175("XLV"),
    @XmlEnumValue("XLZ")
    VALUE_176("XLZ"),
    @XmlEnumValue("XMA")
    VALUE_177("XMA"),
    @XmlEnumValue("XMB")
    VALUE_178("XMB"),
    @XmlEnumValue("XMC")
    VALUE_179("XMC"),
    @XmlEnumValue("XME")
    VALUE_180("XME"),
    @XmlEnumValue("XMR")
    VALUE_181("XMR"),
    @XmlEnumValue("XMS")
    VALUE_182("XMS"),
    @XmlEnumValue("XMT")
    VALUE_183("XMT"),
    @XmlEnumValue("XMW")
    VALUE_184("XMW"),
    @XmlEnumValue("XMX")
    VALUE_185("XMX"),
    @XmlEnumValue("XNA")
    VALUE_186("XNA"),
    @XmlEnumValue("XNE")
    VALUE_187("XNE"),
    @XmlEnumValue("XNF")
    VALUE_188("XNF"),
    @XmlEnumValue("XNG")
    VALUE_189("XNG"),
    @XmlEnumValue("XNS")
    VALUE_190("XNS"),
    @XmlEnumValue("XNT")
    VALUE_191("XNT"),
    @XmlEnumValue("XNU")
    VALUE_192("XNU"),
    @XmlEnumValue("XNV")
    VALUE_193("XNV"),
    @XmlEnumValue("XOA")
    VALUE_194("XOA"),
    @XmlEnumValue("XOB")
    VALUE_195("XOB"),
    @XmlEnumValue("XOC")
    VALUE_196("XOC"),
    @XmlEnumValue("XOD")
    VALUE_197("XOD"),
    @XmlEnumValue("XOE")
    VALUE_198("XOE"),
    @XmlEnumValue("XOF")
    VALUE_199("XOF"),
    @XmlEnumValue("XOK")
    VALUE_200("XOK"),
    @XmlEnumValue("XOT")
    VALUE_201("XOT"),
    @XmlEnumValue("XP2")
    VALUE_202("XP2"),
    @XmlEnumValue("XPA")
    VALUE_203("XPA"),
    @XmlEnumValue("XPB")
    VALUE_204("XPB"),
    @XmlEnumValue("XPC")
    VALUE_205("XPC"),
    @XmlEnumValue("XPD")
    VALUE_206("XPD"),
    @XmlEnumValue("XPE")
    VALUE_207("XPE"),
    @XmlEnumValue("XPF")
    VALUE_208("XPF"),
    @XmlEnumValue("XPG")
    VALUE_209("XPG"),
    @XmlEnumValue("XPH")
    VALUE_210("XPH"),
    @XmlEnumValue("XPI")
    VALUE_211("XPI"),
    @XmlEnumValue("XPJ")
    VALUE_212("XPJ"),
    @XmlEnumValue("XPK")
    VALUE_213("XPK"),
    @XmlEnumValue("XPL")
    VALUE_214("XPL"),
    @XmlEnumValue("XPN")
    VALUE_215("XPN"),
    @XmlEnumValue("XPO")
    VALUE_216("XPO"),
    @XmlEnumValue("XPR")
    VALUE_217("XPR"),
    @XmlEnumValue("XPT")
    VALUE_218("XPT"),
    @XmlEnumValue("XPU")
    VALUE_219("XPU"),
    @XmlEnumValue("XPV")
    VALUE_220("XPV"),
    @XmlEnumValue("XPX")
    VALUE_221("XPX"),
    @XmlEnumValue("XPY")
    VALUE_222("XPY"),
    @XmlEnumValue("XPZ")
    VALUE_223("XPZ"),
    @XmlEnumValue("XQA")
    VALUE_224("XQA"),
    @XmlEnumValue("XQB")
    VALUE_225("XQB"),
    @XmlEnumValue("XQC")
    VALUE_226("XQC"),
    @XmlEnumValue("XQD")
    VALUE_227("XQD"),
    @XmlEnumValue("XQF")
    VALUE_228("XQF"),
    @XmlEnumValue("XQG")
    VALUE_229("XQG"),
    @XmlEnumValue("XQH")
    VALUE_230("XQH"),
    @XmlEnumValue("XQJ")
    VALUE_231("XQJ"),
    @XmlEnumValue("XQK")
    VALUE_232("XQK"),
    @XmlEnumValue("XQL")
    VALUE_233("XQL"),
    @XmlEnumValue("XQM")
    VALUE_234("XQM"),
    @XmlEnumValue("XQN")
    VALUE_235("XQN"),
    @XmlEnumValue("XQP")
    VALUE_236("XQP"),
    @XmlEnumValue("XQQ")
    VALUE_237("XQQ"),
    @XmlEnumValue("XQR")
    VALUE_238("XQR"),
    @XmlEnumValue("XQS")
    VALUE_239("XQS"),
    @XmlEnumValue("XRD")
    VALUE_240("XRD"),
    @XmlEnumValue("XRG")
    VALUE_241("XRG"),
    @XmlEnumValue("XRJ")
    VALUE_242("XRJ"),
    @XmlEnumValue("XRK")
    VALUE_243("XRK"),
    @XmlEnumValue("XRL")
    VALUE_244("XRL"),
    @XmlEnumValue("XRO")
    VALUE_245("XRO"),
    @XmlEnumValue("XRT")
    VALUE_246("XRT"),
    @XmlEnumValue("XRZ")
    VALUE_247("XRZ"),
    @XmlEnumValue("XSA")
    VALUE_248("XSA"),
    @XmlEnumValue("XSB")
    VALUE_249("XSB"),
    @XmlEnumValue("XSC")
    VALUE_250("XSC"),
    @XmlEnumValue("XSD")
    VALUE_251("XSD"),
    @XmlEnumValue("XSE")
    VALUE_252("XSE"),
    @XmlEnumValue("XSH")
    VALUE_253("XSH"),
    @XmlEnumValue("XSI")
    VALUE_254("XSI"),
    @XmlEnumValue("XSK")
    VALUE_255("XSK"),
    @XmlEnumValue("XSL")
    VALUE_256("XSL"),
    @XmlEnumValue("XSM")
    VALUE_257("XSM"),
    @XmlEnumValue("XSO")
    VALUE_258("XSO"),
    @XmlEnumValue("XSP")
    VALUE_259("XSP"),
    @XmlEnumValue("XSS")
    VALUE_260("XSS"),
    @XmlEnumValue("XSU")
    VALUE_261("XSU"),
    @XmlEnumValue("XSV")
    VALUE_262("XSV"),
    @XmlEnumValue("XSW")
    VALUE_263("XSW"),
    @XmlEnumValue("XSY")
    VALUE_264("XSY"),
    @XmlEnumValue("XSZ")
    VALUE_265("XSZ"),
    @XmlEnumValue("XT1")
    VALUE_266("XT1"),
    @XmlEnumValue("XTB")
    VALUE_267("XTB"),
    @XmlEnumValue("XTC")
    VALUE_268("XTC"),
    @XmlEnumValue("XTD")
    VALUE_269("XTD"),
    @XmlEnumValue("XTG")
    VALUE_270("XTG"),
    @XmlEnumValue("XTI")
    VALUE_271("XTI"),
    @XmlEnumValue("XTK")
    VALUE_272("XTK"),
    @XmlEnumValue("XTL")
    VALUE_273("XTL"),
    @XmlEnumValue("XTN")
    VALUE_274("XTN"),
    @XmlEnumValue("XTO")
    VALUE_275("XTO"),
    @XmlEnumValue("XTR")
    VALUE_276("XTR"),
    @XmlEnumValue("XTS")
    VALUE_277("XTS"),
    @XmlEnumValue("XTT")
    VALUE_278("XTT"),
    @XmlEnumValue("XTU")
    VALUE_279("XTU"),
    @XmlEnumValue("XTV")
    VALUE_280("XTV"),
    @XmlEnumValue("XTW")
    VALUE_281("XTW"),
    @XmlEnumValue("XTY")
    VALUE_282("XTY"),
    @XmlEnumValue("XTZ")
    VALUE_283("XTZ"),
    @XmlEnumValue("XUC")
    VALUE_284("XUC"),
    @XmlEnumValue("XUN")
    VALUE_285("XUN"),
    @XmlEnumValue("XVA")
    VALUE_286("XVA"),
    @XmlEnumValue("XVG")
    VALUE_287("XVG"),
    @XmlEnumValue("XVI")
    VALUE_288("XVI"),
    @XmlEnumValue("XVK")
    VALUE_289("XVK"),
    @XmlEnumValue("XVL")
    VALUE_290("XVL"),
    @XmlEnumValue("XVN")
    VALUE_291("XVN"),
    @XmlEnumValue("XVO")
    VALUE_292("XVO"),
    @XmlEnumValue("XVP")
    VALUE_293("XVP"),
    @XmlEnumValue("XVQ")
    VALUE_294("XVQ"),
    @XmlEnumValue("XVR")
    VALUE_295("XVR"),
    @XmlEnumValue("XVS")
    VALUE_296("XVS"),
    @XmlEnumValue("XVY")
    VALUE_297("XVY"),
    @XmlEnumValue("XWA")
    VALUE_298("XWA"),
    @XmlEnumValue("XWB")
    VALUE_299("XWB"),
    @XmlEnumValue("XWC")
    VALUE_300("XWC"),
    @XmlEnumValue("XWD")
    VALUE_301("XWD"),
    @XmlEnumValue("XWF")
    VALUE_302("XWF"),
    @XmlEnumValue("XWG")
    VALUE_303("XWG"),
    @XmlEnumValue("XWH")
    VALUE_304("XWH"),
    @XmlEnumValue("XWJ")
    VALUE_305("XWJ"),
    @XmlEnumValue("XWK")
    VALUE_306("XWK"),
    @XmlEnumValue("XWL")
    VALUE_307("XWL"),
    @XmlEnumValue("XWM")
    VALUE_308("XWM"),
    @XmlEnumValue("XWN")
    VALUE_309("XWN"),
    @XmlEnumValue("XWP")
    VALUE_310("XWP"),
    @XmlEnumValue("XWQ")
    VALUE_311("XWQ"),
    @XmlEnumValue("XWR")
    VALUE_312("XWR"),
    @XmlEnumValue("XWS")
    VALUE_313("XWS"),
    @XmlEnumValue("XWT")
    VALUE_314("XWT"),
    @XmlEnumValue("XWU")
    VALUE_315("XWU"),
    @XmlEnumValue("XWV")
    VALUE_316("XWV"),
    @XmlEnumValue("XWW")
    VALUE_317("XWW"),
    @XmlEnumValue("XWX")
    VALUE_318("XWX"),
    @XmlEnumValue("XWY")
    VALUE_319("XWY"),
    @XmlEnumValue("XWZ")
    VALUE_320("XWZ"),
    @XmlEnumValue("XXA")
    VALUE_321("XXA"),
    @XmlEnumValue("XXB")
    VALUE_322("XXB"),
    @XmlEnumValue("XXC")
    VALUE_323("XXC"),
    @XmlEnumValue("XXD")
    VALUE_324("XXD"),
    @XmlEnumValue("XXF")
    VALUE_325("XXF"),
    @XmlEnumValue("XXG")
    VALUE_326("XXG"),
    @XmlEnumValue("XXH")
    VALUE_327("XXH"),
    @XmlEnumValue("XXJ")
    VALUE_328("XXJ"),
    @XmlEnumValue("XXK")
    VALUE_329("XXK"),
    @XmlEnumValue("XYA")
    VALUE_330("XYA"),
    @XmlEnumValue("XYB")
    VALUE_331("XYB"),
    @XmlEnumValue("XYC")
    VALUE_332("XYC"),
    @XmlEnumValue("XYD")
    VALUE_333("XYD"),
    @XmlEnumValue("XYF")
    VALUE_334("XYF"),
    @XmlEnumValue("XYG")
    VALUE_335("XYG"),
    @XmlEnumValue("XYH")
    VALUE_336("XYH"),
    @XmlEnumValue("XYJ")
    VALUE_337("XYJ"),
    @XmlEnumValue("XYK")
    VALUE_338("XYK"),
    @XmlEnumValue("XYL")
    VALUE_339("XYL"),
    @XmlEnumValue("XYM")
    VALUE_340("XYM"),
    @XmlEnumValue("XYN")
    VALUE_341("XYN"),
    @XmlEnumValue("XYP")
    VALUE_342("XYP"),
    @XmlEnumValue("XYQ")
    VALUE_343("XYQ"),
    @XmlEnumValue("XYR")
    VALUE_344("XYR"),
    @XmlEnumValue("XYS")
    VALUE_345("XYS"),
    @XmlEnumValue("XYT")
    VALUE_346("XYT"),
    @XmlEnumValue("Xyv")
    VALUE_347("Xyv"),
    @XmlEnumValue("XYW")
    VALUE_348("XYW"),
    @XmlEnumValue("XYX")
    VALUE_349("XYX"),
    @XmlEnumValue("XYY")
    VALUE_350("XYY"),
    @XmlEnumValue("XYZ")
    VALUE_351("XYZ"),
    @XmlEnumValue("XZA")
    VALUE_352("XZA"),
    @XmlEnumValue("XZB")
    VALUE_353("XZB"),
    @XmlEnumValue("XZC")
    VALUE_354("XZC"),
    @XmlEnumValue("XZD")
    VALUE_355("XZD"),
    @XmlEnumValue("XZF")
    VALUE_356("XZF"),
    @XmlEnumValue("XZG")
    VALUE_357("XZG"),
    @XmlEnumValue("XZH")
    VALUE_358("XZH"),
    @XmlEnumValue("XZJ")
    VALUE_359("XZJ"),
    @XmlEnumValue("XZK")
    VALUE_360("XZK"),
    @XmlEnumValue("XZL")
    VALUE_361("XZL"),
    @XmlEnumValue("XZM")
    VALUE_362("XZM"),
    @XmlEnumValue("XZN")
    VALUE_363("XZN"),
    @XmlEnumValue("XZP")
    VALUE_364("XZP"),
    @XmlEnumValue("XZQ")
    VALUE_365("XZQ"),
    @XmlEnumValue("XZR")
    VALUE_366("XZR"),
    @XmlEnumValue("XZS")
    VALUE_367("XZS"),
    @XmlEnumValue("XZT")
    VALUE_368("XZT"),
    @XmlEnumValue("XZU")
    VALUE_369("XZU"),
    @XmlEnumValue("XZV")
    VALUE_370("XZV"),
    @XmlEnumValue("XZW")
    VALUE_371("XZW"),
    @XmlEnumValue("XZX")
    VALUE_372("XZX"),
    @XmlEnumValue("XZY")
    VALUE_373("XZY"),
    @XmlEnumValue("KGM")
    VALUE_374("KGM"),
    @XmlEnumValue("MC")
    VALUE_375("MC"),
    @XmlEnumValue("DJ")
    VALUE_376("DJ"),
    @XmlEnumValue("DG")
    VALUE_377("DG"),
    @XmlEnumValue("GRM")
    VALUE_378("GRM"),
    @XmlEnumValue("CGM")
    VALUE_379("CGM"),
    @XmlEnumValue("TNE")
    VALUE_380("TNE"),
    @XmlEnumValue("DTN")
    VALUE_381("DTN"),
    @XmlEnumValue("MGM")
    VALUE_382("MGM"),
    @XmlEnumValue("HGM")
    VALUE_383("HGM"),
    @XmlEnumValue("KTN")
    VALUE_384("KTN"),
    @XmlEnumValue("2U")
    VALUE_385("2U"),
    @XmlEnumValue("LBR")
    VALUE_386("LBR"),
    @XmlEnumValue("GRN")
    VALUE_387("GRN"),
    @XmlEnumValue("ONZ")
    VALUE_388("ONZ"),
    @XmlEnumValue("CWI")
    VALUE_389("CWI"),
    @XmlEnumValue("CWA")
    VALUE_390("CWA"),
    @XmlEnumValue("LTN")
    VALUE_391("LTN"),
    @XmlEnumValue("STI")
    VALUE_392("STI"),
    @XmlEnumValue("STN")
    VALUE_393("STN"),
    @XmlEnumValue("APZ")
    VALUE_394("APZ"),
    @XmlEnumValue("F13")
    VALUE_395("F13"),
    @XmlEnumValue("K64")
    VALUE_396("K64"),
    @XmlEnumValue("L69")
    VALUE_397("L69"),
    @XmlEnumValue("L87")
    VALUE_398("L87"),
    @XmlEnumValue("M85")
    VALUE_399("M85"),
    @XmlEnumValue("M86")
    VALUE_400("M86"),
    @XmlEnumValue("J33")
    VALUE_401("J33"),
    @XmlEnumValue("L32")
    VALUE_402("L32"),
    @XmlEnumValue("NA")
    VALUE_403("NA"),
    @XmlEnumValue("M29")
    VALUE_404("M29"),
    @XmlEnumValue("M91")
    VALUE_405("M91"),
    @XmlEnumValue("Q29")
    VALUE_406("Q29"),
    @XmlEnumValue("MTQ")
    VALUE_407("MTQ"),
    @XmlEnumValue("MAL")
    VALUE_408("MAL"),
    @XmlEnumValue("LTR")
    VALUE_409("LTR"),
    @XmlEnumValue("MMQ")
    VALUE_410("MMQ"),
    @XmlEnumValue("CMQ")
    VALUE_411("CMQ"),
    @XmlEnumValue("DMQ")
    VALUE_412("DMQ"),
    @XmlEnumValue("MLT")
    VALUE_413("MLT"),
    @XmlEnumValue("HLT")
    VALUE_414("HLT"),
    @XmlEnumValue("CLT")
    VALUE_415("CLT"),
    @XmlEnumValue("DMA")
    VALUE_416("DMA"),
    @XmlEnumValue("H19")
    VALUE_417("H19"),
    @XmlEnumValue("H20")
    VALUE_418("H20"),
    @XmlEnumValue("M71")
    VALUE_419("M71"),
    @XmlEnumValue("DLT")
    VALUE_420("DLT"),
    @XmlEnumValue("4G")
    VALUE_421("4G"),
    @XmlEnumValue("K6")
    VALUE_422("K6"),
    @XmlEnumValue("A44")
    VALUE_423("A44"),
    @XmlEnumValue("G94")
    VALUE_424("G94"),
    @XmlEnumValue("G95")
    VALUE_425("G95"),
    @XmlEnumValue("G96")
    VALUE_426("G96"),
    @XmlEnumValue("G97")
    VALUE_427("G97"),
    @XmlEnumValue("5I")
    VALUE_428("5I"),
    @XmlEnumValue("INQ")
    VALUE_429("INQ"),
    @XmlEnumValue("FTQ")
    VALUE_430("FTQ"),
    @XmlEnumValue("YDQ")
    VALUE_431("YDQ"),
    @XmlEnumValue("GLI")
    VALUE_432("GLI"),
    @XmlEnumValue("GLL")
    VALUE_433("GLL"),
    @XmlEnumValue("PT")
    VALUE_434("PT"),
    @XmlEnumValue("PTI")
    VALUE_435("PTI"),
    @XmlEnumValue("QTI")
    VALUE_436("QTI"),
    @XmlEnumValue("PTL")
    VALUE_437("PTL"),
    @XmlEnumValue("QTL")
    VALUE_438("QTL"),
    @XmlEnumValue("PTD")
    VALUE_439("PTD"),
    @XmlEnumValue("OZI")
    VALUE_440("OZI"),
    @XmlEnumValue("QT")
    VALUE_441("QT"),
    @XmlEnumValue("J57")
    VALUE_442("J57"),
    @XmlEnumValue("K21")
    VALUE_443("K21"),
    @XmlEnumValue("K23")
    VALUE_444("K23"),
    @XmlEnumValue("L43")
    VALUE_445("L43"),
    @XmlEnumValue("L61")
    VALUE_446("L61"),
    @XmlEnumValue("L62")
    VALUE_447("L62"),
    @XmlEnumValue("L84")
    VALUE_448("L84"),
    @XmlEnumValue("L86")
    VALUE_449("L86"),
    @XmlEnumValue("M11")
    VALUE_450("M11"),
    @XmlEnumValue("M14")
    VALUE_451("M14"),
    @XmlEnumValue("OZA")
    VALUE_452("OZA"),
    @XmlEnumValue("BUI")
    VALUE_453("BUI"),
    @XmlEnumValue("BUA")
    VALUE_454("BUA"),
    @XmlEnumValue("BLL")
    VALUE_455("BLL"),
    @XmlEnumValue("BLD")
    VALUE_456("BLD"),
    @XmlEnumValue("GLD")
    VALUE_457("GLD"),
    @XmlEnumValue("QTD")
    VALUE_458("QTD"),
    @XmlEnumValue("G26")
    VALUE_459("G26"),
    @XmlEnumValue("G21")
    VALUE_460("G21"),
    @XmlEnumValue("G24")
    VALUE_461("G24"),
    @XmlEnumValue("G25")
    VALUE_462("G25"),
    @XmlEnumValue("G23")
    VALUE_463("G23"),
    @XmlEnumValue("M67")
    VALUE_464("M67"),
    @XmlEnumValue("M68")
    VALUE_465("M68"),
    @XmlEnumValue("M69")
    VALUE_466("M69"),
    @XmlEnumValue("M70")
    VALUE_467("M70"),
    @XmlEnumValue("Q32")
    VALUE_468("Q32"),
    @XmlEnumValue("Q33")
    VALUE_469("Q33"),
    @XmlEnumValue("Q34")
    VALUE_470("Q34"),
    @XmlEnumValue("NM3")
    VALUE_471("NM3"),
    @XmlEnumValue("SM3")
    VALUE_472("SM3");
    private final String value;

    CClaveUnidadPeso(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CClaveUnidadPeso fromValue(String v) {
        for (CClaveUnidadPeso c: CClaveUnidadPeso.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
