//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.catalogos.CartaPorte;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_ClaveTipoCarga.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="c_ClaveTipoCarga">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <whiteSpace value="collapse"/>
 *     <enumeration value="CGS"/>
 *     <enumeration value="CGC"/>
 *     <enumeration value="GMN"/>
 *     <enumeration value="GAG"/>
 *     <enumeration value="OFL"/>
 *     <enumeration value="PYD"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "c_ClaveTipoCarga", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte")
@XmlEnum
public enum CClaveTipoCarga {

    CGS,
    CGC,
    GMN,
    GAG,
    OFL,
    PYD;

    public String value() {
        return name();
    }

    public static CClaveTipoCarga fromValue(String v) {
        return valueOf(v);
    }

}
