//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.catalogos.CartaPorte;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_ClaveProdSTCC.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="c_ClaveProdSTCC">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <whiteSpace value="collapse"/>
 *     <enumeration value="01"/>
 *     <enumeration value="011"/>
 *     <enumeration value="0112"/>
 *     <enumeration value="01131"/>
 *     <enumeration value="01132"/>
 *     <enumeration value="01133"/>
 *     <enumeration value="01134"/>
 *     <enumeration value="01135"/>
 *     <enumeration value="01136"/>
 *     <enumeration value="01137"/>
 *     <enumeration value="01139"/>
 *     <enumeration value="0114"/>
 *     <enumeration value="01144"/>
 *     <enumeration value="0115"/>
 *     <enumeration value="0119"/>
 *     <enumeration value="01193"/>
 *     <enumeration value="01195"/>
 *     <enumeration value="01197"/>
 *     <enumeration value="012"/>
 *     <enumeration value="0121"/>
 *     <enumeration value="0122"/>
 *     <enumeration value="01221"/>
 *     <enumeration value="01224"/>
 *     <enumeration value="01226"/>
 *     <enumeration value="0123"/>
 *     <enumeration value="01232"/>
 *     <enumeration value="0129"/>
 *     <enumeration value="01295"/>
 *     <enumeration value="013"/>
 *     <enumeration value="0131"/>
 *     <enumeration value="01318"/>
 *     <enumeration value="0133"/>
 *     <enumeration value="01334"/>
 *     <enumeration value="01335"/>
 *     <enumeration value="0134"/>
 *     <enumeration value="01341"/>
 *     <enumeration value="01342"/>
 *     <enumeration value="0139"/>
 *     <enumeration value="01392"/>
 *     <enumeration value="01394"/>
 *     <enumeration value="01398"/>
 *     <enumeration value="014"/>
 *     <enumeration value="0141"/>
 *     <enumeration value="01411"/>
 *     <enumeration value="01413"/>
 *     <enumeration value="01414"/>
 *     <enumeration value="0142"/>
 *     <enumeration value="0143"/>
 *     <enumeration value="01431"/>
 *     <enumeration value="015"/>
 *     <enumeration value="0151"/>
 *     <enumeration value="0152"/>
 *     <enumeration value="019"/>
 *     <enumeration value="0191"/>
 *     <enumeration value="0192"/>
 *     <enumeration value="08"/>
 *     <enumeration value="084"/>
 *     <enumeration value="08423"/>
 *     <enumeration value="086"/>
 *     <enumeration value="09"/>
 *     <enumeration value="091"/>
 *     <enumeration value="0912"/>
 *     <enumeration value="09131"/>
 *     <enumeration value="098"/>
 *     <enumeration value="10"/>
 *     <enumeration value="101"/>
 *     <enumeration value="10112"/>
 *     <enumeration value="102"/>
 *     <enumeration value="103"/>
 *     <enumeration value="1031"/>
 *     <enumeration value="1032"/>
 *     <enumeration value="104"/>
 *     <enumeration value="105"/>
 *     <enumeration value="106"/>
 *     <enumeration value="107"/>
 *     <enumeration value="108"/>
 *     <enumeration value="109"/>
 *     <enumeration value="11"/>
 *     <enumeration value="111"/>
 *     <enumeration value="11111"/>
 *     <enumeration value="11112"/>
 *     <enumeration value="112"/>
 *     <enumeration value="1121"/>
 *     <enumeration value="13"/>
 *     <enumeration value="131"/>
 *     <enumeration value="132"/>
 *     <enumeration value="14"/>
 *     <enumeration value="141"/>
 *     <enumeration value="142"/>
 *     <enumeration value="14211"/>
 *     <enumeration value="14212"/>
 *     <enumeration value="14219"/>
 *     <enumeration value="144"/>
 *     <enumeration value="14411"/>
 *     <enumeration value="14412"/>
 *     <enumeration value="14413"/>
 *     <enumeration value="145"/>
 *     <enumeration value="14511"/>
 *     <enumeration value="14512"/>
 *     <enumeration value="14514"/>
 *     <enumeration value="147"/>
 *     <enumeration value="14711"/>
 *     <enumeration value="14713"/>
 *     <enumeration value="14714"/>
 *     <enumeration value="14715"/>
 *     <enumeration value="14716"/>
 *     <enumeration value="149"/>
 *     <enumeration value="14911"/>
 *     <enumeration value="14913"/>
 *     <enumeration value="14914"/>
 *     <enumeration value="19"/>
 *     <enumeration value="191"/>
 *     <enumeration value="192"/>
 *     <enumeration value="193"/>
 *     <enumeration value="194"/>
 *     <enumeration value="195"/>
 *     <enumeration value="196"/>
 *     <enumeration value="199"/>
 *     <enumeration value="20"/>
 *     <enumeration value="201"/>
 *     <enumeration value="2011"/>
 *     <enumeration value="2012"/>
 *     <enumeration value="2013"/>
 *     <enumeration value="2014"/>
 *     <enumeration value="20141"/>
 *     <enumeration value="2015"/>
 *     <enumeration value="2016"/>
 *     <enumeration value="2017"/>
 *     <enumeration value="202"/>
 *     <enumeration value="2021"/>
 *     <enumeration value="2023"/>
 *     <enumeration value="2024"/>
 *     <enumeration value="2025"/>
 *     <enumeration value="2026"/>
 *     <enumeration value="203"/>
 *     <enumeration value="2031"/>
 *     <enumeration value="2032"/>
 *     <enumeration value="2033"/>
 *     <enumeration value="2034"/>
 *     <enumeration value="2035"/>
 *     <enumeration value="2036"/>
 *     <enumeration value="2037"/>
 *     <enumeration value="2038"/>
 *     <enumeration value="2039"/>
 *     <enumeration value="204"/>
 *     <enumeration value="2041"/>
 *     <enumeration value="20411"/>
 *     <enumeration value="20412"/>
 *     <enumeration value="20421"/>
 *     <enumeration value="20423"/>
 *     <enumeration value="2043"/>
 *     <enumeration value="2044"/>
 *     <enumeration value="2045"/>
 *     <enumeration value="2046"/>
 *     <enumeration value="20461"/>
 *     <enumeration value="20462"/>
 *     <enumeration value="20463"/>
 *     <enumeration value="20471"/>
 *     <enumeration value="20472"/>
 *     <enumeration value="205"/>
 *     <enumeration value="206"/>
 *     <enumeration value="2061"/>
 *     <enumeration value="20611"/>
 *     <enumeration value="20616"/>
 *     <enumeration value="20617"/>
 *     <enumeration value="2062"/>
 *     <enumeration value="20625"/>
 *     <enumeration value="20626"/>
 *     <enumeration value="207"/>
 *     <enumeration value="208"/>
 *     <enumeration value="20821"/>
 *     <enumeration value="20823"/>
 *     <enumeration value="2083"/>
 *     <enumeration value="2084"/>
 *     <enumeration value="20851"/>
 *     <enumeration value="20859"/>
 *     <enumeration value="2086"/>
 *     <enumeration value="2087"/>
 *     <enumeration value="209"/>
 *     <enumeration value="20911"/>
 *     <enumeration value="20914"/>
 *     <enumeration value="20921"/>
 *     <enumeration value="20923"/>
 *     <enumeration value="2093"/>
 *     <enumeration value="2094"/>
 *     <enumeration value="2095"/>
 *     <enumeration value="2096"/>
 *     <enumeration value="2097"/>
 *     <enumeration value="2098"/>
 *     <enumeration value="21"/>
 *     <enumeration value="211"/>
 *     <enumeration value="212"/>
 *     <enumeration value="213"/>
 *     <enumeration value="214"/>
 *     <enumeration value="22"/>
 *     <enumeration value="221"/>
 *     <enumeration value="222"/>
 *     <enumeration value="223"/>
 *     <enumeration value="224"/>
 *     <enumeration value="225"/>
 *     <enumeration value="227"/>
 *     <enumeration value="228"/>
 *     <enumeration value="229"/>
 *     <enumeration value="2296"/>
 *     <enumeration value="2297"/>
 *     <enumeration value="2298"/>
 *     <enumeration value="23"/>
 *     <enumeration value="231"/>
 *     <enumeration value="233"/>
 *     <enumeration value="235"/>
 *     <enumeration value="237"/>
 *     <enumeration value="238"/>
 *     <enumeration value="239"/>
 *     <enumeration value="24"/>
 *     <enumeration value="241"/>
 *     <enumeration value="24114"/>
 *     <enumeration value="24115"/>
 *     <enumeration value="24116"/>
 *     <enumeration value="242"/>
 *     <enumeration value="2421"/>
 *     <enumeration value="24212"/>
 *     <enumeration value="2429"/>
 *     <enumeration value="243"/>
 *     <enumeration value="2431"/>
 *     <enumeration value="2432"/>
 *     <enumeration value="244"/>
 *     <enumeration value="249"/>
 *     <enumeration value="2491"/>
 *     <enumeration value="25"/>
 *     <enumeration value="251"/>
 *     <enumeration value="253"/>
 *     <enumeration value="254"/>
 *     <enumeration value="259"/>
 *     <enumeration value="26"/>
 *     <enumeration value="261"/>
 *     <enumeration value="26111"/>
 *     <enumeration value="262"/>
 *     <enumeration value="26211"/>
 *     <enumeration value="26212"/>
 *     <enumeration value="26213"/>
 *     <enumeration value="26214"/>
 *     <enumeration value="26217"/>
 *     <enumeration value="26218"/>
 *     <enumeration value="263"/>
 *     <enumeration value="264"/>
 *     <enumeration value="2643"/>
 *     <enumeration value="26471"/>
 *     <enumeration value="265"/>
 *     <enumeration value="266"/>
 *     <enumeration value="26613"/>
 *     <enumeration value="27"/>
 *     <enumeration value="271"/>
 *     <enumeration value="272"/>
 *     <enumeration value="273"/>
 *     <enumeration value="274"/>
 *     <enumeration value="276"/>
 *     <enumeration value="277"/>
 *     <enumeration value="278"/>
 *     <enumeration value="279"/>
 *     <enumeration value="28"/>
 *     <enumeration value="281"/>
 *     <enumeration value="2812"/>
 *     <enumeration value="28123"/>
 *     <enumeration value="2813"/>
 *     <enumeration value="2814"/>
 *     <enumeration value="2816"/>
 *     <enumeration value="2818"/>
 *     <enumeration value="28184"/>
 *     <enumeration value="2819"/>
 *     <enumeration value="28193"/>
 *     <enumeration value="282"/>
 *     <enumeration value="28212"/>
 *     <enumeration value="28213"/>
 *     <enumeration value="283"/>
 *     <enumeration value="284"/>
 *     <enumeration value="2841"/>
 *     <enumeration value="285"/>
 *     <enumeration value="286"/>
 *     <enumeration value="287"/>
 *     <enumeration value="2871"/>
 *     <enumeration value="289"/>
 *     <enumeration value="2892"/>
 *     <enumeration value="28991"/>
 *     <enumeration value="29"/>
 *     <enumeration value="291"/>
 *     <enumeration value="29111"/>
 *     <enumeration value="29112"/>
 *     <enumeration value="29113"/>
 *     <enumeration value="29114"/>
 *     <enumeration value="29115"/>
 *     <enumeration value="29116"/>
 *     <enumeration value="29117"/>
 *     <enumeration value="29119"/>
 *     <enumeration value="2912"/>
 *     <enumeration value="295"/>
 *     <enumeration value="2951"/>
 *     <enumeration value="2952"/>
 *     <enumeration value="299"/>
 *     <enumeration value="29911"/>
 *     <enumeration value="29913"/>
 *     <enumeration value="29914"/>
 *     <enumeration value="30"/>
 *     <enumeration value="301"/>
 *     <enumeration value="302"/>
 *     <enumeration value="303"/>
 *     <enumeration value="304"/>
 *     <enumeration value="306"/>
 *     <enumeration value="307"/>
 *     <enumeration value="31"/>
 *     <enumeration value="311"/>
 *     <enumeration value="312"/>
 *     <enumeration value="313"/>
 *     <enumeration value="314"/>
 *     <enumeration value="315"/>
 *     <enumeration value="316"/>
 *     <enumeration value="319"/>
 *     <enumeration value="32"/>
 *     <enumeration value="321"/>
 *     <enumeration value="322"/>
 *     <enumeration value="3221"/>
 *     <enumeration value="324"/>
 *     <enumeration value="32411"/>
 *     <enumeration value="325"/>
 *     <enumeration value="3251"/>
 *     <enumeration value="32511"/>
 *     <enumeration value="3253"/>
 *     <enumeration value="3255"/>
 *     <enumeration value="3259"/>
 *     <enumeration value="32594"/>
 *     <enumeration value="326"/>
 *     <enumeration value="327"/>
 *     <enumeration value="3271"/>
 *     <enumeration value="3274"/>
 *     <enumeration value="3275"/>
 *     <enumeration value="328"/>
 *     <enumeration value="329"/>
 *     <enumeration value="3291"/>
 *     <enumeration value="3295"/>
 *     <enumeration value="33"/>
 *     <enumeration value="331"/>
 *     <enumeration value="33111"/>
 *     <enumeration value="33112"/>
 *     <enumeration value="33119"/>
 *     <enumeration value="3312"/>
 *     <enumeration value="33121"/>
 *     <enumeration value="3313"/>
 *     <enumeration value="3315"/>
 *     <enumeration value="332"/>
 *     <enumeration value="33211"/>
 *     <enumeration value="333"/>
 *     <enumeration value="3331"/>
 *     <enumeration value="3332"/>
 *     <enumeration value="3333"/>
 *     <enumeration value="3334"/>
 *     <enumeration value="335"/>
 *     <enumeration value="3351"/>
 *     <enumeration value="3352"/>
 *     <enumeration value="3357"/>
 *     <enumeration value="336"/>
 *     <enumeration value="3361"/>
 *     <enumeration value="3362"/>
 *     <enumeration value="339"/>
 *     <enumeration value="3391"/>
 *     <enumeration value="3392"/>
 *     <enumeration value="34"/>
 *     <enumeration value="341"/>
 *     <enumeration value="342"/>
 *     <enumeration value="343"/>
 *     <enumeration value="3433"/>
 *     <enumeration value="344"/>
 *     <enumeration value="3441"/>
 *     <enumeration value="34411"/>
 *     <enumeration value="345"/>
 *     <enumeration value="346"/>
 *     <enumeration value="348"/>
 *     <enumeration value="349"/>
 *     <enumeration value="3491"/>
 *     <enumeration value="3494"/>
 *     <enumeration value="35"/>
 *     <enumeration value="351"/>
 *     <enumeration value="352"/>
 *     <enumeration value="3524"/>
 *     <enumeration value="353"/>
 *     <enumeration value="3531"/>
 *     <enumeration value="3532"/>
 *     <enumeration value="3533"/>
 *     <enumeration value="3537"/>
 *     <enumeration value="354"/>
 *     <enumeration value="355"/>
 *     <enumeration value="356"/>
 *     <enumeration value="357"/>
 *     <enumeration value="358"/>
 *     <enumeration value="359"/>
 *     <enumeration value="36"/>
 *     <enumeration value="361"/>
 *     <enumeration value="362"/>
 *     <enumeration value="363"/>
 *     <enumeration value="3631"/>
 *     <enumeration value="3632"/>
 *     <enumeration value="3633"/>
 *     <enumeration value="364"/>
 *     <enumeration value="365"/>
 *     <enumeration value="366"/>
 *     <enumeration value="367"/>
 *     <enumeration value="369"/>
 *     <enumeration value="37"/>
 *     <enumeration value="371"/>
 *     <enumeration value="3711"/>
 *     <enumeration value="37111"/>
 *     <enumeration value="37112"/>
 *     <enumeration value="37113"/>
 *     <enumeration value="3712"/>
 *     <enumeration value="3713"/>
 *     <enumeration value="3714"/>
 *     <enumeration value="37147"/>
 *     <enumeration value="3715"/>
 *     <enumeration value="372"/>
 *     <enumeration value="373"/>
 *     <enumeration value="374"/>
 *     <enumeration value="37422"/>
 *     <enumeration value="375"/>
 *     <enumeration value="376"/>
 *     <enumeration value="379"/>
 *     <enumeration value="38"/>
 *     <enumeration value="381"/>
 *     <enumeration value="382"/>
 *     <enumeration value="383"/>
 *     <enumeration value="384"/>
 *     <enumeration value="385"/>
 *     <enumeration value="386"/>
 *     <enumeration value="387"/>
 *     <enumeration value="39"/>
 *     <enumeration value="391"/>
 *     <enumeration value="393"/>
 *     <enumeration value="394"/>
 *     <enumeration value="3949"/>
 *     <enumeration value="395"/>
 *     <enumeration value="396"/>
 *     <enumeration value="399"/>
 *     <enumeration value="40"/>
 *     <enumeration value="401"/>
 *     <enumeration value="402"/>
 *     <enumeration value="4021"/>
 *     <enumeration value="40211"/>
 *     <enumeration value="4022"/>
 *     <enumeration value="4024"/>
 *     <enumeration value="4026"/>
 *     <enumeration value="41"/>
 *     <enumeration value="411"/>
 *     <enumeration value="41111"/>
 *     <enumeration value="41114"/>
 *     <enumeration value="41115"/>
 *     <enumeration value="412"/>
 *     <enumeration value="42"/>
 *     <enumeration value="421"/>
 *     <enumeration value="422"/>
 *     <enumeration value="423"/>
 *     <enumeration value="44"/>
 *     <enumeration value="441"/>
 *     <enumeration value="45"/>
 *     <enumeration value="451"/>
 *     <enumeration value="46"/>
 *     <enumeration value="461"/>
 *     <enumeration value="462"/>
 *     <enumeration value="48"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "c_ClaveProdSTCC", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte")
@XmlEnum
public enum CClaveProdSTCC {

    @XmlEnumValue("01")
    VALUE_1("01"),
    @XmlEnumValue("011")
    VALUE_2("011"),
    @XmlEnumValue("0112")
    VALUE_3("0112"),
    @XmlEnumValue("01131")
    VALUE_4("01131"),
    @XmlEnumValue("01132")
    VALUE_5("01132"),
    @XmlEnumValue("01133")
    VALUE_6("01133"),
    @XmlEnumValue("01134")
    VALUE_7("01134"),
    @XmlEnumValue("01135")
    VALUE_8("01135"),
    @XmlEnumValue("01136")
    VALUE_9("01136"),
    @XmlEnumValue("01137")
    VALUE_10("01137"),
    @XmlEnumValue("01139")
    VALUE_11("01139"),
    @XmlEnumValue("0114")
    VALUE_12("0114"),
    @XmlEnumValue("01144")
    VALUE_13("01144"),
    @XmlEnumValue("0115")
    VALUE_14("0115"),
    @XmlEnumValue("0119")
    VALUE_15("0119"),
    @XmlEnumValue("01193")
    VALUE_16("01193"),
    @XmlEnumValue("01195")
    VALUE_17("01195"),
    @XmlEnumValue("01197")
    VALUE_18("01197"),
    @XmlEnumValue("012")
    VALUE_19("012"),
    @XmlEnumValue("0121")
    VALUE_20("0121"),
    @XmlEnumValue("0122")
    VALUE_21("0122"),
    @XmlEnumValue("01221")
    VALUE_22("01221"),
    @XmlEnumValue("01224")
    VALUE_23("01224"),
    @XmlEnumValue("01226")
    VALUE_24("01226"),
    @XmlEnumValue("0123")
    VALUE_25("0123"),
    @XmlEnumValue("01232")
    VALUE_26("01232"),
    @XmlEnumValue("0129")
    VALUE_27("0129"),
    @XmlEnumValue("01295")
    VALUE_28("01295"),
    @XmlEnumValue("013")
    VALUE_29("013"),
    @XmlEnumValue("0131")
    VALUE_30("0131"),
    @XmlEnumValue("01318")
    VALUE_31("01318"),
    @XmlEnumValue("0133")
    VALUE_32("0133"),
    @XmlEnumValue("01334")
    VALUE_33("01334"),
    @XmlEnumValue("01335")
    VALUE_34("01335"),
    @XmlEnumValue("0134")
    VALUE_35("0134"),
    @XmlEnumValue("01341")
    VALUE_36("01341"),
    @XmlEnumValue("01342")
    VALUE_37("01342"),
    @XmlEnumValue("0139")
    VALUE_38("0139"),
    @XmlEnumValue("01392")
    VALUE_39("01392"),
    @XmlEnumValue("01394")
    VALUE_40("01394"),
    @XmlEnumValue("01398")
    VALUE_41("01398"),
    @XmlEnumValue("014")
    VALUE_42("014"),
    @XmlEnumValue("0141")
    VALUE_43("0141"),
    @XmlEnumValue("01411")
    VALUE_44("01411"),
    @XmlEnumValue("01413")
    VALUE_45("01413"),
    @XmlEnumValue("01414")
    VALUE_46("01414"),
    @XmlEnumValue("0142")
    VALUE_47("0142"),
    @XmlEnumValue("0143")
    VALUE_48("0143"),
    @XmlEnumValue("01431")
    VALUE_49("01431"),
    @XmlEnumValue("015")
    VALUE_50("015"),
    @XmlEnumValue("0151")
    VALUE_51("0151"),
    @XmlEnumValue("0152")
    VALUE_52("0152"),
    @XmlEnumValue("019")
    VALUE_53("019"),
    @XmlEnumValue("0191")
    VALUE_54("0191"),
    @XmlEnumValue("0192")
    VALUE_55("0192"),
    @XmlEnumValue("08")
    VALUE_56("08"),
    @XmlEnumValue("084")
    VALUE_57("084"),
    @XmlEnumValue("08423")
    VALUE_58("08423"),
    @XmlEnumValue("086")
    VALUE_59("086"),
    @XmlEnumValue("09")
    VALUE_60("09"),
    @XmlEnumValue("091")
    VALUE_61("091"),
    @XmlEnumValue("0912")
    VALUE_62("0912"),
    @XmlEnumValue("09131")
    VALUE_63("09131"),
    @XmlEnumValue("098")
    VALUE_64("098"),
    @XmlEnumValue("10")
    VALUE_65("10"),
    @XmlEnumValue("101")
    VALUE_66("101"),
    @XmlEnumValue("10112")
    VALUE_67("10112"),
    @XmlEnumValue("102")
    VALUE_68("102"),
    @XmlEnumValue("103")
    VALUE_69("103"),
    @XmlEnumValue("1031")
    VALUE_70("1031"),
    @XmlEnumValue("1032")
    VALUE_71("1032"),
    @XmlEnumValue("104")
    VALUE_72("104"),
    @XmlEnumValue("105")
    VALUE_73("105"),
    @XmlEnumValue("106")
    VALUE_74("106"),
    @XmlEnumValue("107")
    VALUE_75("107"),
    @XmlEnumValue("108")
    VALUE_76("108"),
    @XmlEnumValue("109")
    VALUE_77("109"),
    @XmlEnumValue("11")
    VALUE_78("11"),
    @XmlEnumValue("111")
    VALUE_79("111"),
    @XmlEnumValue("11111")
    VALUE_80("11111"),
    @XmlEnumValue("11112")
    VALUE_81("11112"),
    @XmlEnumValue("112")
    VALUE_82("112"),
    @XmlEnumValue("1121")
    VALUE_83("1121"),
    @XmlEnumValue("13")
    VALUE_84("13"),
    @XmlEnumValue("131")
    VALUE_85("131"),
    @XmlEnumValue("132")
    VALUE_86("132"),
    @XmlEnumValue("14")
    VALUE_87("14"),
    @XmlEnumValue("141")
    VALUE_88("141"),
    @XmlEnumValue("142")
    VALUE_89("142"),
    @XmlEnumValue("14211")
    VALUE_90("14211"),
    @XmlEnumValue("14212")
    VALUE_91("14212"),
    @XmlEnumValue("14219")
    VALUE_92("14219"),
    @XmlEnumValue("144")
    VALUE_93("144"),
    @XmlEnumValue("14411")
    VALUE_94("14411"),
    @XmlEnumValue("14412")
    VALUE_95("14412"),
    @XmlEnumValue("14413")
    VALUE_96("14413"),
    @XmlEnumValue("145")
    VALUE_97("145"),
    @XmlEnumValue("14511")
    VALUE_98("14511"),
    @XmlEnumValue("14512")
    VALUE_99("14512"),
    @XmlEnumValue("14514")
    VALUE_100("14514"),
    @XmlEnumValue("147")
    VALUE_101("147"),
    @XmlEnumValue("14711")
    VALUE_102("14711"),
    @XmlEnumValue("14713")
    VALUE_103("14713"),
    @XmlEnumValue("14714")
    VALUE_104("14714"),
    @XmlEnumValue("14715")
    VALUE_105("14715"),
    @XmlEnumValue("14716")
    VALUE_106("14716"),
    @XmlEnumValue("149")
    VALUE_107("149"),
    @XmlEnumValue("14911")
    VALUE_108("14911"),
    @XmlEnumValue("14913")
    VALUE_109("14913"),
    @XmlEnumValue("14914")
    VALUE_110("14914"),
    @XmlEnumValue("19")
    VALUE_111("19"),
    @XmlEnumValue("191")
    VALUE_112("191"),
    @XmlEnumValue("192")
    VALUE_113("192"),
    @XmlEnumValue("193")
    VALUE_114("193"),
    @XmlEnumValue("194")
    VALUE_115("194"),
    @XmlEnumValue("195")
    VALUE_116("195"),
    @XmlEnumValue("196")
    VALUE_117("196"),
    @XmlEnumValue("199")
    VALUE_118("199"),
    @XmlEnumValue("20")
    VALUE_119("20"),
    @XmlEnumValue("201")
    VALUE_120("201"),
    @XmlEnumValue("2011")
    VALUE_121("2011"),
    @XmlEnumValue("2012")
    VALUE_122("2012"),
    @XmlEnumValue("2013")
    VALUE_123("2013"),
    @XmlEnumValue("2014")
    VALUE_124("2014"),
    @XmlEnumValue("20141")
    VALUE_125("20141"),
    @XmlEnumValue("2015")
    VALUE_126("2015"),
    @XmlEnumValue("2016")
    VALUE_127("2016"),
    @XmlEnumValue("2017")
    VALUE_128("2017"),
    @XmlEnumValue("202")
    VALUE_129("202"),
    @XmlEnumValue("2021")
    VALUE_130("2021"),
    @XmlEnumValue("2023")
    VALUE_131("2023"),
    @XmlEnumValue("2024")
    VALUE_132("2024"),
    @XmlEnumValue("2025")
    VALUE_133("2025"),
    @XmlEnumValue("2026")
    VALUE_134("2026"),
    @XmlEnumValue("203")
    VALUE_135("203"),
    @XmlEnumValue("2031")
    VALUE_136("2031"),
    @XmlEnumValue("2032")
    VALUE_137("2032"),
    @XmlEnumValue("2033")
    VALUE_138("2033"),
    @XmlEnumValue("2034")
    VALUE_139("2034"),
    @XmlEnumValue("2035")
    VALUE_140("2035"),
    @XmlEnumValue("2036")
    VALUE_141("2036"),
    @XmlEnumValue("2037")
    VALUE_142("2037"),
    @XmlEnumValue("2038")
    VALUE_143("2038"),
    @XmlEnumValue("2039")
    VALUE_144("2039"),
    @XmlEnumValue("204")
    VALUE_145("204"),
    @XmlEnumValue("2041")
    VALUE_146("2041"),
    @XmlEnumValue("20411")
    VALUE_147("20411"),
    @XmlEnumValue("20412")
    VALUE_148("20412"),
    @XmlEnumValue("20421")
    VALUE_149("20421"),
    @XmlEnumValue("20423")
    VALUE_150("20423"),
    @XmlEnumValue("2043")
    VALUE_151("2043"),
    @XmlEnumValue("2044")
    VALUE_152("2044"),
    @XmlEnumValue("2045")
    VALUE_153("2045"),
    @XmlEnumValue("2046")
    VALUE_154("2046"),
    @XmlEnumValue("20461")
    VALUE_155("20461"),
    @XmlEnumValue("20462")
    VALUE_156("20462"),
    @XmlEnumValue("20463")
    VALUE_157("20463"),
    @XmlEnumValue("20471")
    VALUE_158("20471"),
    @XmlEnumValue("20472")
    VALUE_159("20472"),
    @XmlEnumValue("205")
    VALUE_160("205"),
    @XmlEnumValue("206")
    VALUE_161("206"),
    @XmlEnumValue("2061")
    VALUE_162("2061"),
    @XmlEnumValue("20611")
    VALUE_163("20611"),
    @XmlEnumValue("20616")
    VALUE_164("20616"),
    @XmlEnumValue("20617")
    VALUE_165("20617"),
    @XmlEnumValue("2062")
    VALUE_166("2062"),
    @XmlEnumValue("20625")
    VALUE_167("20625"),
    @XmlEnumValue("20626")
    VALUE_168("20626"),
    @XmlEnumValue("207")
    VALUE_169("207"),
    @XmlEnumValue("208")
    VALUE_170("208"),
    @XmlEnumValue("20821")
    VALUE_171("20821"),
    @XmlEnumValue("20823")
    VALUE_172("20823"),
    @XmlEnumValue("2083")
    VALUE_173("2083"),
    @XmlEnumValue("2084")
    VALUE_174("2084"),
    @XmlEnumValue("20851")
    VALUE_175("20851"),
    @XmlEnumValue("20859")
    VALUE_176("20859"),
    @XmlEnumValue("2086")
    VALUE_177("2086"),
    @XmlEnumValue("2087")
    VALUE_178("2087"),
    @XmlEnumValue("209")
    VALUE_179("209"),
    @XmlEnumValue("20911")
    VALUE_180("20911"),
    @XmlEnumValue("20914")
    VALUE_181("20914"),
    @XmlEnumValue("20921")
    VALUE_182("20921"),
    @XmlEnumValue("20923")
    VALUE_183("20923"),
    @XmlEnumValue("2093")
    VALUE_184("2093"),
    @XmlEnumValue("2094")
    VALUE_185("2094"),
    @XmlEnumValue("2095")
    VALUE_186("2095"),
    @XmlEnumValue("2096")
    VALUE_187("2096"),
    @XmlEnumValue("2097")
    VALUE_188("2097"),
    @XmlEnumValue("2098")
    VALUE_189("2098"),
    @XmlEnumValue("21")
    VALUE_190("21"),
    @XmlEnumValue("211")
    VALUE_191("211"),
    @XmlEnumValue("212")
    VALUE_192("212"),
    @XmlEnumValue("213")
    VALUE_193("213"),
    @XmlEnumValue("214")
    VALUE_194("214"),
    @XmlEnumValue("22")
    VALUE_195("22"),
    @XmlEnumValue("221")
    VALUE_196("221"),
    @XmlEnumValue("222")
    VALUE_197("222"),
    @XmlEnumValue("223")
    VALUE_198("223"),
    @XmlEnumValue("224")
    VALUE_199("224"),
    @XmlEnumValue("225")
    VALUE_200("225"),
    @XmlEnumValue("227")
    VALUE_201("227"),
    @XmlEnumValue("228")
    VALUE_202("228"),
    @XmlEnumValue("229")
    VALUE_203("229"),
    @XmlEnumValue("2296")
    VALUE_204("2296"),
    @XmlEnumValue("2297")
    VALUE_205("2297"),
    @XmlEnumValue("2298")
    VALUE_206("2298"),
    @XmlEnumValue("23")
    VALUE_207("23"),
    @XmlEnumValue("231")
    VALUE_208("231"),
    @XmlEnumValue("233")
    VALUE_209("233"),
    @XmlEnumValue("235")
    VALUE_210("235"),
    @XmlEnumValue("237")
    VALUE_211("237"),
    @XmlEnumValue("238")
    VALUE_212("238"),
    @XmlEnumValue("239")
    VALUE_213("239"),
    @XmlEnumValue("24")
    VALUE_214("24"),
    @XmlEnumValue("241")
    VALUE_215("241"),
    @XmlEnumValue("24114")
    VALUE_216("24114"),
    @XmlEnumValue("24115")
    VALUE_217("24115"),
    @XmlEnumValue("24116")
    VALUE_218("24116"),
    @XmlEnumValue("242")
    VALUE_219("242"),
    @XmlEnumValue("2421")
    VALUE_220("2421"),
    @XmlEnumValue("24212")
    VALUE_221("24212"),
    @XmlEnumValue("2429")
    VALUE_222("2429"),
    @XmlEnumValue("243")
    VALUE_223("243"),
    @XmlEnumValue("2431")
    VALUE_224("2431"),
    @XmlEnumValue("2432")
    VALUE_225("2432"),
    @XmlEnumValue("244")
    VALUE_226("244"),
    @XmlEnumValue("249")
    VALUE_227("249"),
    @XmlEnumValue("2491")
    VALUE_228("2491"),
    @XmlEnumValue("25")
    VALUE_229("25"),
    @XmlEnumValue("251")
    VALUE_230("251"),
    @XmlEnumValue("253")
    VALUE_231("253"),
    @XmlEnumValue("254")
    VALUE_232("254"),
    @XmlEnumValue("259")
    VALUE_233("259"),
    @XmlEnumValue("26")
    VALUE_234("26"),
    @XmlEnumValue("261")
    VALUE_235("261"),
    @XmlEnumValue("26111")
    VALUE_236("26111"),
    @XmlEnumValue("262")
    VALUE_237("262"),
    @XmlEnumValue("26211")
    VALUE_238("26211"),
    @XmlEnumValue("26212")
    VALUE_239("26212"),
    @XmlEnumValue("26213")
    VALUE_240("26213"),
    @XmlEnumValue("26214")
    VALUE_241("26214"),
    @XmlEnumValue("26217")
    VALUE_242("26217"),
    @XmlEnumValue("26218")
    VALUE_243("26218"),
    @XmlEnumValue("263")
    VALUE_244("263"),
    @XmlEnumValue("264")
    VALUE_245("264"),
    @XmlEnumValue("2643")
    VALUE_246("2643"),
    @XmlEnumValue("26471")
    VALUE_247("26471"),
    @XmlEnumValue("265")
    VALUE_248("265"),
    @XmlEnumValue("266")
    VALUE_249("266"),
    @XmlEnumValue("26613")
    VALUE_250("26613"),
    @XmlEnumValue("27")
    VALUE_251("27"),
    @XmlEnumValue("271")
    VALUE_252("271"),
    @XmlEnumValue("272")
    VALUE_253("272"),
    @XmlEnumValue("273")
    VALUE_254("273"),
    @XmlEnumValue("274")
    VALUE_255("274"),
    @XmlEnumValue("276")
    VALUE_256("276"),
    @XmlEnumValue("277")
    VALUE_257("277"),
    @XmlEnumValue("278")
    VALUE_258("278"),
    @XmlEnumValue("279")
    VALUE_259("279"),
    @XmlEnumValue("28")
    VALUE_260("28"),
    @XmlEnumValue("281")
    VALUE_261("281"),
    @XmlEnumValue("2812")
    VALUE_262("2812"),
    @XmlEnumValue("28123")
    VALUE_263("28123"),
    @XmlEnumValue("2813")
    VALUE_264("2813"),
    @XmlEnumValue("2814")
    VALUE_265("2814"),
    @XmlEnumValue("2816")
    VALUE_266("2816"),
    @XmlEnumValue("2818")
    VALUE_267("2818"),
    @XmlEnumValue("28184")
    VALUE_268("28184"),
    @XmlEnumValue("2819")
    VALUE_269("2819"),
    @XmlEnumValue("28193")
    VALUE_270("28193"),
    @XmlEnumValue("282")
    VALUE_271("282"),
    @XmlEnumValue("28212")
    VALUE_272("28212"),
    @XmlEnumValue("28213")
    VALUE_273("28213"),
    @XmlEnumValue("283")
    VALUE_274("283"),
    @XmlEnumValue("284")
    VALUE_275("284"),
    @XmlEnumValue("2841")
    VALUE_276("2841"),
    @XmlEnumValue("285")
    VALUE_277("285"),
    @XmlEnumValue("286")
    VALUE_278("286"),
    @XmlEnumValue("287")
    VALUE_279("287"),
    @XmlEnumValue("2871")
    VALUE_280("2871"),
    @XmlEnumValue("289")
    VALUE_281("289"),
    @XmlEnumValue("2892")
    VALUE_282("2892"),
    @XmlEnumValue("28991")
    VALUE_283("28991"),
    @XmlEnumValue("29")
    VALUE_284("29"),
    @XmlEnumValue("291")
    VALUE_285("291"),
    @XmlEnumValue("29111")
    VALUE_286("29111"),
    @XmlEnumValue("29112")
    VALUE_287("29112"),
    @XmlEnumValue("29113")
    VALUE_288("29113"),
    @XmlEnumValue("29114")
    VALUE_289("29114"),
    @XmlEnumValue("29115")
    VALUE_290("29115"),
    @XmlEnumValue("29116")
    VALUE_291("29116"),
    @XmlEnumValue("29117")
    VALUE_292("29117"),
    @XmlEnumValue("29119")
    VALUE_293("29119"),
    @XmlEnumValue("2912")
    VALUE_294("2912"),
    @XmlEnumValue("295")
    VALUE_295("295"),
    @XmlEnumValue("2951")
    VALUE_296("2951"),
    @XmlEnumValue("2952")
    VALUE_297("2952"),
    @XmlEnumValue("299")
    VALUE_298("299"),
    @XmlEnumValue("29911")
    VALUE_299("29911"),
    @XmlEnumValue("29913")
    VALUE_300("29913"),
    @XmlEnumValue("29914")
    VALUE_301("29914"),
    @XmlEnumValue("30")
    VALUE_302("30"),
    @XmlEnumValue("301")
    VALUE_303("301"),
    @XmlEnumValue("302")
    VALUE_304("302"),
    @XmlEnumValue("303")
    VALUE_305("303"),
    @XmlEnumValue("304")
    VALUE_306("304"),
    @XmlEnumValue("306")
    VALUE_307("306"),
    @XmlEnumValue("307")
    VALUE_308("307"),
    @XmlEnumValue("31")
    VALUE_309("31"),
    @XmlEnumValue("311")
    VALUE_310("311"),
    @XmlEnumValue("312")
    VALUE_311("312"),
    @XmlEnumValue("313")
    VALUE_312("313"),
    @XmlEnumValue("314")
    VALUE_313("314"),
    @XmlEnumValue("315")
    VALUE_314("315"),
    @XmlEnumValue("316")
    VALUE_315("316"),
    @XmlEnumValue("319")
    VALUE_316("319"),
    @XmlEnumValue("32")
    VALUE_317("32"),
    @XmlEnumValue("321")
    VALUE_318("321"),
    @XmlEnumValue("322")
    VALUE_319("322"),
    @XmlEnumValue("3221")
    VALUE_320("3221"),
    @XmlEnumValue("324")
    VALUE_321("324"),
    @XmlEnumValue("32411")
    VALUE_322("32411"),
    @XmlEnumValue("325")
    VALUE_323("325"),
    @XmlEnumValue("3251")
    VALUE_324("3251"),
    @XmlEnumValue("32511")
    VALUE_325("32511"),
    @XmlEnumValue("3253")
    VALUE_326("3253"),
    @XmlEnumValue("3255")
    VALUE_327("3255"),
    @XmlEnumValue("3259")
    VALUE_328("3259"),
    @XmlEnumValue("32594")
    VALUE_329("32594"),
    @XmlEnumValue("326")
    VALUE_330("326"),
    @XmlEnumValue("327")
    VALUE_331("327"),
    @XmlEnumValue("3271")
    VALUE_332("3271"),
    @XmlEnumValue("3274")
    VALUE_333("3274"),
    @XmlEnumValue("3275")
    VALUE_334("3275"),
    @XmlEnumValue("328")
    VALUE_335("328"),
    @XmlEnumValue("329")
    VALUE_336("329"),
    @XmlEnumValue("3291")
    VALUE_337("3291"),
    @XmlEnumValue("3295")
    VALUE_338("3295"),
    @XmlEnumValue("33")
    VALUE_339("33"),
    @XmlEnumValue("331")
    VALUE_340("331"),
    @XmlEnumValue("33111")
    VALUE_341("33111"),
    @XmlEnumValue("33112")
    VALUE_342("33112"),
    @XmlEnumValue("33119")
    VALUE_343("33119"),
    @XmlEnumValue("3312")
    VALUE_344("3312"),
    @XmlEnumValue("33121")
    VALUE_345("33121"),
    @XmlEnumValue("3313")
    VALUE_346("3313"),
    @XmlEnumValue("3315")
    VALUE_347("3315"),
    @XmlEnumValue("332")
    VALUE_348("332"),
    @XmlEnumValue("33211")
    VALUE_349("33211"),
    @XmlEnumValue("333")
    VALUE_350("333"),
    @XmlEnumValue("3331")
    VALUE_351("3331"),
    @XmlEnumValue("3332")
    VALUE_352("3332"),
    @XmlEnumValue("3333")
    VALUE_353("3333"),
    @XmlEnumValue("3334")
    VALUE_354("3334"),
    @XmlEnumValue("335")
    VALUE_355("335"),
    @XmlEnumValue("3351")
    VALUE_356("3351"),
    @XmlEnumValue("3352")
    VALUE_357("3352"),
    @XmlEnumValue("3357")
    VALUE_358("3357"),
    @XmlEnumValue("336")
    VALUE_359("336"),
    @XmlEnumValue("3361")
    VALUE_360("3361"),
    @XmlEnumValue("3362")
    VALUE_361("3362"),
    @XmlEnumValue("339")
    VALUE_362("339"),
    @XmlEnumValue("3391")
    VALUE_363("3391"),
    @XmlEnumValue("3392")
    VALUE_364("3392"),
    @XmlEnumValue("34")
    VALUE_365("34"),
    @XmlEnumValue("341")
    VALUE_366("341"),
    @XmlEnumValue("342")
    VALUE_367("342"),
    @XmlEnumValue("343")
    VALUE_368("343"),
    @XmlEnumValue("3433")
    VALUE_369("3433"),
    @XmlEnumValue("344")
    VALUE_370("344"),
    @XmlEnumValue("3441")
    VALUE_371("3441"),
    @XmlEnumValue("34411")
    VALUE_372("34411"),
    @XmlEnumValue("345")
    VALUE_373("345"),
    @XmlEnumValue("346")
    VALUE_374("346"),
    @XmlEnumValue("348")
    VALUE_375("348"),
    @XmlEnumValue("349")
    VALUE_376("349"),
    @XmlEnumValue("3491")
    VALUE_377("3491"),
    @XmlEnumValue("3494")
    VALUE_378("3494"),
    @XmlEnumValue("35")
    VALUE_379("35"),
    @XmlEnumValue("351")
    VALUE_380("351"),
    @XmlEnumValue("352")
    VALUE_381("352"),
    @XmlEnumValue("3524")
    VALUE_382("3524"),
    @XmlEnumValue("353")
    VALUE_383("353"),
    @XmlEnumValue("3531")
    VALUE_384("3531"),
    @XmlEnumValue("3532")
    VALUE_385("3532"),
    @XmlEnumValue("3533")
    VALUE_386("3533"),
    @XmlEnumValue("3537")
    VALUE_387("3537"),
    @XmlEnumValue("354")
    VALUE_388("354"),
    @XmlEnumValue("355")
    VALUE_389("355"),
    @XmlEnumValue("356")
    VALUE_390("356"),
    @XmlEnumValue("357")
    VALUE_391("357"),
    @XmlEnumValue("358")
    VALUE_392("358"),
    @XmlEnumValue("359")
    VALUE_393("359"),
    @XmlEnumValue("36")
    VALUE_394("36"),
    @XmlEnumValue("361")
    VALUE_395("361"),
    @XmlEnumValue("362")
    VALUE_396("362"),
    @XmlEnumValue("363")
    VALUE_397("363"),
    @XmlEnumValue("3631")
    VALUE_398("3631"),
    @XmlEnumValue("3632")
    VALUE_399("3632"),
    @XmlEnumValue("3633")
    VALUE_400("3633"),
    @XmlEnumValue("364")
    VALUE_401("364"),
    @XmlEnumValue("365")
    VALUE_402("365"),
    @XmlEnumValue("366")
    VALUE_403("366"),
    @XmlEnumValue("367")
    VALUE_404("367"),
    @XmlEnumValue("369")
    VALUE_405("369"),
    @XmlEnumValue("37")
    VALUE_406("37"),
    @XmlEnumValue("371")
    VALUE_407("371"),
    @XmlEnumValue("3711")
    VALUE_408("3711"),
    @XmlEnumValue("37111")
    VALUE_409("37111"),
    @XmlEnumValue("37112")
    VALUE_410("37112"),
    @XmlEnumValue("37113")
    VALUE_411("37113"),
    @XmlEnumValue("3712")
    VALUE_412("3712"),
    @XmlEnumValue("3713")
    VALUE_413("3713"),
    @XmlEnumValue("3714")
    VALUE_414("3714"),
    @XmlEnumValue("37147")
    VALUE_415("37147"),
    @XmlEnumValue("3715")
    VALUE_416("3715"),
    @XmlEnumValue("372")
    VALUE_417("372"),
    @XmlEnumValue("373")
    VALUE_418("373"),
    @XmlEnumValue("374")
    VALUE_419("374"),
    @XmlEnumValue("37422")
    VALUE_420("37422"),
    @XmlEnumValue("375")
    VALUE_421("375"),
    @XmlEnumValue("376")
    VALUE_422("376"),
    @XmlEnumValue("379")
    VALUE_423("379"),
    @XmlEnumValue("38")
    VALUE_424("38"),
    @XmlEnumValue("381")
    VALUE_425("381"),
    @XmlEnumValue("382")
    VALUE_426("382"),
    @XmlEnumValue("383")
    VALUE_427("383"),
    @XmlEnumValue("384")
    VALUE_428("384"),
    @XmlEnumValue("385")
    VALUE_429("385"),
    @XmlEnumValue("386")
    VALUE_430("386"),
    @XmlEnumValue("387")
    VALUE_431("387"),
    @XmlEnumValue("39")
    VALUE_432("39"),
    @XmlEnumValue("391")
    VALUE_433("391"),
    @XmlEnumValue("393")
    VALUE_434("393"),
    @XmlEnumValue("394")
    VALUE_435("394"),
    @XmlEnumValue("3949")
    VALUE_436("3949"),
    @XmlEnumValue("395")
    VALUE_437("395"),
    @XmlEnumValue("396")
    VALUE_438("396"),
    @XmlEnumValue("399")
    VALUE_439("399"),
    @XmlEnumValue("40")
    VALUE_440("40"),
    @XmlEnumValue("401")
    VALUE_441("401"),
    @XmlEnumValue("402")
    VALUE_442("402"),
    @XmlEnumValue("4021")
    VALUE_443("4021"),
    @XmlEnumValue("40211")
    VALUE_444("40211"),
    @XmlEnumValue("4022")
    VALUE_445("4022"),
    @XmlEnumValue("4024")
    VALUE_446("4024"),
    @XmlEnumValue("4026")
    VALUE_447("4026"),
    @XmlEnumValue("41")
    VALUE_448("41"),
    @XmlEnumValue("411")
    VALUE_449("411"),
    @XmlEnumValue("41111")
    VALUE_450("41111"),
    @XmlEnumValue("41114")
    VALUE_451("41114"),
    @XmlEnumValue("41115")
    VALUE_452("41115"),
    @XmlEnumValue("412")
    VALUE_453("412"),
    @XmlEnumValue("42")
    VALUE_454("42"),
    @XmlEnumValue("421")
    VALUE_455("421"),
    @XmlEnumValue("422")
    VALUE_456("422"),
    @XmlEnumValue("423")
    VALUE_457("423"),
    @XmlEnumValue("44")
    VALUE_458("44"),
    @XmlEnumValue("441")
    VALUE_459("441"),
    @XmlEnumValue("45")
    VALUE_460("45"),
    @XmlEnumValue("451")
    VALUE_461("451"),
    @XmlEnumValue("46")
    VALUE_462("46"),
    @XmlEnumValue("461")
    VALUE_463("461"),
    @XmlEnumValue("462")
    VALUE_464("462"),
    @XmlEnumValue("48")
    VALUE_465("48");
    private final String value;

    CClaveProdSTCC(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CClaveProdSTCC fromValue(String v) {
        for (CClaveProdSTCC c: CClaveProdSTCC.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
