//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.catalogos.CartaPorte;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_ContenedorMaritimo.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="c_ContenedorMaritimo">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <whiteSpace value="collapse"/>
 *     <enumeration value="CM001"/>
 *     <enumeration value="CM002"/>
 *     <enumeration value="CM003"/>
 *     <enumeration value="CM004"/>
 *     <enumeration value="CM005"/>
 *     <enumeration value="CM006"/>
 *     <enumeration value="CM007"/>
 *     <enumeration value="CM008"/>
 *     <enumeration value="CM009"/>
 *     <enumeration value="CM010"/>
 *     <enumeration value="CM011"/>
 *     <enumeration value="CM012"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "c_ContenedorMaritimo", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte")
@XmlEnum
public enum CContenedorMaritimo {

    @XmlEnumValue("CM001")
    CM_001("CM001"),
    @XmlEnumValue("CM002")
    CM_002("CM002"),
    @XmlEnumValue("CM003")
    CM_003("CM003"),
    @XmlEnumValue("CM004")
    CM_004("CM004"),
    @XmlEnumValue("CM005")
    CM_005("CM005"),
    @XmlEnumValue("CM006")
    CM_006("CM006"),
    @XmlEnumValue("CM007")
    CM_007("CM007"),
    @XmlEnumValue("CM008")
    CM_008("CM008"),
    @XmlEnumValue("CM009")
    CM_009("CM009"),
    @XmlEnumValue("CM010")
    CM_010("CM010"),
    @XmlEnumValue("CM011")
    CM_011("CM011"),
    @XmlEnumValue("CM012")
    CM_012("CM012");
    private final String value;

    CContenedorMaritimo(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CContenedorMaritimo fromValue(String v) {
        for (CContenedorMaritimo c: CContenedorMaritimo.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
