//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.catalogos.CartaPorte;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_ConfigMaritima.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="c_ConfigMaritima">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <whiteSpace value="collapse"/>
 *     <enumeration value="B01"/>
 *     <enumeration value="B02"/>
 *     <enumeration value="B03"/>
 *     <enumeration value="B04"/>
 *     <enumeration value="B05"/>
 *     <enumeration value="B06"/>
 *     <enumeration value="B07"/>
 *     <enumeration value="B08"/>
 *     <enumeration value="B09"/>
 *     <enumeration value="B10"/>
 *     <enumeration value="B11"/>
 *     <enumeration value="B12"/>
 *     <enumeration value="B13"/>
 *     <enumeration value="B14"/>
 *     <enumeration value="B15"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "c_ConfigMaritima", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte")
@XmlEnum
public enum CConfigMaritima {

    @XmlEnumValue("B01")
    B_01("B01"),
    @XmlEnumValue("B02")
    B_02("B02"),
    @XmlEnumValue("B03")
    B_03("B03"),
    @XmlEnumValue("B04")
    B_04("B04"),
    @XmlEnumValue("B05")
    B_05("B05"),
    @XmlEnumValue("B06")
    B_06("B06"),
    @XmlEnumValue("B07")
    B_07("B07"),
    @XmlEnumValue("B08")
    B_08("B08"),
    @XmlEnumValue("B09")
    B_09("B09"),
    @XmlEnumValue("B10")
    B_10("B10"),
    @XmlEnumValue("B11")
    B_11("B11"),
    @XmlEnumValue("B12")
    B_12("B12"),
    @XmlEnumValue("B13")
    B_13("B13"),
    @XmlEnumValue("B14")
    B_14("B14"),
    @XmlEnumValue("B15")
    B_15("B15");
    private final String value;

    CConfigMaritima(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CConfigMaritima fromValue(String v) {
        for (CConfigMaritima c: CConfigMaritima.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
