//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.catalogos.CartaPorte;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_ConfigAutotransporte.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="c_ConfigAutotransporte">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <whiteSpace value="collapse"/>
 *     <enumeration value="C2"/>
 *     <enumeration value="C3"/>
 *     <enumeration value="C2R2"/>
 *     <enumeration value="C3R2"/>
 *     <enumeration value="C2R3"/>
 *     <enumeration value="C3R3"/>
 *     <enumeration value="T2S1"/>
 *     <enumeration value="T2S2"/>
 *     <enumeration value="T2S3"/>
 *     <enumeration value="T3S1"/>
 *     <enumeration value="T3S2"/>
 *     <enumeration value="T3S3"/>
 *     <enumeration value="T2S1R2"/>
 *     <enumeration value="T2S2R2"/>
 *     <enumeration value="T2S1R3"/>
 *     <enumeration value="T3S1R2"/>
 *     <enumeration value="T3S1R3"/>
 *     <enumeration value="T3S2R2"/>
 *     <enumeration value="T3S2R3"/>
 *     <enumeration value="T3S2R4"/>
 *     <enumeration value="T2S2S2"/>
 *     <enumeration value="T3S2S2"/>
 *     <enumeration value="T3S3S2"/>
 *     <enumeration value="OTROEV"/>
 *     <enumeration value="OTROEGP"/>
 *     <enumeration value="OTROSG"/>
 *     <enumeration value="VL"/>
 *     <enumeration value="OTROEVGP"/>
 *     <enumeration value="GPLUTA"/>
 *     <enumeration value="GPLUTB"/>
 *     <enumeration value="GPLUTC"/>
 *     <enumeration value="GPLUTD"/>
 *     <enumeration value="GPLATA"/>
 *     <enumeration value="GPLATB"/>
 *     <enumeration value="GPLATC"/>
 *     <enumeration value="GPLATD"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "c_ConfigAutotransporte", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte")
@XmlEnum
public enum CConfigAutotransporte {

    @XmlEnumValue("C2")
    C_2("C2"),
    @XmlEnumValue("C3")
    C_3("C3"),
    @XmlEnumValue("C2R2")
    C_2_R_2("C2R2"),
    @XmlEnumValue("C3R2")
    C_3_R_2("C3R2"),
    @XmlEnumValue("C2R3")
    C_2_R_3("C2R3"),
    @XmlEnumValue("C3R3")
    C_3_R_3("C3R3"),
    @XmlEnumValue("T2S1")
    T_2_S_1("T2S1"),
    @XmlEnumValue("T2S2")
    T_2_S_2("T2S2"),
    @XmlEnumValue("T2S3")
    T_2_S_3("T2S3"),
    @XmlEnumValue("T3S1")
    T_3_S_1("T3S1"),
    @XmlEnumValue("T3S2")
    T_3_S_2("T3S2"),
    @XmlEnumValue("T3S3")
    T_3_S_3("T3S3"),
    @XmlEnumValue("T2S1R2")
    T_2_S_1_R_2("T2S1R2"),
    @XmlEnumValue("T2S2R2")
    T_2_S_2_R_2("T2S2R2"),
    @XmlEnumValue("T2S1R3")
    T_2_S_1_R_3("T2S1R3"),
    @XmlEnumValue("T3S1R2")
    T_3_S_1_R_2("T3S1R2"),
    @XmlEnumValue("T3S1R3")
    T_3_S_1_R_3("T3S1R3"),
    @XmlEnumValue("T3S2R2")
    T_3_S_2_R_2("T3S2R2"),
    @XmlEnumValue("T3S2R3")
    T_3_S_2_R_3("T3S2R3"),
    @XmlEnumValue("T3S2R4")
    T_3_S_2_R_4("T3S2R4"),
    @XmlEnumValue("T2S2S2")
    T_2_S_2_S_2("T2S2S2"),
    @XmlEnumValue("T3S2S2")
    T_3_S_2_S_2("T3S2S2"),
    @XmlEnumValue("T3S3S2")
    T_3_S_3_S_2("T3S3S2"),
    OTROEV("OTROEV"),
    OTROEGP("OTROEGP"),
    OTROSG("OTROSG"),
    VL("VL"),
    OTROEVGP("OTROEVGP"),
    GPLUTA("GPLUTA"),
    GPLUTB("GPLUTB"),
    GPLUTC("GPLUTC"),
    GPLUTD("GPLUTD"),
    GPLATA("GPLATA"),
    GPLATB("GPLATB"),
    GPLATC("GPLATC"),
    GPLATD("GPLATD");
    private final String value;

    CConfigAutotransporte(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CConfigAutotransporte fromValue(String v) {
        for (CConfigAutotransporte c: CConfigAutotransporte.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
