//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.catalogos.CartaPorte;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_Contenedor.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="c_Contenedor">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <whiteSpace value="collapse"/>
 *     <enumeration value="TC01"/>
 *     <enumeration value="TC02"/>
 *     <enumeration value="TC03"/>
 *     <enumeration value="TC04"/>
 *     <enumeration value="TC05"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "c_Contenedor", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte")
@XmlEnum
public enum CContenedor {

    @XmlEnumValue("TC01")
    TC_01("TC01"),
    @XmlEnumValue("TC02")
    TC_02("TC02"),
    @XmlEnumValue("TC03")
    TC_03("TC03"),
    @XmlEnumValue("TC04")
    TC_04("TC04"),
    @XmlEnumValue("TC05")
    TC_05("TC05");
    private final String value;

    CContenedor(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CContenedor fromValue(String v) {
        for (CContenedor c: CContenedor.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
