//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.catalogos.CartaPorte;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_NumAutorizacionNaviero.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="c_NumAutorizacionNaviero">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <whiteSpace value="collapse"/>
 *     <enumeration value="ANC001/2022"/>
 *     <enumeration value="ANC001/2023"/>
 *     <enumeration value="ANC002/2022"/>
 *     <enumeration value="ANC002/2024"/>
 *     <enumeration value="ANC003/2023"/>
 *     <enumeration value="ANC003/2024"/>
 *     <enumeration value="ANC004/2023"/>
 *     <enumeration value="ANC005/2022"/>
 *     <enumeration value="ANC005/2023"/>
 *     <enumeration value="ANC005/2024"/>
 *     <enumeration value="ANC006/2024"/>
 *     <enumeration value="ANC007/2024"/>
 *     <enumeration value="ANC009/2024"/>
 *     <enumeration value="ANC011/2022"/>
 *     <enumeration value="ANC012/2022"/>
 *     <enumeration value="ANC013/2023"/>
 *     <enumeration value="ANC016/2023"/>
 *     <enumeration value="ANC019/2022"/>
 *     <enumeration value="ANC021/2022"/>
 *     <enumeration value="ANC022/2022"/>
 *     <enumeration value="ANC023/2022"/>
 *     <enumeration value="ANC025/2023"/>
 *     <enumeration value="ANC025/2025"/>
 *     <enumeration value="ANC027/2022"/>
 *     <enumeration value="ANC027/2023"/>
 *     <enumeration value="ANC027/2025"/>
 *     <enumeration value="ANC028/2022"/>
 *     <enumeration value="ANC028/2023"/>
 *     <enumeration value="ANC029/2022"/>
 *     <enumeration value="ANC029/2023"/>
 *     <enumeration value="ANC029/2025"/>
 *     <enumeration value="ANC032/2022"/>
 *     <enumeration value="ANC032/2023"/>
 *     <enumeration value="ANC032/2025"/>
 *     <enumeration value="ANC033/2023"/>
 *     <enumeration value="ANC033/2024"/>
 *     <enumeration value="ANC033/2025"/>
 *     <enumeration value="ANC034/2023"/>
 *     <enumeration value="ANC034/2024"/>
 *     <enumeration value="ANC034/2025"/>
 *     <enumeration value="ANC035/2022"/>
 *     <enumeration value="ANC035/2023"/>
 *     <enumeration value="ANC035/2024"/>
 *     <enumeration value="ANC035/2025"/>
 *     <enumeration value="ANC036/2023"/>
 *     <enumeration value="ANC037/2023"/>
 *     <enumeration value="ANC037/2025"/>
 *     <enumeration value="ANC038/2022"/>
 *     <enumeration value="ANC038/2023"/>
 *     <enumeration value="ANC040/2025"/>
 *     <enumeration value="ANC041/2022"/>
 *     <enumeration value="ANC041/2023"/>
 *     <enumeration value="ANC041/2025"/>
 *     <enumeration value="ANC042/2023"/>
 *     <enumeration value="ANC043/2022"/>
 *     <enumeration value="ANC044/2025"/>
 *     <enumeration value="ANC045/2025"/>
 *     <enumeration value="ANC046/2025"/>
 *     <enumeration value="ANC049/2022"/>
 *     <enumeration value="ANC051/2022"/>
 *     <enumeration value="ANC052/2022"/>
 *     <enumeration value="ANC052/2023"/>
 *     <enumeration value="ANC056/2023"/>
 *     <enumeration value="ANC057/2023"/>
 *     <enumeration value="ANC060/2022"/>
 *     <enumeration value="ANC060/2023"/>
 *     <enumeration value="ANC061/2023"/>
 *     <enumeration value="ANC062/2022"/>
 *     <enumeration value="ANC062/2023"/>
 *     <enumeration value="ANC063/2023"/>
 *     <enumeration value="ANC071/2023"/>
 *     <enumeration value="ANC072/2023"/>
 *     <enumeration value="ANC073/2023"/>
 *     <enumeration value="ANC074/2023"/>
 *     <enumeration value="ANC41/2021"/>
 *     <enumeration value="ANC47/2021"/>
 *     <enumeration value="ANC49/2021"/>
 *     <enumeration value="ANC54/2021"/>
 *     <enumeration value="ANC58/2021"/>
 *     <enumeration value="ANG001/2024"/>
 *     <enumeration value="ANG001/2025"/>
 *     <enumeration value="ANG002/2023"/>
 *     <enumeration value="ANG003/2022"/>
 *     <enumeration value="ANG004/2022"/>
 *     <enumeration value="ANG004/2024"/>
 *     <enumeration value="ANG005/2022"/>
 *     <enumeration value="ANG005/2023"/>
 *     <enumeration value="ANG005/2025"/>
 *     <enumeration value="ANG006/2022"/>
 *     <enumeration value="ANG006/2023"/>
 *     <enumeration value="ANG006/2024"/>
 *     <enumeration value="ANG006/2025"/>
 *     <enumeration value="ANG007/2022"/>
 *     <enumeration value="ANG007/2023"/>
 *     <enumeration value="ANG007/2024"/>
 *     <enumeration value="ANG007/2025"/>
 *     <enumeration value="ANG008/2022"/>
 *     <enumeration value="ANG008/2023"/>
 *     <enumeration value="ANG008/2024"/>
 *     <enumeration value="ANG008/2025"/>
 *     <enumeration value="ANG009/2022"/>
 *     <enumeration value="ANG009/2023"/>
 *     <enumeration value="ANG009/2025"/>
 *     <enumeration value="ANG010/2022"/>
 *     <enumeration value="ANG010/2023"/>
 *     <enumeration value="ANG010/2024"/>
 *     <enumeration value="ANG010/2025"/>
 *     <enumeration value="ANG011/2023"/>
 *     <enumeration value="ANG011/2024"/>
 *     <enumeration value="ANG012/2022"/>
 *     <enumeration value="ANG012/2023"/>
 *     <enumeration value="ANG012/2024"/>
 *     <enumeration value="ANG013/2022"/>
 *     <enumeration value="ANG013/2024"/>
 *     <enumeration value="ANG014/2022"/>
 *     <enumeration value="ANG014/2023"/>
 *     <enumeration value="ANG014/2024"/>
 *     <enumeration value="ANG015/2022"/>
 *     <enumeration value="ANG015/2023"/>
 *     <enumeration value="ANG015/2024"/>
 *     <enumeration value="ANG016/2022"/>
 *     <enumeration value="ANG016/2023"/>
 *     <enumeration value="ANG016/2024"/>
 *     <enumeration value="ANG016/2025"/>
 *     <enumeration value="ANG017/2022"/>
 *     <enumeration value="ANG017/2023"/>
 *     <enumeration value="ANG017/2024"/>
 *     <enumeration value="ANG017/2025"/>
 *     <enumeration value="ANG018/2022"/>
 *     <enumeration value="ANG018/2023"/>
 *     <enumeration value="ANG018/2024"/>
 *     <enumeration value="ANG018/2025"/>
 *     <enumeration value="ANG019/2023"/>
 *     <enumeration value="ANG019/2024"/>
 *     <enumeration value="ANG019/2025"/>
 *     <enumeration value="ANG020/2022"/>
 *     <enumeration value="ANG020/2023"/>
 *     <enumeration value="ANG020/2024"/>
 *     <enumeration value="ANG020/2025"/>
 *     <enumeration value="ANG021/2023"/>
 *     <enumeration value="ANG021/2024"/>
 *     <enumeration value="ANG021/2025"/>
 *     <enumeration value="ANG022/2023"/>
 *     <enumeration value="ANG022/2024"/>
 *     <enumeration value="ANG022/2025"/>
 *     <enumeration value="ANG023/2022"/>
 *     <enumeration value="ANG023/2023"/>
 *     <enumeration value="ANG023/2024"/>
 *     <enumeration value="ANG023/2025"/>
 *     <enumeration value="ANG024/2022"/>
 *     <enumeration value="ANG024/2023"/>
 *     <enumeration value="ANG024/2024"/>
 *     <enumeration value="ANG024/2025"/>
 *     <enumeration value="ANG025/2022"/>
 *     <enumeration value="ANG026/2022"/>
 *     <enumeration value="ANG026/2023"/>
 *     <enumeration value="ANG026/2024"/>
 *     <enumeration value="ANG026/2025"/>
 *     <enumeration value="ANG027/2024"/>
 *     <enumeration value="ANG028/2024"/>
 *     <enumeration value="ANG028/2025"/>
 *     <enumeration value="ANG029/2024"/>
 *     <enumeration value="ANG030/2022"/>
 *     <enumeration value="ANG030/2023"/>
 *     <enumeration value="ANG030/2024"/>
 *     <enumeration value="ANG030/2025"/>
 *     <enumeration value="ANG031/2022"/>
 *     <enumeration value="ANG031/2023"/>
 *     <enumeration value="ANG031/2024"/>
 *     <enumeration value="ANG031/2025"/>
 *     <enumeration value="ANG032/2024"/>
 *     <enumeration value="ANG033/2022"/>
 *     <enumeration value="ANG034/2022"/>
 *     <enumeration value="ANG034/2023"/>
 *     <enumeration value="ANG035/2023"/>
 *     <enumeration value="ANG036/2022"/>
 *     <enumeration value="ANG036/2025"/>
 *     <enumeration value="ANG037/2022"/>
 *     <enumeration value="ANG038/2025"/>
 *     <enumeration value="ANG039/2022"/>
 *     <enumeration value="ANG039/2023"/>
 *     <enumeration value="ANG040/2022"/>
 *     <enumeration value="ANG040/2023"/>
 *     <enumeration value="ANG041/2022"/>
 *     <enumeration value="ANG042/2022"/>
 *     <enumeration value="ANG042/2025"/>
 *     <enumeration value="ANG043/2022"/>
 *     <enumeration value="ANG043/2023"/>
 *     <enumeration value="ANG044/2023"/>
 *     <enumeration value="ANG045/2022"/>
 *     <enumeration value="ANG045/2023"/>
 *     <enumeration value="ANG046/2022"/>
 *     <enumeration value="ANG046/2023"/>
 *     <enumeration value="ANG047/2022"/>
 *     <enumeration value="ANG047/2023"/>
 *     <enumeration value="ANG048/2022"/>
 *     <enumeration value="ANG048/2023"/>
 *     <enumeration value="ANG049/2023"/>
 *     <enumeration value="ANG050/2022"/>
 *     <enumeration value="ANG050/2023"/>
 *     <enumeration value="ANG051/2023"/>
 *     <enumeration value="ANG052/2022"/>
 *     <enumeration value="ANG053/2022"/>
 *     <enumeration value="ANG053/2023"/>
 *     <enumeration value="ANG054/2022"/>
 *     <enumeration value="ANG054/2023"/>
 *     <enumeration value="ANG055/2022"/>
 *     <enumeration value="ANG055/2023"/>
 *     <enumeration value="ANG056/2022"/>
 *     <enumeration value="ANG057/2022"/>
 *     <enumeration value="ANG058/2022"/>
 *     <enumeration value="ANG058/2023"/>
 *     <enumeration value="ANG059/2022"/>
 *     <enumeration value="ANG059/2023"/>
 *     <enumeration value="ANG061/2022"/>
 *     <enumeration value="ANG063/2022"/>
 *     <enumeration value="ANG064/2023"/>
 *     <enumeration value="ANG065/2023"/>
 *     <enumeration value="ANG066/2023"/>
 *     <enumeration value="ANG067/2023"/>
 *     <enumeration value="ANG068/2023"/>
 *     <enumeration value="ANG069/2023"/>
 *     <enumeration value="ANG070/2023"/>
 *     <enumeration value="ANG075/2023"/>
 *     <enumeration value="ANG076/2023"/>
 *     <enumeration value="ANG39-2021"/>
 *     <enumeration value="ANG40-2021"/>
 *     <enumeration value="ANG42/2021"/>
 *     <enumeration value="ANG43/2021"/>
 *     <enumeration value="ANG44-2021"/>
 *     <enumeration value="ANG45/2021"/>
 *     <enumeration value="ANG46/2021"/>
 *     <enumeration value="ANG47/2021"/>
 *     <enumeration value="ANG48/2021"/>
 *     <enumeration value="ANG49/2021"/>
 *     <enumeration value="ANG50/2021"/>
 *     <enumeration value="ANG51/2021"/>
 *     <enumeration value="ANG52/2021"/>
 *     <enumeration value="ANG53/2021"/>
 *     <enumeration value="ANG55/2021"/>
 *     <enumeration value="ANG56/2021"/>
 *     <enumeration value="ANG57/2021"/>
 *     <enumeration value="ANG59/2021"/>
 *     <enumeration value="NAVMX-2024"/>
 *     <enumeration value="SCT418-011-2021"/>
 *     <enumeration value="SCT418-012-2021"/>
 *     <enumeration value="SCT418-014-2021"/>
 *     <enumeration value="SCT418-015-2021"/>
 *     <enumeration value="SCT418-016-2021"/>
 *     <enumeration value="SCT418-017-2021"/>
 *     <enumeration value="SCT418-018-2021"/>
 *     <enumeration value="SCT418-019-2021"/>
 *     <enumeration value="SCT418-022-2021"/>
 *     <enumeration value="SCT418-023-2021"/>
 *     <enumeration value="SCT418-024-2021"/>
 *     <enumeration value="SCT418-025-2021"/>
 *     <enumeration value="SCT418-026-2021"/>
 *     <enumeration value="SCT418-027-2021"/>
 *     <enumeration value="SCT418-028-2021"/>
 *     <enumeration value="SCT418-029-2021"/>
 *     <enumeration value="SCT418-030-2021"/>
 *     <enumeration value="SCT418-031-2021"/>
 *     <enumeration value="SCT418-032-2021"/>
 *     <enumeration value="SCT418-033-2021"/>
 *     <enumeration value="SCT418-034-2021"/>
 *     <enumeration value="SCT418-035-2021"/>
 *     <enumeration value="SCT418-036-2021"/>
 *     <enumeration value="SCT418-037-2021"/>
 *     <enumeration value="SCT418-038-2021"/>
 *     <enumeration value="SCT418/001/2017"/>
 *     <enumeration value="SCT418/001/2018"/>
 *     <enumeration value="SCT418/001/2019"/>
 *     <enumeration value="SCT418/001/2020"/>
 *     <enumeration value="SCT418/001/2021"/>
 *     <enumeration value="SCT418/002/2017"/>
 *     <enumeration value="SCT418/002/2018"/>
 *     <enumeration value="SCT418/002/2019"/>
 *     <enumeration value="SCT418/002/2020"/>
 *     <enumeration value="SCT418/002/2021"/>
 *     <enumeration value="SCT418/003/2017"/>
 *     <enumeration value="SCT418/003/2018"/>
 *     <enumeration value="SCT418/003/2019"/>
 *     <enumeration value="SCT418/003/2020"/>
 *     <enumeration value="SCT418/003/2021"/>
 *     <enumeration value="SCT418/004/2017"/>
 *     <enumeration value="SCT418/004/2018"/>
 *     <enumeration value="SCT418/004/2019"/>
 *     <enumeration value="SCT418/004/2020"/>
 *     <enumeration value="SCT418/004/2021"/>
 *     <enumeration value="SCT418/005/2017"/>
 *     <enumeration value="SCT418/005/2018"/>
 *     <enumeration value="SCT418/005/2019"/>
 *     <enumeration value="SCT418/005/2020"/>
 *     <enumeration value="SCT418/005/2021"/>
 *     <enumeration value="SCT418/006/2017"/>
 *     <enumeration value="SCT418/006/2018"/>
 *     <enumeration value="SCT418/006/2019"/>
 *     <enumeration value="SCT418/006/2020"/>
 *     <enumeration value="SCT418/006/2021"/>
 *     <enumeration value="SCT418/007/2017"/>
 *     <enumeration value="SCT418/007/2018"/>
 *     <enumeration value="SCT418/007/2019"/>
 *     <enumeration value="SCT418/007/2020"/>
 *     <enumeration value="SCT418/007/2021"/>
 *     <enumeration value="SCT418/008/2017"/>
 *     <enumeration value="SCT418/008/2018"/>
 *     <enumeration value="SCT418/008/2019"/>
 *     <enumeration value="SCT418/008/2020"/>
 *     <enumeration value="SCT418/008/2021"/>
 *     <enumeration value="SCT418/009/2017"/>
 *     <enumeration value="SCT418/009/2018"/>
 *     <enumeration value="SCT418/009/2019"/>
 *     <enumeration value="SCT418/009/2020"/>
 *     <enumeration value="SCT418/009/2021"/>
 *     <enumeration value="SCT418/010/2017"/>
 *     <enumeration value="SCT418/010/2018"/>
 *     <enumeration value="SCT418/010/2019"/>
 *     <enumeration value="SCT418/010/2020"/>
 *     <enumeration value="SCT418/010/2021"/>
 *     <enumeration value="SCT418/011/2017"/>
 *     <enumeration value="SCT418/011/2018"/>
 *     <enumeration value="SCT418/011/2019"/>
 *     <enumeration value="SCT418/011/2020"/>
 *     <enumeration value="SCT418/012/2017"/>
 *     <enumeration value="SCT418/012/2018"/>
 *     <enumeration value="SCT418/012/2019"/>
 *     <enumeration value="SCT418/012/2020"/>
 *     <enumeration value="SCT418/013/2017"/>
 *     <enumeration value="SCT418/013/2018"/>
 *     <enumeration value="SCT418/013/2019"/>
 *     <enumeration value="SCT418/013/2020"/>
 *     <enumeration value="SCT418/013/2021"/>
 *     <enumeration value="SCT418/014/2017"/>
 *     <enumeration value="SCT418/014/2018"/>
 *     <enumeration value="SCT418/014/2019"/>
 *     <enumeration value="SCT418/014/2020"/>
 *     <enumeration value="SCT418/015/2017"/>
 *     <enumeration value="SCT418/015/2018"/>
 *     <enumeration value="SCT418/015/2019"/>
 *     <enumeration value="SCT418/015/2020"/>
 *     <enumeration value="SCT418/016/2017"/>
 *     <enumeration value="SCT418/016/2018"/>
 *     <enumeration value="SCT418/016/2019"/>
 *     <enumeration value="SCT418/016/2020"/>
 *     <enumeration value="SCT418/017/2017"/>
 *     <enumeration value="SCT418/017/2018"/>
 *     <enumeration value="SCT418/017/2019"/>
 *     <enumeration value="SCT418/017/2020"/>
 *     <enumeration value="SCT418/018/2017"/>
 *     <enumeration value="SCT418/018/2018"/>
 *     <enumeration value="SCT418/018/2019"/>
 *     <enumeration value="SCT418/018/2020"/>
 *     <enumeration value="SCT418/019/2017"/>
 *     <enumeration value="SCT418/019/2018"/>
 *     <enumeration value="SCT418/019/2019"/>
 *     <enumeration value="SCT418/019/2020"/>
 *     <enumeration value="SCT418/020/2016"/>
 *     <enumeration value="SCT418/020/2018"/>
 *     <enumeration value="SCT418/020/2019"/>
 *     <enumeration value="SCT418/020/2020"/>
 *     <enumeration value="SCT418/020/2021"/>
 *     <enumeration value="SCT418/021/2016"/>
 *     <enumeration value="SCT418/021/2017"/>
 *     <enumeration value="SCT418/021/2018"/>
 *     <enumeration value="SCT418/021/2019"/>
 *     <enumeration value="SCT418/021/2020"/>
 *     <enumeration value="SCT418/021/2021"/>
 *     <enumeration value="SCT418/022/2017"/>
 *     <enumeration value="SCT418/022/2018"/>
 *     <enumeration value="SCT418/022/2019"/>
 *     <enumeration value="SCT418/022/2020"/>
 *     <enumeration value="SCT418/023/2017"/>
 *     <enumeration value="SCT418/023/2018"/>
 *     <enumeration value="SCT418/023/2019"/>
 *     <enumeration value="SCT418/023/2020"/>
 *     <enumeration value="SCT418/024/2017"/>
 *     <enumeration value="SCT418/024/2018"/>
 *     <enumeration value="SCT418/024/2019"/>
 *     <enumeration value="SCT418/024/2020"/>
 *     <enumeration value="SCT418/025/2016"/>
 *     <enumeration value="SCT418/025/2017"/>
 *     <enumeration value="SCT418/025/2018"/>
 *     <enumeration value="SCT418/025/2019"/>
 *     <enumeration value="SCT418/025/2020"/>
 *     <enumeration value="SCT418/026/2016"/>
 *     <enumeration value="SCT418/026/2017"/>
 *     <enumeration value="SCT418/026/2018"/>
 *     <enumeration value="SCT418/026/2019"/>
 *     <enumeration value="SCT418/026/2020"/>
 *     <enumeration value="SCT418/027/2017"/>
 *     <enumeration value="SCT418/027/2018"/>
 *     <enumeration value="SCT418/027/2019"/>
 *     <enumeration value="SCT418/027/2020"/>
 *     <enumeration value="SCT418/028/2016"/>
 *     <enumeration value="SCT418/028/2017"/>
 *     <enumeration value="SCT418/028/2018"/>
 *     <enumeration value="SCT418/028/2019"/>
 *     <enumeration value="SCT418/028/2020"/>
 *     <enumeration value="SCT418/029/2016"/>
 *     <enumeration value="SCT418/029/2017"/>
 *     <enumeration value="SCT418/029/2018"/>
 *     <enumeration value="SCT418/029/2019"/>
 *     <enumeration value="SCT418/029/2020"/>
 *     <enumeration value="SCT418/030/2016"/>
 *     <enumeration value="SCT418/030/2017"/>
 *     <enumeration value="SCT418/030/2018"/>
 *     <enumeration value="SCT418/030/2019"/>
 *     <enumeration value="SCT418/030/2020"/>
 *     <enumeration value="SCT418/031/2017"/>
 *     <enumeration value="SCT418/031/2018"/>
 *     <enumeration value="SCT418/031/2019"/>
 *     <enumeration value="SCT418/031/2020"/>
 *     <enumeration value="SCT418/032/2017"/>
 *     <enumeration value="SCT418/032/2018"/>
 *     <enumeration value="SCT418/032/2019"/>
 *     <enumeration value="SCT418/032/2020"/>
 *     <enumeration value="SCT418/033/2017"/>
 *     <enumeration value="SCT418/033/2018"/>
 *     <enumeration value="SCT418/033/2019"/>
 *     <enumeration value="SCT418/033/2020"/>
 *     <enumeration value="SCT418/034/2016"/>
 *     <enumeration value="SCT418/034/2017"/>
 *     <enumeration value="SCT418/034/2018"/>
 *     <enumeration value="SCT418/034/2019"/>
 *     <enumeration value="SCT418/034/2020"/>
 *     <enumeration value="SCT418/035/2017"/>
 *     <enumeration value="SCT418/035/2018"/>
 *     <enumeration value="SCT418/035/2019"/>
 *     <enumeration value="SCT418/035/2020"/>
 *     <enumeration value="SCT418/036/2016"/>
 *     <enumeration value="SCT418/036/2017"/>
 *     <enumeration value="SCT418/036/2018"/>
 *     <enumeration value="SCT418/036/2019"/>
 *     <enumeration value="SCT418/036/2020"/>
 *     <enumeration value="SCT418/037/2017"/>
 *     <enumeration value="SCT418/037/2018"/>
 *     <enumeration value="SCT418/037/2019"/>
 *     <enumeration value="SCT418/037/2020"/>
 *     <enumeration value="SCT418/038/2017"/>
 *     <enumeration value="SCT418/038/2018"/>
 *     <enumeration value="SCT418/038/2019"/>
 *     <enumeration value="SCT418/038/2020"/>
 *     <enumeration value="SCT418/039/2017"/>
 *     <enumeration value="SCT418/039/2018"/>
 *     <enumeration value="SCT418/039/2019"/>
 *     <enumeration value="SCT418/039/2020"/>
 *     <enumeration value="SCT418/040/2017"/>
 *     <enumeration value="SCT418/040/2018"/>
 *     <enumeration value="SCT418/040/2019"/>
 *     <enumeration value="SCT418/040/2020"/>
 *     <enumeration value="SCT418/041/2017"/>
 *     <enumeration value="SCT418/041/2018"/>
 *     <enumeration value="SCT418/041/2019"/>
 *     <enumeration value="SCT418/041/2020"/>
 *     <enumeration value="SCT418/042/2016"/>
 *     <enumeration value="SCT418/042/2017"/>
 *     <enumeration value="SCT418/042/2018"/>
 *     <enumeration value="SCT418/042/2019"/>
 *     <enumeration value="SCT418/042/2020"/>
 *     <enumeration value="SCT418/043/2017"/>
 *     <enumeration value="SCT418/043/2018"/>
 *     <enumeration value="SCT418/043/2019"/>
 *     <enumeration value="SCT418/044/2017"/>
 *     <enumeration value="SCT418/044/2018"/>
 *     <enumeration value="SCT418/044/2019"/>
 *     <enumeration value="SCT418/045/2017"/>
 *     <enumeration value="SCT418/045/2018"/>
 *     <enumeration value="SCT418/045/2019"/>
 *     <enumeration value="SCT418/046/2016"/>
 *     <enumeration value="SCT418/046/2017"/>
 *     <enumeration value="SCT418/046/2018"/>
 *     <enumeration value="SCT418/046/2019"/>
 *     <enumeration value="SCT418/047/2016"/>
 *     <enumeration value="SCT418/047/2017"/>
 *     <enumeration value="SCT418/047/2018"/>
 *     <enumeration value="SCT418/047/2019"/>
 *     <enumeration value="SCT418/048/2016"/>
 *     <enumeration value="SCT418/048/2017"/>
 *     <enumeration value="SCT418/048/2018"/>
 *     <enumeration value="SCT418/048/2019"/>
 *     <enumeration value="SCT418/049/2017"/>
 *     <enumeration value="SCT418/049/2018"/>
 *     <enumeration value="SCT418/049/2019"/>
 *     <enumeration value="SCT418/050/2017"/>
 *     <enumeration value="SCT418/050/2018"/>
 *     <enumeration value="SCT418/050/2019"/>
 *     <enumeration value="SCT418/051/2016"/>
 *     <enumeration value="SCT418/051/2017"/>
 *     <enumeration value="SCT418/051/2018"/>
 *     <enumeration value="SCT418/051/2019"/>
 *     <enumeration value="SCT418/052/2016"/>
 *     <enumeration value="SCT418/052/2017"/>
 *     <enumeration value="SCT418/052/2018"/>
 *     <enumeration value="SCT418/052/2019"/>
 *     <enumeration value="SCT418/053/2017"/>
 *     <enumeration value="SCT418/053/2018"/>
 *     <enumeration value="SCT418/053/2019"/>
 *     <enumeration value="SCT418/054/2017"/>
 *     <enumeration value="SCT418/054/2018"/>
 *     <enumeration value="SCT418/054/2019"/>
 *     <enumeration value="SCT418/055/2017"/>
 *     <enumeration value="SCT418/055/2018"/>
 *     <enumeration value="SCT418/056/2017"/>
 *     <enumeration value="SCT418/056/2018"/>
 *     <enumeration value="SCT418/057/2017"/>
 *     <enumeration value="SCT418/057/2018"/>
 *     <enumeration value="SCT418/058/2017"/>
 *     <enumeration value="SCT418/058/2018"/>
 *     <enumeration value="SCT418/059/2018"/>
 *     <enumeration value="SCT418/060/2017"/>
 *     <enumeration value="SCT418/060/2018"/>
 *     <enumeration value="SCT418/061/2017"/>
 *     <enumeration value="SCT418/061/2018"/>
 *     <enumeration value="SCT418/062/2018"/>
 *     <enumeration value="SCT418/063/2017"/>
 *     <enumeration value="SCT418/063/2018"/>
 *     <enumeration value="SCT418/064/2017"/>
 *     <enumeration value="SCT418/064/2018"/>
 *     <enumeration value="SCT418/065/2017"/>
 *     <enumeration value="SCT418/065/2018"/>
 *     <enumeration value="SCT418/066/2017"/>
 *     <enumeration value="SCT418/066/2018"/>
 *     <enumeration value="SCT418/067/2017"/>
 *     <enumeration value="SCT418/067/2018"/>
 *     <enumeration value="SCT418/068/2017"/>
 *     <enumeration value="SCT418/068/2018"/>
 *     <enumeration value="SCT418/069/2017"/>
 *     <enumeration value="SCT418/069/2018"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "c_NumAutorizacionNaviero", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte")
@XmlEnum
public enum CNumAutorizacionNaviero {

    @XmlEnumValue("ANC001/2022")
    ANC_001_2022("ANC001/2022"),
    @XmlEnumValue("ANC001/2023")
    ANC_001_2023("ANC001/2023"),
    @XmlEnumValue("ANC002/2022")
    ANC_002_2022("ANC002/2022"),
    @XmlEnumValue("ANC002/2024")
    ANC_002_2024("ANC002/2024"),
    @XmlEnumValue("ANC003/2023")
    ANC_003_2023("ANC003/2023"),
    @XmlEnumValue("ANC003/2024")
    ANC_003_2024("ANC003/2024"),
    @XmlEnumValue("ANC004/2023")
    ANC_004_2023("ANC004/2023"),
    @XmlEnumValue("ANC005/2022")
    ANC_005_2022("ANC005/2022"),
    @XmlEnumValue("ANC005/2023")
    ANC_005_2023("ANC005/2023"),
    @XmlEnumValue("ANC005/2024")
    ANC_005_2024("ANC005/2024"),
    @XmlEnumValue("ANC006/2024")
    ANC_006_2024("ANC006/2024"),
    @XmlEnumValue("ANC007/2024")
    ANC_007_2024("ANC007/2024"),
    @XmlEnumValue("ANC009/2024")
    ANC_009_2024("ANC009/2024"),
    @XmlEnumValue("ANC011/2022")
    ANC_011_2022("ANC011/2022"),
    @XmlEnumValue("ANC012/2022")
    ANC_012_2022("ANC012/2022"),
    @XmlEnumValue("ANC013/2023")
    ANC_013_2023("ANC013/2023"),
    @XmlEnumValue("ANC016/2023")
    ANC_016_2023("ANC016/2023"),
    @XmlEnumValue("ANC019/2022")
    ANC_019_2022("ANC019/2022"),
    @XmlEnumValue("ANC021/2022")
    ANC_021_2022("ANC021/2022"),
    @XmlEnumValue("ANC022/2022")
    ANC_022_2022("ANC022/2022"),
    @XmlEnumValue("ANC023/2022")
    ANC_023_2022("ANC023/2022"),
    @XmlEnumValue("ANC025/2023")
    ANC_025_2023("ANC025/2023"),
    @XmlEnumValue("ANC025/2025")
    ANC_025_2025("ANC025/2025"),
    @XmlEnumValue("ANC027/2022")
    ANC_027_2022("ANC027/2022"),
    @XmlEnumValue("ANC027/2023")
    ANC_027_2023("ANC027/2023"),
    @XmlEnumValue("ANC027/2025")
    ANC_027_2025("ANC027/2025"),
    @XmlEnumValue("ANC028/2022")
    ANC_028_2022("ANC028/2022"),
    @XmlEnumValue("ANC028/2023")
    ANC_028_2023("ANC028/2023"),
    @XmlEnumValue("ANC029/2022")
    ANC_029_2022("ANC029/2022"),
    @XmlEnumValue("ANC029/2023")
    ANC_029_2023("ANC029/2023"),
    @XmlEnumValue("ANC029/2025")
    ANC_029_2025("ANC029/2025"),
    @XmlEnumValue("ANC032/2022")
    ANC_032_2022("ANC032/2022"),
    @XmlEnumValue("ANC032/2023")
    ANC_032_2023("ANC032/2023"),
    @XmlEnumValue("ANC032/2025")
    ANC_032_2025("ANC032/2025"),
    @XmlEnumValue("ANC033/2023")
    ANC_033_2023("ANC033/2023"),
    @XmlEnumValue("ANC033/2024")
    ANC_033_2024("ANC033/2024"),
    @XmlEnumValue("ANC033/2025")
    ANC_033_2025("ANC033/2025"),
    @XmlEnumValue("ANC034/2023")
    ANC_034_2023("ANC034/2023"),
    @XmlEnumValue("ANC034/2024")
    ANC_034_2024("ANC034/2024"),
    @XmlEnumValue("ANC034/2025")
    ANC_034_2025("ANC034/2025"),
    @XmlEnumValue("ANC035/2022")
    ANC_035_2022("ANC035/2022"),
    @XmlEnumValue("ANC035/2023")
    ANC_035_2023("ANC035/2023"),
    @XmlEnumValue("ANC035/2024")
    ANC_035_2024("ANC035/2024"),
    @XmlEnumValue("ANC035/2025")
    ANC_035_2025("ANC035/2025"),
    @XmlEnumValue("ANC036/2023")
    ANC_036_2023("ANC036/2023"),
    @XmlEnumValue("ANC037/2023")
    ANC_037_2023("ANC037/2023"),
    @XmlEnumValue("ANC037/2025")
    ANC_037_2025("ANC037/2025"),
    @XmlEnumValue("ANC038/2022")
    ANC_038_2022("ANC038/2022"),
    @XmlEnumValue("ANC038/2023")
    ANC_038_2023("ANC038/2023"),
    @XmlEnumValue("ANC040/2025")
    ANC_040_2025("ANC040/2025"),
    @XmlEnumValue("ANC041/2022")
    ANC_041_2022("ANC041/2022"),
    @XmlEnumValue("ANC041/2023")
    ANC_041_2023("ANC041/2023"),
    @XmlEnumValue("ANC041/2025")
    ANC_041_2025("ANC041/2025"),
    @XmlEnumValue("ANC042/2023")
    ANC_042_2023("ANC042/2023"),
    @XmlEnumValue("ANC043/2022")
    ANC_043_2022("ANC043/2022"),
    @XmlEnumValue("ANC044/2025")
    ANC_044_2025("ANC044/2025"),
    @XmlEnumValue("ANC045/2025")
    ANC_045_2025("ANC045/2025"),
    @XmlEnumValue("ANC046/2025")
    ANC_046_2025("ANC046/2025"),
    @XmlEnumValue("ANC049/2022")
    ANC_049_2022("ANC049/2022"),
    @XmlEnumValue("ANC051/2022")
    ANC_051_2022("ANC051/2022"),
    @XmlEnumValue("ANC052/2022")
    ANC_052_2022("ANC052/2022"),
    @XmlEnumValue("ANC052/2023")
    ANC_052_2023("ANC052/2023"),
    @XmlEnumValue("ANC056/2023")
    ANC_056_2023("ANC056/2023"),
    @XmlEnumValue("ANC057/2023")
    ANC_057_2023("ANC057/2023"),
    @XmlEnumValue("ANC060/2022")
    ANC_060_2022("ANC060/2022"),
    @XmlEnumValue("ANC060/2023")
    ANC_060_2023("ANC060/2023"),
    @XmlEnumValue("ANC061/2023")
    ANC_061_2023("ANC061/2023"),
    @XmlEnumValue("ANC062/2022")
    ANC_062_2022("ANC062/2022"),
    @XmlEnumValue("ANC062/2023")
    ANC_062_2023("ANC062/2023"),
    @XmlEnumValue("ANC063/2023")
    ANC_063_2023("ANC063/2023"),
    @XmlEnumValue("ANC071/2023")
    ANC_071_2023("ANC071/2023"),
    @XmlEnumValue("ANC072/2023")
    ANC_072_2023("ANC072/2023"),
    @XmlEnumValue("ANC073/2023")
    ANC_073_2023("ANC073/2023"),
    @XmlEnumValue("ANC074/2023")
    ANC_074_2023("ANC074/2023"),
    @XmlEnumValue("ANC41/2021")
    ANC_41_2021("ANC41/2021"),
    @XmlEnumValue("ANC47/2021")
    ANC_47_2021("ANC47/2021"),
    @XmlEnumValue("ANC49/2021")
    ANC_49_2021("ANC49/2021"),
    @XmlEnumValue("ANC54/2021")
    ANC_54_2021("ANC54/2021"),
    @XmlEnumValue("ANC58/2021")
    ANC_58_2021("ANC58/2021"),
    @XmlEnumValue("ANG001/2024")
    ANG_001_2024("ANG001/2024"),
    @XmlEnumValue("ANG001/2025")
    ANG_001_2025("ANG001/2025"),
    @XmlEnumValue("ANG002/2023")
    ANG_002_2023("ANG002/2023"),
    @XmlEnumValue("ANG003/2022")
    ANG_003_2022("ANG003/2022"),
    @XmlEnumValue("ANG004/2022")
    ANG_004_2022("ANG004/2022"),
    @XmlEnumValue("ANG004/2024")
    ANG_004_2024("ANG004/2024"),
    @XmlEnumValue("ANG005/2022")
    ANG_005_2022("ANG005/2022"),
    @XmlEnumValue("ANG005/2023")
    ANG_005_2023("ANG005/2023"),
    @XmlEnumValue("ANG005/2025")
    ANG_005_2025("ANG005/2025"),
    @XmlEnumValue("ANG006/2022")
    ANG_006_2022("ANG006/2022"),
    @XmlEnumValue("ANG006/2023")
    ANG_006_2023("ANG006/2023"),
    @XmlEnumValue("ANG006/2024")
    ANG_006_2024("ANG006/2024"),
    @XmlEnumValue("ANG006/2025")
    ANG_006_2025("ANG006/2025"),
    @XmlEnumValue("ANG007/2022")
    ANG_007_2022("ANG007/2022"),
    @XmlEnumValue("ANG007/2023")
    ANG_007_2023("ANG007/2023"),
    @XmlEnumValue("ANG007/2024")
    ANG_007_2024("ANG007/2024"),
    @XmlEnumValue("ANG007/2025")
    ANG_007_2025("ANG007/2025"),
    @XmlEnumValue("ANG008/2022")
    ANG_008_2022("ANG008/2022"),
    @XmlEnumValue("ANG008/2023")
    ANG_008_2023("ANG008/2023"),
    @XmlEnumValue("ANG008/2024")
    ANG_008_2024("ANG008/2024"),
    @XmlEnumValue("ANG008/2025")
    ANG_008_2025("ANG008/2025"),
    @XmlEnumValue("ANG009/2022")
    ANG_009_2022("ANG009/2022"),
    @XmlEnumValue("ANG009/2023")
    ANG_009_2023("ANG009/2023"),
    @XmlEnumValue("ANG009/2025")
    ANG_009_2025("ANG009/2025"),
    @XmlEnumValue("ANG010/2022")
    ANG_010_2022("ANG010/2022"),
    @XmlEnumValue("ANG010/2023")
    ANG_010_2023("ANG010/2023"),
    @XmlEnumValue("ANG010/2024")
    ANG_010_2024("ANG010/2024"),
    @XmlEnumValue("ANG010/2025")
    ANG_010_2025("ANG010/2025"),
    @XmlEnumValue("ANG011/2023")
    ANG_011_2023("ANG011/2023"),
    @XmlEnumValue("ANG011/2024")
    ANG_011_2024("ANG011/2024"),
    @XmlEnumValue("ANG012/2022")
    ANG_012_2022("ANG012/2022"),
    @XmlEnumValue("ANG012/2023")
    ANG_012_2023("ANG012/2023"),
    @XmlEnumValue("ANG012/2024")
    ANG_012_2024("ANG012/2024"),
    @XmlEnumValue("ANG013/2022")
    ANG_013_2022("ANG013/2022"),
    @XmlEnumValue("ANG013/2024")
    ANG_013_2024("ANG013/2024"),
    @XmlEnumValue("ANG014/2022")
    ANG_014_2022("ANG014/2022"),
    @XmlEnumValue("ANG014/2023")
    ANG_014_2023("ANG014/2023"),
    @XmlEnumValue("ANG014/2024")
    ANG_014_2024("ANG014/2024"),
    @XmlEnumValue("ANG015/2022")
    ANG_015_2022("ANG015/2022"),
    @XmlEnumValue("ANG015/2023")
    ANG_015_2023("ANG015/2023"),
    @XmlEnumValue("ANG015/2024")
    ANG_015_2024("ANG015/2024"),
    @XmlEnumValue("ANG016/2022")
    ANG_016_2022("ANG016/2022"),
    @XmlEnumValue("ANG016/2023")
    ANG_016_2023("ANG016/2023"),
    @XmlEnumValue("ANG016/2024")
    ANG_016_2024("ANG016/2024"),
    @XmlEnumValue("ANG016/2025")
    ANG_016_2025("ANG016/2025"),
    @XmlEnumValue("ANG017/2022")
    ANG_017_2022("ANG017/2022"),
    @XmlEnumValue("ANG017/2023")
    ANG_017_2023("ANG017/2023"),
    @XmlEnumValue("ANG017/2024")
    ANG_017_2024("ANG017/2024"),
    @XmlEnumValue("ANG017/2025")
    ANG_017_2025("ANG017/2025"),
    @XmlEnumValue("ANG018/2022")
    ANG_018_2022("ANG018/2022"),
    @XmlEnumValue("ANG018/2023")
    ANG_018_2023("ANG018/2023"),
    @XmlEnumValue("ANG018/2024")
    ANG_018_2024("ANG018/2024"),
    @XmlEnumValue("ANG018/2025")
    ANG_018_2025("ANG018/2025"),
    @XmlEnumValue("ANG019/2023")
    ANG_019_2023("ANG019/2023"),
    @XmlEnumValue("ANG019/2024")
    ANG_019_2024("ANG019/2024"),
    @XmlEnumValue("ANG019/2025")
    ANG_019_2025("ANG019/2025"),
    @XmlEnumValue("ANG020/2022")
    ANG_020_2022("ANG020/2022"),
    @XmlEnumValue("ANG020/2023")
    ANG_020_2023("ANG020/2023"),
    @XmlEnumValue("ANG020/2024")
    ANG_020_2024("ANG020/2024"),
    @XmlEnumValue("ANG020/2025")
    ANG_020_2025("ANG020/2025"),
    @XmlEnumValue("ANG021/2023")
    ANG_021_2023("ANG021/2023"),
    @XmlEnumValue("ANG021/2024")
    ANG_021_2024("ANG021/2024"),
    @XmlEnumValue("ANG021/2025")
    ANG_021_2025("ANG021/2025"),
    @XmlEnumValue("ANG022/2023")
    ANG_022_2023("ANG022/2023"),
    @XmlEnumValue("ANG022/2024")
    ANG_022_2024("ANG022/2024"),
    @XmlEnumValue("ANG022/2025")
    ANG_022_2025("ANG022/2025"),
    @XmlEnumValue("ANG023/2022")
    ANG_023_2022("ANG023/2022"),
    @XmlEnumValue("ANG023/2023")
    ANG_023_2023("ANG023/2023"),
    @XmlEnumValue("ANG023/2024")
    ANG_023_2024("ANG023/2024"),
    @XmlEnumValue("ANG023/2025")
    ANG_023_2025("ANG023/2025"),
    @XmlEnumValue("ANG024/2022")
    ANG_024_2022("ANG024/2022"),
    @XmlEnumValue("ANG024/2023")
    ANG_024_2023("ANG024/2023"),
    @XmlEnumValue("ANG024/2024")
    ANG_024_2024("ANG024/2024"),
    @XmlEnumValue("ANG024/2025")
    ANG_024_2025("ANG024/2025"),
    @XmlEnumValue("ANG025/2022")
    ANG_025_2022("ANG025/2022"),
    @XmlEnumValue("ANG026/2022")
    ANG_026_2022("ANG026/2022"),
    @XmlEnumValue("ANG026/2023")
    ANG_026_2023("ANG026/2023"),
    @XmlEnumValue("ANG026/2024")
    ANG_026_2024("ANG026/2024"),
    @XmlEnumValue("ANG026/2025")
    ANG_026_2025("ANG026/2025"),
    @XmlEnumValue("ANG027/2024")
    ANG_027_2024("ANG027/2024"),
    @XmlEnumValue("ANG028/2024")
    ANG_028_2024("ANG028/2024"),
    @XmlEnumValue("ANG028/2025")
    ANG_028_2025("ANG028/2025"),
    @XmlEnumValue("ANG029/2024")
    ANG_029_2024("ANG029/2024"),
    @XmlEnumValue("ANG030/2022")
    ANG_030_2022("ANG030/2022"),
    @XmlEnumValue("ANG030/2023")
    ANG_030_2023("ANG030/2023"),
    @XmlEnumValue("ANG030/2024")
    ANG_030_2024("ANG030/2024"),
    @XmlEnumValue("ANG030/2025")
    ANG_030_2025("ANG030/2025"),
    @XmlEnumValue("ANG031/2022")
    ANG_031_2022("ANG031/2022"),
    @XmlEnumValue("ANG031/2023")
    ANG_031_2023("ANG031/2023"),
    @XmlEnumValue("ANG031/2024")
    ANG_031_2024("ANG031/2024"),
    @XmlEnumValue("ANG031/2025")
    ANG_031_2025("ANG031/2025"),
    @XmlEnumValue("ANG032/2024")
    ANG_032_2024("ANG032/2024"),
    @XmlEnumValue("ANG033/2022")
    ANG_033_2022("ANG033/2022"),
    @XmlEnumValue("ANG034/2022")
    ANG_034_2022("ANG034/2022"),
    @XmlEnumValue("ANG034/2023")
    ANG_034_2023("ANG034/2023"),
    @XmlEnumValue("ANG035/2023")
    ANG_035_2023("ANG035/2023"),
    @XmlEnumValue("ANG036/2022")
    ANG_036_2022("ANG036/2022"),
    @XmlEnumValue("ANG036/2025")
    ANG_036_2025("ANG036/2025"),
    @XmlEnumValue("ANG037/2022")
    ANG_037_2022("ANG037/2022"),
    @XmlEnumValue("ANG038/2025")
    ANG_038_2025("ANG038/2025"),
    @XmlEnumValue("ANG039/2022")
    ANG_039_2022("ANG039/2022"),
    @XmlEnumValue("ANG039/2023")
    ANG_039_2023("ANG039/2023"),
    @XmlEnumValue("ANG040/2022")
    ANG_040_2022("ANG040/2022"),
    @XmlEnumValue("ANG040/2023")
    ANG_040_2023("ANG040/2023"),
    @XmlEnumValue("ANG041/2022")
    ANG_041_2022("ANG041/2022"),
    @XmlEnumValue("ANG042/2022")
    ANG_042_2022("ANG042/2022"),
    @XmlEnumValue("ANG042/2025")
    ANG_042_2025("ANG042/2025"),
    @XmlEnumValue("ANG043/2022")
    ANG_043_2022("ANG043/2022"),
    @XmlEnumValue("ANG043/2023")
    ANG_043_2023("ANG043/2023"),
    @XmlEnumValue("ANG044/2023")
    ANG_044_2023("ANG044/2023"),
    @XmlEnumValue("ANG045/2022")
    ANG_045_2022("ANG045/2022"),
    @XmlEnumValue("ANG045/2023")
    ANG_045_2023("ANG045/2023"),
    @XmlEnumValue("ANG046/2022")
    ANG_046_2022("ANG046/2022"),
    @XmlEnumValue("ANG046/2023")
    ANG_046_2023("ANG046/2023"),
    @XmlEnumValue("ANG047/2022")
    ANG_047_2022("ANG047/2022"),
    @XmlEnumValue("ANG047/2023")
    ANG_047_2023("ANG047/2023"),
    @XmlEnumValue("ANG048/2022")
    ANG_048_2022("ANG048/2022"),
    @XmlEnumValue("ANG048/2023")
    ANG_048_2023("ANG048/2023"),
    @XmlEnumValue("ANG049/2023")
    ANG_049_2023("ANG049/2023"),
    @XmlEnumValue("ANG050/2022")
    ANG_050_2022("ANG050/2022"),
    @XmlEnumValue("ANG050/2023")
    ANG_050_2023("ANG050/2023"),
    @XmlEnumValue("ANG051/2023")
    ANG_051_2023("ANG051/2023"),
    @XmlEnumValue("ANG052/2022")
    ANG_052_2022("ANG052/2022"),
    @XmlEnumValue("ANG053/2022")
    ANG_053_2022("ANG053/2022"),
    @XmlEnumValue("ANG053/2023")
    ANG_053_2023("ANG053/2023"),
    @XmlEnumValue("ANG054/2022")
    ANG_054_2022("ANG054/2022"),
    @XmlEnumValue("ANG054/2023")
    ANG_054_2023("ANG054/2023"),
    @XmlEnumValue("ANG055/2022")
    ANG_055_2022("ANG055/2022"),
    @XmlEnumValue("ANG055/2023")
    ANG_055_2023("ANG055/2023"),
    @XmlEnumValue("ANG056/2022")
    ANG_056_2022("ANG056/2022"),
    @XmlEnumValue("ANG057/2022")
    ANG_057_2022("ANG057/2022"),
    @XmlEnumValue("ANG058/2022")
    ANG_058_2022("ANG058/2022"),
    @XmlEnumValue("ANG058/2023")
    ANG_058_2023("ANG058/2023"),
    @XmlEnumValue("ANG059/2022")
    ANG_059_2022("ANG059/2022"),
    @XmlEnumValue("ANG059/2023")
    ANG_059_2023("ANG059/2023"),
    @XmlEnumValue("ANG061/2022")
    ANG_061_2022("ANG061/2022"),
    @XmlEnumValue("ANG063/2022")
    ANG_063_2022("ANG063/2022"),
    @XmlEnumValue("ANG064/2023")
    ANG_064_2023("ANG064/2023"),
    @XmlEnumValue("ANG065/2023")
    ANG_065_2023("ANG065/2023"),
    @XmlEnumValue("ANG066/2023")
    ANG_066_2023("ANG066/2023"),
    @XmlEnumValue("ANG067/2023")
    ANG_067_2023("ANG067/2023"),
    @XmlEnumValue("ANG068/2023")
    ANG_068_2023("ANG068/2023"),
    @XmlEnumValue("ANG069/2023")
    ANG_069_2023("ANG069/2023"),
    @XmlEnumValue("ANG070/2023")
    ANG_070_2023("ANG070/2023"),
    @XmlEnumValue("ANG075/2023")
    ANG_075_2023("ANG075/2023"),
    @XmlEnumValue("ANG076/2023")
    ANG_076_2023("ANG076/2023"),
    @XmlEnumValue("ANG39-2021")
    ANG_39_2021("ANG39-2021"),
    @XmlEnumValue("ANG40-2021")
    ANG_40_2021("ANG40-2021"),
    @XmlEnumValue("ANG42/2021")
    ANG_42_2021("ANG42/2021"),
    @XmlEnumValue("ANG43/2021")
    ANG_43_2021("ANG43/2021"),
    @XmlEnumValue("ANG44-2021")
    ANG_44_2021("ANG44-2021"),
    @XmlEnumValue("ANG45/2021")
    ANG_45_2021("ANG45/2021"),
    @XmlEnumValue("ANG46/2021")
    ANG_46_2021("ANG46/2021"),
    @XmlEnumValue("ANG47/2021")
    ANG_47_2021("ANG47/2021"),
    @XmlEnumValue("ANG48/2021")
    ANG_48_2021("ANG48/2021"),
    @XmlEnumValue("ANG49/2021")
    ANG_49_2021("ANG49/2021"),
    @XmlEnumValue("ANG50/2021")
    ANG_50_2021("ANG50/2021"),
    @XmlEnumValue("ANG51/2021")
    ANG_51_2021("ANG51/2021"),
    @XmlEnumValue("ANG52/2021")
    ANG_52_2021("ANG52/2021"),
    @XmlEnumValue("ANG53/2021")
    ANG_53_2021("ANG53/2021"),
    @XmlEnumValue("ANG55/2021")
    ANG_55_2021("ANG55/2021"),
    @XmlEnumValue("ANG56/2021")
    ANG_56_2021("ANG56/2021"),
    @XmlEnumValue("ANG57/2021")
    ANG_57_2021("ANG57/2021"),
    @XmlEnumValue("ANG59/2021")
    ANG_59_2021("ANG59/2021"),
    @XmlEnumValue("NAVMX-2024")
    NAVMX_2024("NAVMX-2024"),
    @XmlEnumValue("SCT418-011-2021")
    SCT_418_011_2021("SCT418-011-2021"),
    @XmlEnumValue("SCT418-012-2021")
    SCT_418_012_2021("SCT418-012-2021"),
    @XmlEnumValue("SCT418-014-2021")
    SCT_418_014_2021("SCT418-014-2021"),
    @XmlEnumValue("SCT418-015-2021")
    SCT_418_015_2021("SCT418-015-2021"),
    @XmlEnumValue("SCT418-016-2021")
    SCT_418_016_2021("SCT418-016-2021"),
    @XmlEnumValue("SCT418-017-2021")
    SCT_418_017_2021("SCT418-017-2021"),
    @XmlEnumValue("SCT418-018-2021")
    SCT_418_018_2021("SCT418-018-2021"),
    @XmlEnumValue("SCT418-019-2021")
    SCT_418_019_2021("SCT418-019-2021"),
    @XmlEnumValue("SCT418-022-2021")
    SCT_418_022_2021("SCT418-022-2021"),
    @XmlEnumValue("SCT418-023-2021")
    SCT_418_023_2021("SCT418-023-2021"),
    @XmlEnumValue("SCT418-024-2021")
    SCT_418_024_2021("SCT418-024-2021"),
    @XmlEnumValue("SCT418-025-2021")
    SCT_418_025_2021("SCT418-025-2021"),
    @XmlEnumValue("SCT418-026-2021")
    SCT_418_026_2021("SCT418-026-2021"),
    @XmlEnumValue("SCT418-027-2021")
    SCT_418_027_2021("SCT418-027-2021"),
    @XmlEnumValue("SCT418-028-2021")
    SCT_418_028_2021("SCT418-028-2021"),
    @XmlEnumValue("SCT418-029-2021")
    SCT_418_029_2021("SCT418-029-2021"),
    @XmlEnumValue("SCT418-030-2021")
    SCT_418_030_2021("SCT418-030-2021"),
    @XmlEnumValue("SCT418-031-2021")
    SCT_418_031_2021("SCT418-031-2021"),
    @XmlEnumValue("SCT418-032-2021")
    SCT_418_032_2021("SCT418-032-2021"),
    @XmlEnumValue("SCT418-033-2021")
    SCT_418_033_2021("SCT418-033-2021"),
    @XmlEnumValue("SCT418-034-2021")
    SCT_418_034_2021("SCT418-034-2021"),
    @XmlEnumValue("SCT418-035-2021")
    SCT_418_035_2021("SCT418-035-2021"),
    @XmlEnumValue("SCT418-036-2021")
    SCT_418_036_2021("SCT418-036-2021"),
    @XmlEnumValue("SCT418-037-2021")
    SCT_418_037_2021("SCT418-037-2021"),
    @XmlEnumValue("SCT418-038-2021")
    SCT_418_038_2021("SCT418-038-2021"),
    @XmlEnumValue("SCT418/001/2017")
    SCT_418_001_2017("SCT418/001/2017"),
    @XmlEnumValue("SCT418/001/2018")
    SCT_418_001_2018("SCT418/001/2018"),
    @XmlEnumValue("SCT418/001/2019")
    SCT_418_001_2019("SCT418/001/2019"),
    @XmlEnumValue("SCT418/001/2020")
    SCT_418_001_2020("SCT418/001/2020"),
    @XmlEnumValue("SCT418/001/2021")
    SCT_418_001_2021("SCT418/001/2021"),
    @XmlEnumValue("SCT418/002/2017")
    SCT_418_002_2017("SCT418/002/2017"),
    @XmlEnumValue("SCT418/002/2018")
    SCT_418_002_2018("SCT418/002/2018"),
    @XmlEnumValue("SCT418/002/2019")
    SCT_418_002_2019("SCT418/002/2019"),
    @XmlEnumValue("SCT418/002/2020")
    SCT_418_002_2020("SCT418/002/2020"),
    @XmlEnumValue("SCT418/002/2021")
    SCT_418_002_2021("SCT418/002/2021"),
    @XmlEnumValue("SCT418/003/2017")
    SCT_418_003_2017("SCT418/003/2017"),
    @XmlEnumValue("SCT418/003/2018")
    SCT_418_003_2018("SCT418/003/2018"),
    @XmlEnumValue("SCT418/003/2019")
    SCT_418_003_2019("SCT418/003/2019"),
    @XmlEnumValue("SCT418/003/2020")
    SCT_418_003_2020("SCT418/003/2020"),
    @XmlEnumValue("SCT418/003/2021")
    SCT_418_003_2021("SCT418/003/2021"),
    @XmlEnumValue("SCT418/004/2017")
    SCT_418_004_2017("SCT418/004/2017"),
    @XmlEnumValue("SCT418/004/2018")
    SCT_418_004_2018("SCT418/004/2018"),
    @XmlEnumValue("SCT418/004/2019")
    SCT_418_004_2019("SCT418/004/2019"),
    @XmlEnumValue("SCT418/004/2020")
    SCT_418_004_2020("SCT418/004/2020"),
    @XmlEnumValue("SCT418/004/2021")
    SCT_418_004_2021("SCT418/004/2021"),
    @XmlEnumValue("SCT418/005/2017")
    SCT_418_005_2017("SCT418/005/2017"),
    @XmlEnumValue("SCT418/005/2018")
    SCT_418_005_2018("SCT418/005/2018"),
    @XmlEnumValue("SCT418/005/2019")
    SCT_418_005_2019("SCT418/005/2019"),
    @XmlEnumValue("SCT418/005/2020")
    SCT_418_005_2020("SCT418/005/2020"),
    @XmlEnumValue("SCT418/005/2021")
    SCT_418_005_2021("SCT418/005/2021"),
    @XmlEnumValue("SCT418/006/2017")
    SCT_418_006_2017("SCT418/006/2017"),
    @XmlEnumValue("SCT418/006/2018")
    SCT_418_006_2018("SCT418/006/2018"),
    @XmlEnumValue("SCT418/006/2019")
    SCT_418_006_2019("SCT418/006/2019"),
    @XmlEnumValue("SCT418/006/2020")
    SCT_418_006_2020("SCT418/006/2020"),
    @XmlEnumValue("SCT418/006/2021")
    SCT_418_006_2021("SCT418/006/2021"),
    @XmlEnumValue("SCT418/007/2017")
    SCT_418_007_2017("SCT418/007/2017"),
    @XmlEnumValue("SCT418/007/2018")
    SCT_418_007_2018("SCT418/007/2018"),
    @XmlEnumValue("SCT418/007/2019")
    SCT_418_007_2019("SCT418/007/2019"),
    @XmlEnumValue("SCT418/007/2020")
    SCT_418_007_2020("SCT418/007/2020"),
    @XmlEnumValue("SCT418/007/2021")
    SCT_418_007_2021("SCT418/007/2021"),
    @XmlEnumValue("SCT418/008/2017")
    SCT_418_008_2017("SCT418/008/2017"),
    @XmlEnumValue("SCT418/008/2018")
    SCT_418_008_2018("SCT418/008/2018"),
    @XmlEnumValue("SCT418/008/2019")
    SCT_418_008_2019("SCT418/008/2019"),
    @XmlEnumValue("SCT418/008/2020")
    SCT_418_008_2020("SCT418/008/2020"),
    @XmlEnumValue("SCT418/008/2021")
    SCT_418_008_2021("SCT418/008/2021"),
    @XmlEnumValue("SCT418/009/2017")
    SCT_418_009_2017("SCT418/009/2017"),
    @XmlEnumValue("SCT418/009/2018")
    SCT_418_009_2018("SCT418/009/2018"),
    @XmlEnumValue("SCT418/009/2019")
    SCT_418_009_2019("SCT418/009/2019"),
    @XmlEnumValue("SCT418/009/2020")
    SCT_418_009_2020("SCT418/009/2020"),
    @XmlEnumValue("SCT418/009/2021")
    SCT_418_009_2021("SCT418/009/2021"),
    @XmlEnumValue("SCT418/010/2017")
    SCT_418_010_2017("SCT418/010/2017"),
    @XmlEnumValue("SCT418/010/2018")
    SCT_418_010_2018("SCT418/010/2018"),
    @XmlEnumValue("SCT418/010/2019")
    SCT_418_010_2019("SCT418/010/2019"),
    @XmlEnumValue("SCT418/010/2020")
    SCT_418_010_2020("SCT418/010/2020"),
    @XmlEnumValue("SCT418/010/2021")
    SCT_418_010_2021("SCT418/010/2021"),
    @XmlEnumValue("SCT418/011/2017")
    SCT_418_011_2017("SCT418/011/2017"),
    @XmlEnumValue("SCT418/011/2018")
    SCT_418_011_2018("SCT418/011/2018"),
    @XmlEnumValue("SCT418/011/2019")
    SCT_418_011_2019("SCT418/011/2019"),
    @XmlEnumValue("SCT418/011/2020")
    SCT_418_011_2020("SCT418/011/2020"),
    @XmlEnumValue("SCT418/012/2017")
    SCT_418_012_2017("SCT418/012/2017"),
    @XmlEnumValue("SCT418/012/2018")
    SCT_418_012_2018("SCT418/012/2018"),
    @XmlEnumValue("SCT418/012/2019")
    SCT_418_012_2019("SCT418/012/2019"),
    @XmlEnumValue("SCT418/012/2020")
    SCT_418_012_2020("SCT418/012/2020"),
    @XmlEnumValue("SCT418/013/2017")
    SCT_418_013_2017("SCT418/013/2017"),
    @XmlEnumValue("SCT418/013/2018")
    SCT_418_013_2018("SCT418/013/2018"),
    @XmlEnumValue("SCT418/013/2019")
    SCT_418_013_2019("SCT418/013/2019"),
    @XmlEnumValue("SCT418/013/2020")
    SCT_418_013_2020("SCT418/013/2020"),
    @XmlEnumValue("SCT418/013/2021")
    SCT_418_013_2021("SCT418/013/2021"),
    @XmlEnumValue("SCT418/014/2017")
    SCT_418_014_2017("SCT418/014/2017"),
    @XmlEnumValue("SCT418/014/2018")
    SCT_418_014_2018("SCT418/014/2018"),
    @XmlEnumValue("SCT418/014/2019")
    SCT_418_014_2019("SCT418/014/2019"),
    @XmlEnumValue("SCT418/014/2020")
    SCT_418_014_2020("SCT418/014/2020"),
    @XmlEnumValue("SCT418/015/2017")
    SCT_418_015_2017("SCT418/015/2017"),
    @XmlEnumValue("SCT418/015/2018")
    SCT_418_015_2018("SCT418/015/2018"),
    @XmlEnumValue("SCT418/015/2019")
    SCT_418_015_2019("SCT418/015/2019"),
    @XmlEnumValue("SCT418/015/2020")
    SCT_418_015_2020("SCT418/015/2020"),
    @XmlEnumValue("SCT418/016/2017")
    SCT_418_016_2017("SCT418/016/2017"),
    @XmlEnumValue("SCT418/016/2018")
    SCT_418_016_2018("SCT418/016/2018"),
    @XmlEnumValue("SCT418/016/2019")
    SCT_418_016_2019("SCT418/016/2019"),
    @XmlEnumValue("SCT418/016/2020")
    SCT_418_016_2020("SCT418/016/2020"),
    @XmlEnumValue("SCT418/017/2017")
    SCT_418_017_2017("SCT418/017/2017"),
    @XmlEnumValue("SCT418/017/2018")
    SCT_418_017_2018("SCT418/017/2018"),
    @XmlEnumValue("SCT418/017/2019")
    SCT_418_017_2019("SCT418/017/2019"),
    @XmlEnumValue("SCT418/017/2020")
    SCT_418_017_2020("SCT418/017/2020"),
    @XmlEnumValue("SCT418/018/2017")
    SCT_418_018_2017("SCT418/018/2017"),
    @XmlEnumValue("SCT418/018/2018")
    SCT_418_018_2018("SCT418/018/2018"),
    @XmlEnumValue("SCT418/018/2019")
    SCT_418_018_2019("SCT418/018/2019"),
    @XmlEnumValue("SCT418/018/2020")
    SCT_418_018_2020("SCT418/018/2020"),
    @XmlEnumValue("SCT418/019/2017")
    SCT_418_019_2017("SCT418/019/2017"),
    @XmlEnumValue("SCT418/019/2018")
    SCT_418_019_2018("SCT418/019/2018"),
    @XmlEnumValue("SCT418/019/2019")
    SCT_418_019_2019("SCT418/019/2019"),
    @XmlEnumValue("SCT418/019/2020")
    SCT_418_019_2020("SCT418/019/2020"),
    @XmlEnumValue("SCT418/020/2016")
    SCT_418_020_2016("SCT418/020/2016"),
    @XmlEnumValue("SCT418/020/2018")
    SCT_418_020_2018("SCT418/020/2018"),
    @XmlEnumValue("SCT418/020/2019")
    SCT_418_020_2019("SCT418/020/2019"),
    @XmlEnumValue("SCT418/020/2020")
    SCT_418_020_2020("SCT418/020/2020"),
    @XmlEnumValue("SCT418/020/2021")
    SCT_418_020_2021("SCT418/020/2021"),
    @XmlEnumValue("SCT418/021/2016")
    SCT_418_021_2016("SCT418/021/2016"),
    @XmlEnumValue("SCT418/021/2017")
    SCT_418_021_2017("SCT418/021/2017"),
    @XmlEnumValue("SCT418/021/2018")
    SCT_418_021_2018("SCT418/021/2018"),
    @XmlEnumValue("SCT418/021/2019")
    SCT_418_021_2019("SCT418/021/2019"),
    @XmlEnumValue("SCT418/021/2020")
    SCT_418_021_2020("SCT418/021/2020"),
    @XmlEnumValue("SCT418/021/2021")
    SCT_418_021_2021("SCT418/021/2021"),
    @XmlEnumValue("SCT418/022/2017")
    SCT_418_022_2017("SCT418/022/2017"),
    @XmlEnumValue("SCT418/022/2018")
    SCT_418_022_2018("SCT418/022/2018"),
    @XmlEnumValue("SCT418/022/2019")
    SCT_418_022_2019("SCT418/022/2019"),
    @XmlEnumValue("SCT418/022/2020")
    SCT_418_022_2020("SCT418/022/2020"),
    @XmlEnumValue("SCT418/023/2017")
    SCT_418_023_2017("SCT418/023/2017"),
    @XmlEnumValue("SCT418/023/2018")
    SCT_418_023_2018("SCT418/023/2018"),
    @XmlEnumValue("SCT418/023/2019")
    SCT_418_023_2019("SCT418/023/2019"),
    @XmlEnumValue("SCT418/023/2020")
    SCT_418_023_2020("SCT418/023/2020"),
    @XmlEnumValue("SCT418/024/2017")
    SCT_418_024_2017("SCT418/024/2017"),
    @XmlEnumValue("SCT418/024/2018")
    SCT_418_024_2018("SCT418/024/2018"),
    @XmlEnumValue("SCT418/024/2019")
    SCT_418_024_2019("SCT418/024/2019"),
    @XmlEnumValue("SCT418/024/2020")
    SCT_418_024_2020("SCT418/024/2020"),
    @XmlEnumValue("SCT418/025/2016")
    SCT_418_025_2016("SCT418/025/2016"),
    @XmlEnumValue("SCT418/025/2017")
    SCT_418_025_2017("SCT418/025/2017"),
    @XmlEnumValue("SCT418/025/2018")
    SCT_418_025_2018("SCT418/025/2018"),
    @XmlEnumValue("SCT418/025/2019")
    SCT_418_025_2019("SCT418/025/2019"),
    @XmlEnumValue("SCT418/025/2020")
    SCT_418_025_2020("SCT418/025/2020"),
    @XmlEnumValue("SCT418/026/2016")
    SCT_418_026_2016("SCT418/026/2016"),
    @XmlEnumValue("SCT418/026/2017")
    SCT_418_026_2017("SCT418/026/2017"),
    @XmlEnumValue("SCT418/026/2018")
    SCT_418_026_2018("SCT418/026/2018"),
    @XmlEnumValue("SCT418/026/2019")
    SCT_418_026_2019("SCT418/026/2019"),
    @XmlEnumValue("SCT418/026/2020")
    SCT_418_026_2020("SCT418/026/2020"),
    @XmlEnumValue("SCT418/027/2017")
    SCT_418_027_2017("SCT418/027/2017"),
    @XmlEnumValue("SCT418/027/2018")
    SCT_418_027_2018("SCT418/027/2018"),
    @XmlEnumValue("SCT418/027/2019")
    SCT_418_027_2019("SCT418/027/2019"),
    @XmlEnumValue("SCT418/027/2020")
    SCT_418_027_2020("SCT418/027/2020"),
    @XmlEnumValue("SCT418/028/2016")
    SCT_418_028_2016("SCT418/028/2016"),
    @XmlEnumValue("SCT418/028/2017")
    SCT_418_028_2017("SCT418/028/2017"),
    @XmlEnumValue("SCT418/028/2018")
    SCT_418_028_2018("SCT418/028/2018"),
    @XmlEnumValue("SCT418/028/2019")
    SCT_418_028_2019("SCT418/028/2019"),
    @XmlEnumValue("SCT418/028/2020")
    SCT_418_028_2020("SCT418/028/2020"),
    @XmlEnumValue("SCT418/029/2016")
    SCT_418_029_2016("SCT418/029/2016"),
    @XmlEnumValue("SCT418/029/2017")
    SCT_418_029_2017("SCT418/029/2017"),
    @XmlEnumValue("SCT418/029/2018")
    SCT_418_029_2018("SCT418/029/2018"),
    @XmlEnumValue("SCT418/029/2019")
    SCT_418_029_2019("SCT418/029/2019"),
    @XmlEnumValue("SCT418/029/2020")
    SCT_418_029_2020("SCT418/029/2020"),
    @XmlEnumValue("SCT418/030/2016")
    SCT_418_030_2016("SCT418/030/2016"),
    @XmlEnumValue("SCT418/030/2017")
    SCT_418_030_2017("SCT418/030/2017"),
    @XmlEnumValue("SCT418/030/2018")
    SCT_418_030_2018("SCT418/030/2018"),
    @XmlEnumValue("SCT418/030/2019")
    SCT_418_030_2019("SCT418/030/2019"),
    @XmlEnumValue("SCT418/030/2020")
    SCT_418_030_2020("SCT418/030/2020"),
    @XmlEnumValue("SCT418/031/2017")
    SCT_418_031_2017("SCT418/031/2017"),
    @XmlEnumValue("SCT418/031/2018")
    SCT_418_031_2018("SCT418/031/2018"),
    @XmlEnumValue("SCT418/031/2019")
    SCT_418_031_2019("SCT418/031/2019"),
    @XmlEnumValue("SCT418/031/2020")
    SCT_418_031_2020("SCT418/031/2020"),
    @XmlEnumValue("SCT418/032/2017")
    SCT_418_032_2017("SCT418/032/2017"),
    @XmlEnumValue("SCT418/032/2018")
    SCT_418_032_2018("SCT418/032/2018"),
    @XmlEnumValue("SCT418/032/2019")
    SCT_418_032_2019("SCT418/032/2019"),
    @XmlEnumValue("SCT418/032/2020")
    SCT_418_032_2020("SCT418/032/2020"),
    @XmlEnumValue("SCT418/033/2017")
    SCT_418_033_2017("SCT418/033/2017"),
    @XmlEnumValue("SCT418/033/2018")
    SCT_418_033_2018("SCT418/033/2018"),
    @XmlEnumValue("SCT418/033/2019")
    SCT_418_033_2019("SCT418/033/2019"),
    @XmlEnumValue("SCT418/033/2020")
    SCT_418_033_2020("SCT418/033/2020"),
    @XmlEnumValue("SCT418/034/2016")
    SCT_418_034_2016("SCT418/034/2016"),
    @XmlEnumValue("SCT418/034/2017")
    SCT_418_034_2017("SCT418/034/2017"),
    @XmlEnumValue("SCT418/034/2018")
    SCT_418_034_2018("SCT418/034/2018"),
    @XmlEnumValue("SCT418/034/2019")
    SCT_418_034_2019("SCT418/034/2019"),
    @XmlEnumValue("SCT418/034/2020")
    SCT_418_034_2020("SCT418/034/2020"),
    @XmlEnumValue("SCT418/035/2017")
    SCT_418_035_2017("SCT418/035/2017"),
    @XmlEnumValue("SCT418/035/2018")
    SCT_418_035_2018("SCT418/035/2018"),
    @XmlEnumValue("SCT418/035/2019")
    SCT_418_035_2019("SCT418/035/2019"),
    @XmlEnumValue("SCT418/035/2020")
    SCT_418_035_2020("SCT418/035/2020"),
    @XmlEnumValue("SCT418/036/2016")
    SCT_418_036_2016("SCT418/036/2016"),
    @XmlEnumValue("SCT418/036/2017")
    SCT_418_036_2017("SCT418/036/2017"),
    @XmlEnumValue("SCT418/036/2018")
    SCT_418_036_2018("SCT418/036/2018"),
    @XmlEnumValue("SCT418/036/2019")
    SCT_418_036_2019("SCT418/036/2019"),
    @XmlEnumValue("SCT418/036/2020")
    SCT_418_036_2020("SCT418/036/2020"),
    @XmlEnumValue("SCT418/037/2017")
    SCT_418_037_2017("SCT418/037/2017"),
    @XmlEnumValue("SCT418/037/2018")
    SCT_418_037_2018("SCT418/037/2018"),
    @XmlEnumValue("SCT418/037/2019")
    SCT_418_037_2019("SCT418/037/2019"),
    @XmlEnumValue("SCT418/037/2020")
    SCT_418_037_2020("SCT418/037/2020"),
    @XmlEnumValue("SCT418/038/2017")
    SCT_418_038_2017("SCT418/038/2017"),
    @XmlEnumValue("SCT418/038/2018")
    SCT_418_038_2018("SCT418/038/2018"),
    @XmlEnumValue("SCT418/038/2019")
    SCT_418_038_2019("SCT418/038/2019"),
    @XmlEnumValue("SCT418/038/2020")
    SCT_418_038_2020("SCT418/038/2020"),
    @XmlEnumValue("SCT418/039/2017")
    SCT_418_039_2017("SCT418/039/2017"),
    @XmlEnumValue("SCT418/039/2018")
    SCT_418_039_2018("SCT418/039/2018"),
    @XmlEnumValue("SCT418/039/2019")
    SCT_418_039_2019("SCT418/039/2019"),
    @XmlEnumValue("SCT418/039/2020")
    SCT_418_039_2020("SCT418/039/2020"),
    @XmlEnumValue("SCT418/040/2017")
    SCT_418_040_2017("SCT418/040/2017"),
    @XmlEnumValue("SCT418/040/2018")
    SCT_418_040_2018("SCT418/040/2018"),
    @XmlEnumValue("SCT418/040/2019")
    SCT_418_040_2019("SCT418/040/2019"),
    @XmlEnumValue("SCT418/040/2020")
    SCT_418_040_2020("SCT418/040/2020"),
    @XmlEnumValue("SCT418/041/2017")
    SCT_418_041_2017("SCT418/041/2017"),
    @XmlEnumValue("SCT418/041/2018")
    SCT_418_041_2018("SCT418/041/2018"),
    @XmlEnumValue("SCT418/041/2019")
    SCT_418_041_2019("SCT418/041/2019"),
    @XmlEnumValue("SCT418/041/2020")
    SCT_418_041_2020("SCT418/041/2020"),
    @XmlEnumValue("SCT418/042/2016")
    SCT_418_042_2016("SCT418/042/2016"),
    @XmlEnumValue("SCT418/042/2017")
    SCT_418_042_2017("SCT418/042/2017"),
    @XmlEnumValue("SCT418/042/2018")
    SCT_418_042_2018("SCT418/042/2018"),
    @XmlEnumValue("SCT418/042/2019")
    SCT_418_042_2019("SCT418/042/2019"),
    @XmlEnumValue("SCT418/042/2020")
    SCT_418_042_2020("SCT418/042/2020"),
    @XmlEnumValue("SCT418/043/2017")
    SCT_418_043_2017("SCT418/043/2017"),
    @XmlEnumValue("SCT418/043/2018")
    SCT_418_043_2018("SCT418/043/2018"),
    @XmlEnumValue("SCT418/043/2019")
    SCT_418_043_2019("SCT418/043/2019"),
    @XmlEnumValue("SCT418/044/2017")
    SCT_418_044_2017("SCT418/044/2017"),
    @XmlEnumValue("SCT418/044/2018")
    SCT_418_044_2018("SCT418/044/2018"),
    @XmlEnumValue("SCT418/044/2019")
    SCT_418_044_2019("SCT418/044/2019"),
    @XmlEnumValue("SCT418/045/2017")
    SCT_418_045_2017("SCT418/045/2017"),
    @XmlEnumValue("SCT418/045/2018")
    SCT_418_045_2018("SCT418/045/2018"),
    @XmlEnumValue("SCT418/045/2019")
    SCT_418_045_2019("SCT418/045/2019"),
    @XmlEnumValue("SCT418/046/2016")
    SCT_418_046_2016("SCT418/046/2016"),
    @XmlEnumValue("SCT418/046/2017")
    SCT_418_046_2017("SCT418/046/2017"),
    @XmlEnumValue("SCT418/046/2018")
    SCT_418_046_2018("SCT418/046/2018"),
    @XmlEnumValue("SCT418/046/2019")
    SCT_418_046_2019("SCT418/046/2019"),
    @XmlEnumValue("SCT418/047/2016")
    SCT_418_047_2016("SCT418/047/2016"),
    @XmlEnumValue("SCT418/047/2017")
    SCT_418_047_2017("SCT418/047/2017"),
    @XmlEnumValue("SCT418/047/2018")
    SCT_418_047_2018("SCT418/047/2018"),
    @XmlEnumValue("SCT418/047/2019")
    SCT_418_047_2019("SCT418/047/2019"),
    @XmlEnumValue("SCT418/048/2016")
    SCT_418_048_2016("SCT418/048/2016"),
    @XmlEnumValue("SCT418/048/2017")
    SCT_418_048_2017("SCT418/048/2017"),
    @XmlEnumValue("SCT418/048/2018")
    SCT_418_048_2018("SCT418/048/2018"),
    @XmlEnumValue("SCT418/048/2019")
    SCT_418_048_2019("SCT418/048/2019"),
    @XmlEnumValue("SCT418/049/2017")
    SCT_418_049_2017("SCT418/049/2017"),
    @XmlEnumValue("SCT418/049/2018")
    SCT_418_049_2018("SCT418/049/2018"),
    @XmlEnumValue("SCT418/049/2019")
    SCT_418_049_2019("SCT418/049/2019"),
    @XmlEnumValue("SCT418/050/2017")
    SCT_418_050_2017("SCT418/050/2017"),
    @XmlEnumValue("SCT418/050/2018")
    SCT_418_050_2018("SCT418/050/2018"),
    @XmlEnumValue("SCT418/050/2019")
    SCT_418_050_2019("SCT418/050/2019"),
    @XmlEnumValue("SCT418/051/2016")
    SCT_418_051_2016("SCT418/051/2016"),
    @XmlEnumValue("SCT418/051/2017")
    SCT_418_051_2017("SCT418/051/2017"),
    @XmlEnumValue("SCT418/051/2018")
    SCT_418_051_2018("SCT418/051/2018"),
    @XmlEnumValue("SCT418/051/2019")
    SCT_418_051_2019("SCT418/051/2019"),
    @XmlEnumValue("SCT418/052/2016")
    SCT_418_052_2016("SCT418/052/2016"),
    @XmlEnumValue("SCT418/052/2017")
    SCT_418_052_2017("SCT418/052/2017"),
    @XmlEnumValue("SCT418/052/2018")
    SCT_418_052_2018("SCT418/052/2018"),
    @XmlEnumValue("SCT418/052/2019")
    SCT_418_052_2019("SCT418/052/2019"),
    @XmlEnumValue("SCT418/053/2017")
    SCT_418_053_2017("SCT418/053/2017"),
    @XmlEnumValue("SCT418/053/2018")
    SCT_418_053_2018("SCT418/053/2018"),
    @XmlEnumValue("SCT418/053/2019")
    SCT_418_053_2019("SCT418/053/2019"),
    @XmlEnumValue("SCT418/054/2017")
    SCT_418_054_2017("SCT418/054/2017"),
    @XmlEnumValue("SCT418/054/2018")
    SCT_418_054_2018("SCT418/054/2018"),
    @XmlEnumValue("SCT418/054/2019")
    SCT_418_054_2019("SCT418/054/2019"),
    @XmlEnumValue("SCT418/055/2017")
    SCT_418_055_2017("SCT418/055/2017"),
    @XmlEnumValue("SCT418/055/2018")
    SCT_418_055_2018("SCT418/055/2018"),
    @XmlEnumValue("SCT418/056/2017")
    SCT_418_056_2017("SCT418/056/2017"),
    @XmlEnumValue("SCT418/056/2018")
    SCT_418_056_2018("SCT418/056/2018"),
    @XmlEnumValue("SCT418/057/2017")
    SCT_418_057_2017("SCT418/057/2017"),
    @XmlEnumValue("SCT418/057/2018")
    SCT_418_057_2018("SCT418/057/2018"),
    @XmlEnumValue("SCT418/058/2017")
    SCT_418_058_2017("SCT418/058/2017"),
    @XmlEnumValue("SCT418/058/2018")
    SCT_418_058_2018("SCT418/058/2018"),
    @XmlEnumValue("SCT418/059/2018")
    SCT_418_059_2018("SCT418/059/2018"),
    @XmlEnumValue("SCT418/060/2017")
    SCT_418_060_2017("SCT418/060/2017"),
    @XmlEnumValue("SCT418/060/2018")
    SCT_418_060_2018("SCT418/060/2018"),
    @XmlEnumValue("SCT418/061/2017")
    SCT_418_061_2017("SCT418/061/2017"),
    @XmlEnumValue("SCT418/061/2018")
    SCT_418_061_2018("SCT418/061/2018"),
    @XmlEnumValue("SCT418/062/2018")
    SCT_418_062_2018("SCT418/062/2018"),
    @XmlEnumValue("SCT418/063/2017")
    SCT_418_063_2017("SCT418/063/2017"),
    @XmlEnumValue("SCT418/063/2018")
    SCT_418_063_2018("SCT418/063/2018"),
    @XmlEnumValue("SCT418/064/2017")
    SCT_418_064_2017("SCT418/064/2017"),
    @XmlEnumValue("SCT418/064/2018")
    SCT_418_064_2018("SCT418/064/2018"),
    @XmlEnumValue("SCT418/065/2017")
    SCT_418_065_2017("SCT418/065/2017"),
    @XmlEnumValue("SCT418/065/2018")
    SCT_418_065_2018("SCT418/065/2018"),
    @XmlEnumValue("SCT418/066/2017")
    SCT_418_066_2017("SCT418/066/2017"),
    @XmlEnumValue("SCT418/066/2018")
    SCT_418_066_2018("SCT418/066/2018"),
    @XmlEnumValue("SCT418/067/2017")
    SCT_418_067_2017("SCT418/067/2017"),
    @XmlEnumValue("SCT418/067/2018")
    SCT_418_067_2018("SCT418/067/2018"),
    @XmlEnumValue("SCT418/068/2017")
    SCT_418_068_2017("SCT418/068/2017"),
    @XmlEnumValue("SCT418/068/2018")
    SCT_418_068_2018("SCT418/068/2018"),
    @XmlEnumValue("SCT418/069/2017")
    SCT_418_069_2017("SCT418/069/2017"),
    @XmlEnumValue("SCT418/069/2018")
    SCT_418_069_2018("SCT418/069/2018");
    private final String value;

    CNumAutorizacionNaviero(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CNumAutorizacionNaviero fromValue(String v) {
        for (CNumAutorizacionNaviero c: CNumAutorizacionNaviero.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
