//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.catalogos.CartaPorte;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_ParteTransporte.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="c_ParteTransporte">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <whiteSpace value="collapse"/>
 *     <enumeration value="PT01"/>
 *     <enumeration value="PT02"/>
 *     <enumeration value="PT03"/>
 *     <enumeration value="PT04"/>
 *     <enumeration value="PT05"/>
 *     <enumeration value="PT06"/>
 *     <enumeration value="PT07"/>
 *     <enumeration value="PT08"/>
 *     <enumeration value="PT09"/>
 *     <enumeration value="PT10"/>
 *     <enumeration value="PT11"/>
 *     <enumeration value="PT12"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "c_ParteTransporte", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte")
@XmlEnum
public enum CParteTransporte {

    @XmlEnumValue("PT01")
    PT_01("PT01"),
    @XmlEnumValue("PT02")
    PT_02("PT02"),
    @XmlEnumValue("PT03")
    PT_03("PT03"),
    @XmlEnumValue("PT04")
    PT_04("PT04"),
    @XmlEnumValue("PT05")
    PT_05("PT05"),
    @XmlEnumValue("PT06")
    PT_06("PT06"),
    @XmlEnumValue("PT07")
    PT_07("PT07"),
    @XmlEnumValue("PT08")
    PT_08("PT08"),
    @XmlEnumValue("PT09")
    PT_09("PT09"),
    @XmlEnumValue("PT10")
    PT_10("PT10"),
    @XmlEnumValue("PT11")
    PT_11("PT11"),
    @XmlEnumValue("PT12")
    PT_12("PT12");
    private final String value;

    CParteTransporte(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CParteTransporte fromValue(String v) {
        for (CParteTransporte c: CParteTransporte.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
