//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.catalogos.CartaPorte;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_RegimenAduanero.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="c_RegimenAduanero">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <whiteSpace value="collapse"/>
 *     <enumeration value="IMD"/>
 *     <enumeration value="EXD"/>
 *     <enumeration value="ITR"/>
 *     <enumeration value="ITE"/>
 *     <enumeration value="ETR"/>
 *     <enumeration value="ETE"/>
 *     <enumeration value="DFI"/>
 *     <enumeration value="RFE"/>
 *     <enumeration value="RFS"/>
 *     <enumeration value="TRA"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "c_RegimenAduanero", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte")
@XmlEnum
public enum CRegimenAduanero {

    IMD,
    EXD,
    ITR,
    ITE,
    ETR,
    ETE,
    DFI,
    RFE,
    RFS,
    TRA;

    public String value() {
        return name();
    }

    public static CRegimenAduanero fromValue(String v) {
        return valueOf(v);
    }

}
