//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.catalogos.CartaPorte;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_SubTipoRem.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="c_SubTipoRem">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <whiteSpace value="collapse"/>
 *     <enumeration value="CTR001"/>
 *     <enumeration value="CTR002"/>
 *     <enumeration value="CTR003"/>
 *     <enumeration value="CTR004"/>
 *     <enumeration value="CTR005"/>
 *     <enumeration value="CTR006"/>
 *     <enumeration value="CTR007"/>
 *     <enumeration value="CTR008"/>
 *     <enumeration value="CTR009"/>
 *     <enumeration value="CTR010"/>
 *     <enumeration value="CTR011"/>
 *     <enumeration value="CTR012"/>
 *     <enumeration value="CTR013"/>
 *     <enumeration value="CTR014"/>
 *     <enumeration value="CTR015"/>
 *     <enumeration value="CTR016"/>
 *     <enumeration value="CTR017"/>
 *     <enumeration value="CTR018"/>
 *     <enumeration value="CTR019"/>
 *     <enumeration value="CTR020"/>
 *     <enumeration value="CTR021"/>
 *     <enumeration value="CTR022"/>
 *     <enumeration value="CTR023"/>
 *     <enumeration value="CTR024"/>
 *     <enumeration value="CTR025"/>
 *     <enumeration value="CTR026"/>
 *     <enumeration value="CTR027"/>
 *     <enumeration value="CTR028"/>
 *     <enumeration value="CTR029"/>
 *     <enumeration value="CTR030"/>
 *     <enumeration value="CTR031"/>
 *     <enumeration value="CTR032"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "c_SubTipoRem", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte")
@XmlEnum
public enum CSubTipoRem {

    @XmlEnumValue("CTR001")
    CTR_001("CTR001"),
    @XmlEnumValue("CTR002")
    CTR_002("CTR002"),
    @XmlEnumValue("CTR003")
    CTR_003("CTR003"),
    @XmlEnumValue("CTR004")
    CTR_004("CTR004"),
    @XmlEnumValue("CTR005")
    CTR_005("CTR005"),
    @XmlEnumValue("CTR006")
    CTR_006("CTR006"),
    @XmlEnumValue("CTR007")
    CTR_007("CTR007"),
    @XmlEnumValue("CTR008")
    CTR_008("CTR008"),
    @XmlEnumValue("CTR009")
    CTR_009("CTR009"),
    @XmlEnumValue("CTR010")
    CTR_010("CTR010"),
    @XmlEnumValue("CTR011")
    CTR_011("CTR011"),
    @XmlEnumValue("CTR012")
    CTR_012("CTR012"),
    @XmlEnumValue("CTR013")
    CTR_013("CTR013"),
    @XmlEnumValue("CTR014")
    CTR_014("CTR014"),
    @XmlEnumValue("CTR015")
    CTR_015("CTR015"),
    @XmlEnumValue("CTR016")
    CTR_016("CTR016"),
    @XmlEnumValue("CTR017")
    CTR_017("CTR017"),
    @XmlEnumValue("CTR018")
    CTR_018("CTR018"),
    @XmlEnumValue("CTR019")
    CTR_019("CTR019"),
    @XmlEnumValue("CTR020")
    CTR_020("CTR020"),
    @XmlEnumValue("CTR021")
    CTR_021("CTR021"),
    @XmlEnumValue("CTR022")
    CTR_022("CTR022"),
    @XmlEnumValue("CTR023")
    CTR_023("CTR023"),
    @XmlEnumValue("CTR024")
    CTR_024("CTR024"),
    @XmlEnumValue("CTR025")
    CTR_025("CTR025"),
    @XmlEnumValue("CTR026")
    CTR_026("CTR026"),
    @XmlEnumValue("CTR027")
    CTR_027("CTR027"),
    @XmlEnumValue("CTR028")
    CTR_028("CTR028"),
    @XmlEnumValue("CTR029")
    CTR_029("CTR029"),
    @XmlEnumValue("CTR030")
    CTR_030("CTR030"),
    @XmlEnumValue("CTR031")
    CTR_031("CTR031"),
    @XmlEnumValue("CTR032")
    CTR_032("CTR032");
    private final String value;

    CSubTipoRem(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CSubTipoRem fromValue(String v) {
        for (CSubTipoRem c: CSubTipoRem.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
