//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.catalogos.CartaPorte;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_TipoDeTrafico.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="c_TipoDeTrafico">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <whiteSpace value="collapse"/>
 *     <enumeration value="TT01"/>
 *     <enumeration value="TT02"/>
 *     <enumeration value="TT03"/>
 *     <enumeration value="TT04"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "c_TipoDeTrafico", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte")
@XmlEnum
public enum CTipoDeTrafico {

    @XmlEnumValue("TT01")
    TT_01("TT01"),
    @XmlEnumValue("TT02")
    TT_02("TT02"),
    @XmlEnumValue("TT03")
    TT_03("TT03"),
    @XmlEnumValue("TT04")
    TT_04("TT04");
    private final String value;

    CTipoDeTrafico(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CTipoDeTrafico fromValue(String v) {
        for (CTipoDeTrafico c: CTipoDeTrafico.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
