//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.catalogos.CartaPorte;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_TipoDeServicio.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="c_TipoDeServicio">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <whiteSpace value="collapse"/>
 *     <enumeration value="TS01"/>
 *     <enumeration value="TS02"/>
 *     <enumeration value="TS03"/>
 *     <enumeration value="TS04"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "c_TipoDeServicio", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte")
@XmlEnum
public enum CTipoDeServicio {

    @XmlEnumValue("TS01")
    TS_01("TS01"),
    @XmlEnumValue("TS02")
    TS_02("TS02"),
    @XmlEnumValue("TS03")
    TS_03("TS03"),
    @XmlEnumValue("TS04")
    TS_04("TS04");
    private final String value;

    CTipoDeServicio(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CTipoDeServicio fromValue(String v) {
        for (CTipoDeServicio c: CTipoDeServicio.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
