//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.catalogos.CartaPorte;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_TipoEmbalaje.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="c_TipoEmbalaje">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <whiteSpace value="collapse"/>
 *     <enumeration value="1A1"/>
 *     <enumeration value="1A2"/>
 *     <enumeration value="1B1"/>
 *     <enumeration value="1B2"/>
 *     <enumeration value="1D"/>
 *     <enumeration value="1G"/>
 *     <enumeration value="1H1"/>
 *     <enumeration value="1H2"/>
 *     <enumeration value="1N1"/>
 *     <enumeration value="1N2"/>
 *     <enumeration value="3A1"/>
 *     <enumeration value="3A2"/>
 *     <enumeration value="3B1"/>
 *     <enumeration value="3B2"/>
 *     <enumeration value="3H1"/>
 *     <enumeration value="3H2"/>
 *     <enumeration value="4A"/>
 *     <enumeration value="4B"/>
 *     <enumeration value="4C1"/>
 *     <enumeration value="4C2"/>
 *     <enumeration value="4D"/>
 *     <enumeration value="4F"/>
 *     <enumeration value="4G"/>
 *     <enumeration value="4H1"/>
 *     <enumeration value="4H2"/>
 *     <enumeration value="5H1"/>
 *     <enumeration value="5H2"/>
 *     <enumeration value="5H3"/>
 *     <enumeration value="5H4"/>
 *     <enumeration value="5L1"/>
 *     <enumeration value="5L2"/>
 *     <enumeration value="5L3"/>
 *     <enumeration value="5M1"/>
 *     <enumeration value="5M2"/>
 *     <enumeration value="6HA1"/>
 *     <enumeration value="6HA2"/>
 *     <enumeration value="6HB1"/>
 *     <enumeration value="6HB2"/>
 *     <enumeration value="6HC"/>
 *     <enumeration value="6HD1"/>
 *     <enumeration value="6HD2"/>
 *     <enumeration value="6HG1"/>
 *     <enumeration value="6HG2"/>
 *     <enumeration value="6HH1"/>
 *     <enumeration value="6HH2"/>
 *     <enumeration value="6PA1"/>
 *     <enumeration value="6PA2"/>
 *     <enumeration value="6PB1"/>
 *     <enumeration value="6PB2"/>
 *     <enumeration value="6PC"/>
 *     <enumeration value="6PD1"/>
 *     <enumeration value="6PD2"/>
 *     <enumeration value="6PG1"/>
 *     <enumeration value="6PG2"/>
 *     <enumeration value="6PH1"/>
 *     <enumeration value="6PH2"/>
 *     <enumeration value="7H1"/>
 *     <enumeration value="7L1"/>
 *     <enumeration value="Z01"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "c_TipoEmbalaje", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte")
@XmlEnum
public enum CTipoEmbalaje {

    @XmlEnumValue("1A1")
    VALUE_1("1A1"),
    @XmlEnumValue("1A2")
    VALUE_2("1A2"),
    @XmlEnumValue("1B1")
    VALUE_3("1B1"),
    @XmlEnumValue("1B2")
    VALUE_4("1B2"),
    @XmlEnumValue("1D")
    VALUE_5("1D"),
    @XmlEnumValue("1G")
    VALUE_6("1G"),
    @XmlEnumValue("1H1")
    VALUE_7("1H1"),
    @XmlEnumValue("1H2")
    VALUE_8("1H2"),
    @XmlEnumValue("1N1")
    VALUE_9("1N1"),
    @XmlEnumValue("1N2")
    VALUE_10("1N2"),
    @XmlEnumValue("3A1")
    VALUE_11("3A1"),
    @XmlEnumValue("3A2")
    VALUE_12("3A2"),
    @XmlEnumValue("3B1")
    VALUE_13("3B1"),
    @XmlEnumValue("3B2")
    VALUE_14("3B2"),
    @XmlEnumValue("3H1")
    VALUE_15("3H1"),
    @XmlEnumValue("3H2")
    VALUE_16("3H2"),
    @XmlEnumValue("4A")
    VALUE_17("4A"),
    @XmlEnumValue("4B")
    VALUE_18("4B"),
    @XmlEnumValue("4C1")
    VALUE_19("4C1"),
    @XmlEnumValue("4C2")
    VALUE_20("4C2"),
    @XmlEnumValue("4D")
    VALUE_21("4D"),
    @XmlEnumValue("4F")
    VALUE_22("4F"),
    @XmlEnumValue("4G")
    VALUE_23("4G"),
    @XmlEnumValue("4H1")
    VALUE_24("4H1"),
    @XmlEnumValue("4H2")
    VALUE_25("4H2"),
    @XmlEnumValue("5H1")
    VALUE_26("5H1"),
    @XmlEnumValue("5H2")
    VALUE_27("5H2"),
    @XmlEnumValue("5H3")
    VALUE_28("5H3"),
    @XmlEnumValue("5H4")
    VALUE_29("5H4"),
    @XmlEnumValue("5L1")
    VALUE_30("5L1"),
    @XmlEnumValue("5L2")
    VALUE_31("5L2"),
    @XmlEnumValue("5L3")
    VALUE_32("5L3"),
    @XmlEnumValue("5M1")
    VALUE_33("5M1"),
    @XmlEnumValue("5M2")
    VALUE_34("5M2"),
    @XmlEnumValue("6HA1")
    VALUE_35("6HA1"),
    @XmlEnumValue("6HA2")
    VALUE_36("6HA2"),
    @XmlEnumValue("6HB1")
    VALUE_37("6HB1"),
    @XmlEnumValue("6HB2")
    VALUE_38("6HB2"),
    @XmlEnumValue("6HC")
    VALUE_39("6HC"),
    @XmlEnumValue("6HD1")
    VALUE_40("6HD1"),
    @XmlEnumValue("6HD2")
    VALUE_41("6HD2"),
    @XmlEnumValue("6HG1")
    VALUE_42("6HG1"),
    @XmlEnumValue("6HG2")
    VALUE_43("6HG2"),
    @XmlEnumValue("6HH1")
    VALUE_44("6HH1"),
    @XmlEnumValue("6HH2")
    VALUE_45("6HH2"),
    @XmlEnumValue("6PA1")
    VALUE_46("6PA1"),
    @XmlEnumValue("6PA2")
    VALUE_47("6PA2"),
    @XmlEnumValue("6PB1")
    VALUE_48("6PB1"),
    @XmlEnumValue("6PB2")
    VALUE_49("6PB2"),
    @XmlEnumValue("6PC")
    VALUE_50("6PC"),
    @XmlEnumValue("6PD1")
    VALUE_51("6PD1"),
    @XmlEnumValue("6PD2")
    VALUE_52("6PD2"),
    @XmlEnumValue("6PG1")
    VALUE_53("6PG1"),
    @XmlEnumValue("6PG2")
    VALUE_54("6PG2"),
    @XmlEnumValue("6PH1")
    VALUE_55("6PH1"),
    @XmlEnumValue("6PH2")
    VALUE_56("6PH2"),
    @XmlEnumValue("7H1")
    VALUE_57("7H1"),
    @XmlEnumValue("7L1")
    VALUE_58("7L1"),
    @XmlEnumValue("Z01")
    VALUE_59("Z01");
    private final String value;

    CTipoEmbalaje(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CTipoEmbalaje fromValue(String v) {
        for (CTipoEmbalaje c: CTipoEmbalaje.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
