//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.catalogos.Nomina;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_TipoRegimen.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="c_TipoRegimen">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <whiteSpace value="collapse"/>
 *     <enumeration value="02"/>
 *     <enumeration value="03"/>
 *     <enumeration value="04"/>
 *     <enumeration value="05"/>
 *     <enumeration value="06"/>
 *     <enumeration value="07"/>
 *     <enumeration value="08"/>
 *     <enumeration value="09"/>
 *     <enumeration value="10"/>
 *     <enumeration value="11"/>
 *     <enumeration value="12"/>
 *     <enumeration value="13"/>
 *     <enumeration value="99"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "c_TipoRegimen", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Nomina")
@XmlEnum
public enum CTipoRegimen {

    @XmlEnumValue("02")
    VALUE_1("02"),
    @XmlEnumValue("03")
    VALUE_2("03"),
    @XmlEnumValue("04")
    VALUE_3("04"),
    @XmlEnumValue("05")
    VALUE_4("05"),
    @XmlEnumValue("06")
    VALUE_5("06"),
    @XmlEnumValue("07")
    VALUE_6("07"),
    @XmlEnumValue("08")
    VALUE_7("08"),
    @XmlEnumValue("09")
    VALUE_8("09"),
    @XmlEnumValue("10")
    VALUE_9("10"),
    @XmlEnumValue("11")
    VALUE_10("11"),
    @XmlEnumValue("12")
    VALUE_11("12"),
    @XmlEnumValue("13")
    VALUE_12("13"),
    @XmlEnumValue("99")
    VALUE_13("99");
    private final String value;

    CTipoRegimen(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CTipoRegimen fromValue(String v) {
        for (CTipoRegimen c: CTipoRegimen.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
