//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.renovacionysustitucionvehiculos10;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_TipoDecreto.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="c_TipoDecreto">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="01"/>
 *     <enumeration value="02"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "c_TipoDecreto")
@XmlEnum
public enum CTipoDecreto {

    @XmlEnumValue("01")
    VALUE_1("01"),
    @XmlEnumValue("02")
    VALUE_2("02");
    private final String value;

    CTipoDecreto(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CTipoDecreto fromValue(String v) {
        for (CTipoDecreto c: CTipoDecreto.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
