//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.EstadoDeCuentaCombustible11;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_claveProducto.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="c_claveProducto">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="32011"/>
 *     <enumeration value="32012"/>
 *     <enumeration value="34006"/>
 *     <enumeration value="34008"/>
 *     <enumeration value="Otros"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "c_claveProducto")
@XmlEnum
public enum CClaveProducto {

    @XmlEnumValue("32011")
    VALUE_1("32011"),
    @XmlEnumValue("32012")
    VALUE_2("32012"),
    @XmlEnumValue("34006")
    VALUE_3("34006"),
    @XmlEnumValue("34008")
    VALUE_4("34008"),
    @XmlEnumValue("Otros")
    VALUE_5("Otros");
    private final String value;

    CClaveProducto(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CClaveProducto fromValue(String v) {
        for (CClaveProducto c: CClaveProducto.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
