//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.EstadoDeCuentaCombustible11;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.grupocorasa.sat.common.EstadoDeCuentaCombustible11 package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.grupocorasa.sat.common.EstadoDeCuentaCombustible11
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EstadoDeCuentaCombustible }
     * 
     * @return
     *     the new instance of {@link EstadoDeCuentaCombustible }
     */
    public EstadoDeCuentaCombustible createEstadoDeCuentaCombustible() {
        return new EstadoDeCuentaCombustible();
    }

    /**
     * Create an instance of {@link EstadoDeCuentaCombustible.Conceptos }
     * 
     * @return
     *     the new instance of {@link EstadoDeCuentaCombustible.Conceptos }
     */
    public EstadoDeCuentaCombustible.Conceptos createEstadoDeCuentaCombustibleConceptos() {
        return new EstadoDeCuentaCombustible.Conceptos();
    }

    /**
     * Create an instance of {@link EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible }
     * 
     * @return
     *     the new instance of {@link EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible }
     */
    public EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible createEstadoDeCuentaCombustibleConceptosConceptoEstadoDeCuentaCombustible() {
        return new EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible();
    }

    /**
     * Create an instance of {@link EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible.Traslados }
     * 
     * @return
     *     the new instance of {@link EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible.Traslados }
     */
    public EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible.Traslados createEstadoDeCuentaCombustibleConceptosConceptoEstadoDeCuentaCombustibleTraslados() {
        return new EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible.Traslados();
    }

    /**
     * Create an instance of {@link EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible.Traslados.Traslado }
     * 
     * @return
     *     the new instance of {@link EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible.Traslados.Traslado }
     */
    public EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible.Traslados.Traslado createEstadoDeCuentaCombustibleConceptosConceptoEstadoDeCuentaCombustibleTrasladosTraslado() {
        return new EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible.Traslados.Traslado();
    }

}
