//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.ComercioExterior10;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_INCOTERM.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="c_INCOTERM">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="CFR"/>
 *     <enumeration value="CIF"/>
 *     <enumeration value="CPT"/>
 *     <enumeration value="CIP"/>
 *     <enumeration value="DAF"/>
 *     <enumeration value="DAP"/>
 *     <enumeration value="DAT"/>
 *     <enumeration value="DES"/>
 *     <enumeration value="DEQ"/>
 *     <enumeration value="DDU"/>
 *     <enumeration value="DDP"/>
 *     <enumeration value="EXW"/>
 *     <enumeration value="FCA"/>
 *     <enumeration value="FAS"/>
 *     <enumeration value="FOB"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "c_INCOTERM")
@XmlEnum
public enum CINCOTERM {

    CFR,
    CIF,
    CPT,
    CIP,
    DAF,
    DAP,
    DAT,
    DES,
    DEQ,
    DDU,
    DDP,
    EXW,
    FCA,
    FAS,
    FOB;

    public String value() {
        return name();
    }

    public static CINCOTERM fromValue(String v) {
        return valueOf(v);
    }

}
