//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.ComercioExterior10;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_UnidadMedidaAduana.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="c_UnidadMedidaAduana">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="1"/>
 *     <enumeration value="2"/>
 *     <enumeration value="3"/>
 *     <enumeration value="4"/>
 *     <enumeration value="5"/>
 *     <enumeration value="6"/>
 *     <enumeration value="7"/>
 *     <enumeration value="8"/>
 *     <enumeration value="9"/>
 *     <enumeration value="10"/>
 *     <enumeration value="11"/>
 *     <enumeration value="12"/>
 *     <enumeration value="13"/>
 *     <enumeration value="14"/>
 *     <enumeration value="15"/>
 *     <enumeration value="16"/>
 *     <enumeration value="17"/>
 *     <enumeration value="18"/>
 *     <enumeration value="19"/>
 *     <enumeration value="20"/>
 *     <enumeration value="21"/>
 *     <enumeration value="99"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "c_UnidadMedidaAduana")
@XmlEnum
public enum CUnidadMedidaAduana {

    @XmlEnumValue("1")
    VALUE_1("1"),
    @XmlEnumValue("2")
    VALUE_2("2"),
    @XmlEnumValue("3")
    VALUE_3("3"),
    @XmlEnumValue("4")
    VALUE_4("4"),
    @XmlEnumValue("5")
    VALUE_5("5"),
    @XmlEnumValue("6")
    VALUE_6("6"),
    @XmlEnumValue("7")
    VALUE_7("7"),
    @XmlEnumValue("8")
    VALUE_8("8"),
    @XmlEnumValue("9")
    VALUE_9("9"),
    @XmlEnumValue("10")
    VALUE_10("10"),
    @XmlEnumValue("11")
    VALUE_11("11"),
    @XmlEnumValue("12")
    VALUE_12("12"),
    @XmlEnumValue("13")
    VALUE_13("13"),
    @XmlEnumValue("14")
    VALUE_14("14"),
    @XmlEnumValue("15")
    VALUE_15("15"),
    @XmlEnumValue("16")
    VALUE_16("16"),
    @XmlEnumValue("17")
    VALUE_17("17"),
    @XmlEnumValue("18")
    VALUE_18("18"),
    @XmlEnumValue("19")
    VALUE_19("19"),
    @XmlEnumValue("20")
    VALUE_20("20"),
    @XmlEnumValue("21")
    VALUE_21("21"),
    @XmlEnumValue("99")
    VALUE_22("99");
    private final String value;

    CUnidadMedidaAduana(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CUnidadMedidaAduana fromValue(String v) {
        for (CUnidadMedidaAduana c: CUnidadMedidaAduana.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
