//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.arteantiguedades10;

import java.math.BigDecimal;
import java.time.LocalDate;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import mx.grupocorasa.sat.util.DateAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <attribute name="Version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1.0" />
 *       <attribute name="TipoBien" use="required">
 *         <simpleType>
 *           <restriction base="{http://www.sat.gob.mx/arteantiguedades}c_TipoBien">
 *             <length value="2"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="OtrosTipoBien">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             <minLength value="1"/>
 *             <maxLength value="255"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="TituloAdquirido" use="required">
 *         <simpleType>
 *           <restriction base="{http://www.sat.gob.mx/arteantiguedades}c_Tituloadquirido">
 *             <length value="2"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="OtrosTituloAdquirido">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             <minLength value="1"/>
 *             <maxLength value="255"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="Subtotal" type="{http://www.sat.gob.mx/arteantiguedades}t_Importe" />
 *       <attribute name="IVA" type="{http://www.sat.gob.mx/arteantiguedades}t_Importe" />
 *       <attribute name="FechaAdquisicion" use="required">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *             <whiteSpace value="collapse"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="CaracterísticasDeObraoPieza" use="required">
 *         <simpleType>
 *           <restriction base="{http://www.sat.gob.mx/arteantiguedades}c_CaracterísticasDeObraoPieza">
 *             <length value="2"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "obrasarteantiguedades")
public class Obrasarteantiguedades {

    @XmlAttribute(name = "Version", required = true)
    protected String version;
    @XmlAttribute(name = "TipoBien", required = true)
    protected CTipoBien tipoBien;
    @XmlAttribute(name = "OtrosTipoBien")
    protected String otrosTipoBien;
    @XmlAttribute(name = "TituloAdquirido", required = true)
    protected CTituloadquirido tituloAdquirido;
    @XmlAttribute(name = "OtrosTituloAdquirido")
    protected String otrosTituloAdquirido;
    @XmlAttribute(name = "Subtotal")
    protected BigDecimal subtotal;
    @XmlAttribute(name = "IVA")
    protected BigDecimal iva;
    @XmlAttribute(name = "FechaAdquisicion", required = true)
    @XmlJavaTypeAdapter(DateAdapter.class)
    protected LocalDate fechaAdquisicion;
    @XmlAttribute(name = "Caracter\u00edsticasDeObraoPieza", required = true)
    protected CCaracterísticasDeObraoPieza característicasDeObraoPieza;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the tipoBien property.
     * 
     * @return
     *     possible object is
     *     {@link CTipoBien }
     *     
     */
    public CTipoBien getTipoBien() {
        return tipoBien;
    }

    /**
     * Sets the value of the tipoBien property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTipoBien }
     *     
     */
    public void setTipoBien(CTipoBien value) {
        this.tipoBien = value;
    }

    /**
     * Gets the value of the otrosTipoBien property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtrosTipoBien() {
        return otrosTipoBien;
    }

    /**
     * Sets the value of the otrosTipoBien property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtrosTipoBien(String value) {
        this.otrosTipoBien = value;
    }

    /**
     * Gets the value of the tituloAdquirido property.
     * 
     * @return
     *     possible object is
     *     {@link CTituloadquirido }
     *     
     */
    public CTituloadquirido getTituloAdquirido() {
        return tituloAdquirido;
    }

    /**
     * Sets the value of the tituloAdquirido property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTituloadquirido }
     *     
     */
    public void setTituloAdquirido(CTituloadquirido value) {
        this.tituloAdquirido = value;
    }

    /**
     * Gets the value of the otrosTituloAdquirido property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtrosTituloAdquirido() {
        return otrosTituloAdquirido;
    }

    /**
     * Sets the value of the otrosTituloAdquirido property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtrosTituloAdquirido(String value) {
        this.otrosTituloAdquirido = value;
    }

    /**
     * Gets the value of the subtotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSubtotal() {
        return subtotal;
    }

    /**
     * Sets the value of the subtotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSubtotal(BigDecimal value) {
        this.subtotal = value;
    }

    /**
     * Gets the value of the iva property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIVA() {
        return iva;
    }

    /**
     * Sets the value of the iva property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIVA(BigDecimal value) {
        this.iva = value;
    }

    /**
     * Gets the value of the fechaAdquisicion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public LocalDate getFechaAdquisicion() {
        return fechaAdquisicion;
    }

    /**
     * Sets the value of the fechaAdquisicion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaAdquisicion(LocalDate value) {
        this.fechaAdquisicion = value;
    }

    /**
     * Gets the value of the característicasDeObraoPieza property.
     * 
     * @return
     *     possible object is
     *     {@link CCaracterísticasDeObraoPieza }
     *     
     */
    public CCaracterísticasDeObraoPieza getCaracterísticasDeObraoPieza() {
        return característicasDeObraoPieza;
    }

    /**
     * Sets the value of the característicasDeObraoPieza property.
     * 
     * @param value
     *     allowed object is
     *     {@link CCaracterísticasDeObraoPieza }
     *     
     */
    public void setCaracterísticasDeObraoPieza(CCaracterísticasDeObraoPieza value) {
        this.característicasDeObraoPieza = value;
    }

}
