//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.ine11;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_Ambito.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="t_Ambito">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="Local"/>
 *     <enumeration value="Federal"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "t_Ambito")
@XmlEnum
public enum TAmbito {

    @XmlEnumValue("Local")
    LOCAL("Local"),
    @XmlEnumValue("Federal")
    FEDERAL("Federal");
    private final String value;

    TAmbito(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TAmbito fromValue(String v) {
        for (TAmbito c: TAmbito.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
