//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.ine11;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_ClaveEntidad.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="t_ClaveEntidad">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="AGU"/>
 *     <enumeration value="BCN"/>
 *     <enumeration value="BCS"/>
 *     <enumeration value="CAM"/>
 *     <enumeration value="CHP"/>
 *     <enumeration value="CHH"/>
 *     <enumeration value="COA"/>
 *     <enumeration value="COL"/>
 *     <enumeration value="CR1"/>
 *     <enumeration value="CR2"/>
 *     <enumeration value="CR3"/>
 *     <enumeration value="CR4"/>
 *     <enumeration value="CR5"/>
 *     <enumeration value="DIF"/>
 *     <enumeration value="DUR"/>
 *     <enumeration value="GUA"/>
 *     <enumeration value="GRO"/>
 *     <enumeration value="HID"/>
 *     <enumeration value="JAL"/>
 *     <enumeration value="MEX"/>
 *     <enumeration value="MIC"/>
 *     <enumeration value="MOR"/>
 *     <enumeration value="NAC"/>
 *     <enumeration value="NAY"/>
 *     <enumeration value="NLE"/>
 *     <enumeration value="OAX"/>
 *     <enumeration value="PUE"/>
 *     <enumeration value="QUE"/>
 *     <enumeration value="ROO"/>
 *     <enumeration value="SLP"/>
 *     <enumeration value="SIN"/>
 *     <enumeration value="SON"/>
 *     <enumeration value="TAB"/>
 *     <enumeration value="TAM"/>
 *     <enumeration value="TLA"/>
 *     <enumeration value="VER"/>
 *     <enumeration value="YUC"/>
 *     <enumeration value="ZAC"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "t_ClaveEntidad")
@XmlEnum
public enum TClaveEntidad {

    AGU("AGU"),
    BCN("BCN"),
    BCS("BCS"),
    CAM("CAM"),
    CHP("CHP"),
    CHH("CHH"),
    COA("COA"),
    COL("COL"),
    @XmlEnumValue("CR1")
    CR_1("CR1"),
    @XmlEnumValue("CR2")
    CR_2("CR2"),
    @XmlEnumValue("CR3")
    CR_3("CR3"),
    @XmlEnumValue("CR4")
    CR_4("CR4"),
    @XmlEnumValue("CR5")
    CR_5("CR5"),
    DIF("DIF"),
    DUR("DUR"),
    GUA("GUA"),
    GRO("GRO"),
    HID("HID"),
    JAL("JAL"),
    MEX("MEX"),
    MIC("MIC"),
    MOR("MOR"),
    NAC("NAC"),
    NAY("NAY"),
    NLE("NLE"),
    OAX("OAX"),
    PUE("PUE"),
    QUE("QUE"),
    ROO("ROO"),
    SLP("SLP"),
    SIN("SIN"),
    SON("SON"),
    TAB("TAB"),
    TAM("TAM"),
    TLA("TLA"),
    VER("VER"),
    YUC("YUC"),
    ZAC("ZAC");
    private final String value;

    TClaveEntidad(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TClaveEntidad fromValue(String v) {
        for (TClaveEntidad c: TClaveEntidad.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
