//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.ine11;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_TipoComite.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="t_TipoComite">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="Ejecutivo Nacional"/>
 *     <enumeration value="Ejecutivo Estatal"/>
 *     <enumeration value="Directivo Estatal"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "t_TipoComite")
@XmlEnum
public enum TTipoComite {

    @XmlEnumValue("Ejecutivo Nacional")
    EJECUTIVO_NACIONAL("Ejecutivo Nacional"),
    @XmlEnumValue("Ejecutivo Estatal")
    EJECUTIVO_ESTATAL("Ejecutivo Estatal"),
    @XmlEnumValue("Directivo Estatal")
    DIRECTIVO_ESTATAL("Directivo Estatal");
    private final String value;

    TTipoComite(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TTipoComite fromValue(String v) {
        for (TTipoComite c: TTipoComite.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
