//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.catalogos.Combustible;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_ClaveTipoCombustible.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="c_ClaveTipoCombustible">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <whiteSpace value="collapse"/>
 *     <enumeration value="1"/>
 *     <enumeration value="2"/>
 *     <enumeration value="3"/>
 *     <enumeration value="4"/>
 *     <enumeration value="5"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "c_ClaveTipoCombustible", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Combustible")
@XmlEnum
public enum CClaveTipoCombustible {


    /**
     * Gasolina menor a 92 octanos
     * 
     */
    @XmlEnumValue("1")
    VALUE_1("1"),

    /**
     * Gasolina mayor o igual a 92 octanos
     * 
     */
    @XmlEnumValue("2")
    VALUE_2("2"),

    /**
     * Diesel
     * 
     */
    @XmlEnumValue("3")
    VALUE_3("3"),

    /**
     * Diesel Marino
     * 
     */
    @XmlEnumValue("4")
    VALUE_4("4"),

    /**
     * Otros
     * 
     */
    @XmlEnumValue("5")
    VALUE_5("5");
    private final String value;

    CClaveTipoCombustible(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CClaveTipoCombustible fromValue(String v) {
        for (CClaveTipoCombustible c: CClaveTipoCombustible.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
