//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.certificadodestruccion10;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_TipoSerie.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="c_TipoSerie">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="SERIE A"/>
 *     <enumeration value="SERIE B"/>
 *     <enumeration value="SERIE C"/>
 *     <enumeration value="SERIE D"/>
 *     <enumeration value="SERIE E"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "c_TipoSerie")
@XmlEnum
public enum CTipoSerie {

    @XmlEnumValue("SERIE A")
    SERIE_A("SERIE A"),
    @XmlEnumValue("SERIE B")
    SERIE_B("SERIE B"),
    @XmlEnumValue("SERIE C")
    SERIE_C("SERIE C"),
    @XmlEnumValue("SERIE D")
    SERIE_D("SERIE D"),
    @XmlEnumValue("SERIE E")
    SERIE_E("SERIE E");
    private final String value;

    CTipoSerie(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CTipoSerie fromValue(String v) {
        for (CTipoSerie c: CTipoSerie.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
