//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.catalogos.hidrocarburos;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClavePedimento.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="ClavePedimento">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <whiteSpace value="collapse"/>
 *     <enumeration value="A1"/>
 *     <enumeration value="A3"/>
 *     <enumeration value="C1"/>
 *     <enumeration value="D1"/>
 *     <enumeration value="GC"/>
 *     <enumeration value="K1"/>
 *     <enumeration value="L1"/>
 *     <enumeration value="P1"/>
 *     <enumeration value="S2"/>
 *     <enumeration value="T1"/>
 *     <enumeration value="VF"/>
 *     <enumeration value="VU"/>
 *     <enumeration value="V1"/>
 *     <enumeration value="V2"/>
 *     <enumeration value="V5"/>
 *     <enumeration value="V6"/>
 *     <enumeration value="V7"/>
 *     <enumeration value="V9"/>
 *     <enumeration value="VD"/>
 *     <enumeration value="AD"/>
 *     <enumeration value="AJ"/>
 *     <enumeration value="BA"/>
 *     <enumeration value="BB"/>
 *     <enumeration value="BC"/>
 *     <enumeration value="BD"/>
 *     <enumeration value="BE"/>
 *     <enumeration value="BF"/>
 *     <enumeration value="BH"/>
 *     <enumeration value="BI"/>
 *     <enumeration value="BM"/>
 *     <enumeration value="BO"/>
 *     <enumeration value="BP"/>
 *     <enumeration value="BR"/>
 *     <enumeration value="H1"/>
 *     <enumeration value="H8"/>
 *     <enumeration value="I1"/>
 *     <enumeration value="F4"/>
 *     <enumeration value="F5"/>
 *     <enumeration value="IN"/>
 *     <enumeration value="AF"/>
 *     <enumeration value="RT"/>
 *     <enumeration value="A4"/>
 *     <enumeration value="E1"/>
 *     <enumeration value="E2"/>
 *     <enumeration value="G1"/>
 *     <enumeration value="C3"/>
 *     <enumeration value="K2"/>
 *     <enumeration value="A5"/>
 *     <enumeration value="E3"/>
 *     <enumeration value="E4"/>
 *     <enumeration value="G2"/>
 *     <enumeration value="K3"/>
 *     <enumeration value="F2"/>
 *     <enumeration value="F3"/>
 *     <enumeration value="V3"/>
 *     <enumeration value="V4"/>
 *     <enumeration value="F8"/>
 *     <enumeration value="F9"/>
 *     <enumeration value="G6"/>
 *     <enumeration value="G7"/>
 *     <enumeration value="V8"/>
 *     <enumeration value="M1"/>
 *     <enumeration value="M2"/>
 *     <enumeration value="J3"/>
 *     <enumeration value="G8"/>
 *     <enumeration value="M3"/>
 *     <enumeration value="M4"/>
 *     <enumeration value="M5"/>
 *     <enumeration value="J4"/>
 *     <enumeration value="T3"/>
 *     <enumeration value="T6"/>
 *     <enumeration value="T7"/>
 *     <enumeration value="T9"/>
 *     <enumeration value="R1"/>
 *     <enumeration value="CT"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "ClavePedimento", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/hidrocarburos")
@XmlEnum
public enum ClavePedimento {

    @XmlEnumValue("A1")
    A_1("A1"),
    @XmlEnumValue("A3")
    A_3("A3"),
    @XmlEnumValue("C1")
    C_1("C1"),
    @XmlEnumValue("D1")
    D_1("D1"),
    GC("GC"),
    @XmlEnumValue("K1")
    K_1("K1"),
    @XmlEnumValue("L1")
    L_1("L1"),
    @XmlEnumValue("P1")
    P_1("P1"),
    @XmlEnumValue("S2")
    S_2("S2"),
    @XmlEnumValue("T1")
    T_1("T1"),
    VF("VF"),
    VU("VU"),
    @XmlEnumValue("V1")
    V_1("V1"),
    @XmlEnumValue("V2")
    V_2("V2"),
    @XmlEnumValue("V5")
    V_5("V5"),
    @XmlEnumValue("V6")
    V_6("V6"),
    @XmlEnumValue("V7")
    V_7("V7"),
    @XmlEnumValue("V9")
    V_9("V9"),
    VD("VD"),
    AD("AD"),
    AJ("AJ"),
    BA("BA"),
    BB("BB"),
    BC("BC"),
    BD("BD"),
    BE("BE"),
    BF("BF"),
    BH("BH"),
    BI("BI"),
    BM("BM"),
    BO("BO"),
    BP("BP"),
    BR("BR"),
    @XmlEnumValue("H1")
    H_1("H1"),
    @XmlEnumValue("H8")
    H_8("H8"),
    @XmlEnumValue("I1")
    I_1("I1"),
    @XmlEnumValue("F4")
    F_4("F4"),
    @XmlEnumValue("F5")
    F_5("F5"),
    IN("IN"),
    AF("AF"),
    RT("RT"),
    @XmlEnumValue("A4")
    A_4("A4"),
    @XmlEnumValue("E1")
    E_1("E1"),
    @XmlEnumValue("E2")
    E_2("E2"),
    @XmlEnumValue("G1")
    G_1("G1"),
    @XmlEnumValue("C3")
    C_3("C3"),
    @XmlEnumValue("K2")
    K_2("K2"),
    @XmlEnumValue("A5")
    A_5("A5"),
    @XmlEnumValue("E3")
    E_3("E3"),
    @XmlEnumValue("E4")
    E_4("E4"),
    @XmlEnumValue("G2")
    G_2("G2"),
    @XmlEnumValue("K3")
    K_3("K3"),
    @XmlEnumValue("F2")
    F_2("F2"),
    @XmlEnumValue("F3")
    F_3("F3"),
    @XmlEnumValue("V3")
    V_3("V3"),
    @XmlEnumValue("V4")
    V_4("V4"),
    @XmlEnumValue("F8")
    F_8("F8"),
    @XmlEnumValue("F9")
    F_9("F9"),
    @XmlEnumValue("G6")
    G_6("G6"),
    @XmlEnumValue("G7")
    G_7("G7"),
    @XmlEnumValue("V8")
    V_8("V8"),
    @XmlEnumValue("M1")
    M_1("M1"),
    @XmlEnumValue("M2")
    M_2("M2"),
    @XmlEnumValue("J3")
    J_3("J3"),
    @XmlEnumValue("G8")
    G_8("G8"),
    @XmlEnumValue("M3")
    M_3("M3"),
    @XmlEnumValue("M4")
    M_4("M4"),
    @XmlEnumValue("M5")
    M_5("M5"),
    @XmlEnumValue("J4")
    J_4("J4"),
    @XmlEnumValue("T3")
    T_3("T3"),
    @XmlEnumValue("T6")
    T_6("T6"),
    @XmlEnumValue("T7")
    T_7("T7"),
    @XmlEnumValue("T9")
    T_9("T9"),
    @XmlEnumValue("R1")
    R_1("R1"),
    CT("CT");
    private final String value;

    ClavePedimento(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ClavePedimento fromValue(String v) {
        for (ClavePedimento c: ClavePedimento.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
