//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.catalogos.hidrocarburos;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClavePagoPedimento.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="ClavePagoPedimento">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <whiteSpace value="collapse"/>
 *     <enumeration value="00"/>
 *     <enumeration value="02"/>
 *     <enumeration value="04"/>
 *     <enumeration value="05"/>
 *     <enumeration value="06"/>
 *     <enumeration value="07"/>
 *     <enumeration value="08"/>
 *     <enumeration value="09"/>
 *     <enumeration value="10"/>
 *     <enumeration value="11"/>
 *     <enumeration value="12"/>
 *     <enumeration value="13"/>
 *     <enumeration value="14"/>
 *     <enumeration value="15"/>
 *     <enumeration value="16"/>
 *     <enumeration value="18"/>
 *     <enumeration value="19"/>
 *     <enumeration value="20"/>
 *     <enumeration value="21"/>
 *     <enumeration value="22"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "ClavePagoPedimento", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/hidrocarburos")
@XmlEnum
public enum ClavePagoPedimento {

    @XmlEnumValue("00")
    VALUE_1("00"),
    @XmlEnumValue("02")
    VALUE_2("02"),
    @XmlEnumValue("04")
    VALUE_3("04"),
    @XmlEnumValue("05")
    VALUE_4("05"),
    @XmlEnumValue("06")
    VALUE_5("06"),
    @XmlEnumValue("07")
    VALUE_6("07"),
    @XmlEnumValue("08")
    VALUE_7("08"),
    @XmlEnumValue("09")
    VALUE_8("09"),
    @XmlEnumValue("10")
    VALUE_9("10"),
    @XmlEnumValue("11")
    VALUE_10("11"),
    @XmlEnumValue("12")
    VALUE_11("12"),
    @XmlEnumValue("13")
    VALUE_12("13"),
    @XmlEnumValue("14")
    VALUE_13("14"),
    @XmlEnumValue("15")
    VALUE_14("15"),
    @XmlEnumValue("16")
    VALUE_15("16"),
    @XmlEnumValue("18")
    VALUE_16("18"),
    @XmlEnumValue("19")
    VALUE_17("19"),
    @XmlEnumValue("20")
    VALUE_18("20"),
    @XmlEnumValue("21")
    VALUE_19("21"),
    @XmlEnumValue("22")
    VALUE_20("22");
    private final String value;

    ClavePagoPedimento(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ClavePagoPedimento fromValue(String v) {
        for (ClavePagoPedimento c: ClavePagoPedimento.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
