//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.catalogos.hidrocarburos;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SubActividad.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="SubActividad">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <whiteSpace value="collapse"/>
 *     <enumeration value="001"/>
 *     <enumeration value="002"/>
 *     <enumeration value="003"/>
 *     <enumeration value="004"/>
 *     <enumeration value="005"/>
 *     <enumeration value="006"/>
 *     <enumeration value="007"/>
 *     <enumeration value="008"/>
 *     <enumeration value="009"/>
 *     <enumeration value="010"/>
 *     <enumeration value="011"/>
 *     <enumeration value="012"/>
 *     <enumeration value="013"/>
 *     <enumeration value="014"/>
 *     <enumeration value="015"/>
 *     <enumeration value="016"/>
 *     <enumeration value="017"/>
 *     <enumeration value="018"/>
 *     <enumeration value="019"/>
 *     <enumeration value="020"/>
 *     <enumeration value="021"/>
 *     <enumeration value="022"/>
 *     <enumeration value="023"/>
 *     <enumeration value="024"/>
 *     <enumeration value="025"/>
 *     <enumeration value="026"/>
 *     <enumeration value="027"/>
 *     <enumeration value="028"/>
 *     <enumeration value="029"/>
 *     <enumeration value="030"/>
 *     <enumeration value="031"/>
 *     <enumeration value="032"/>
 *     <enumeration value="033"/>
 *     <enumeration value="034"/>
 *     <enumeration value="035"/>
 *     <enumeration value="036"/>
 *     <enumeration value="037"/>
 *     <enumeration value="038"/>
 *     <enumeration value="039"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "SubActividad", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/hidrocarburos")
@XmlEnum
public enum SubActividad {

    @XmlEnumValue("001")
    VALUE_1("001"),
    @XmlEnumValue("002")
    VALUE_2("002"),
    @XmlEnumValue("003")
    VALUE_3("003"),
    @XmlEnumValue("004")
    VALUE_4("004"),
    @XmlEnumValue("005")
    VALUE_5("005"),
    @XmlEnumValue("006")
    VALUE_6("006"),
    @XmlEnumValue("007")
    VALUE_7("007"),
    @XmlEnumValue("008")
    VALUE_8("008"),
    @XmlEnumValue("009")
    VALUE_9("009"),
    @XmlEnumValue("010")
    VALUE_10("010"),
    @XmlEnumValue("011")
    VALUE_11("011"),
    @XmlEnumValue("012")
    VALUE_12("012"),
    @XmlEnumValue("013")
    VALUE_13("013"),
    @XmlEnumValue("014")
    VALUE_14("014"),
    @XmlEnumValue("015")
    VALUE_15("015"),
    @XmlEnumValue("016")
    VALUE_16("016"),
    @XmlEnumValue("017")
    VALUE_17("017"),
    @XmlEnumValue("018")
    VALUE_18("018"),
    @XmlEnumValue("019")
    VALUE_19("019"),
    @XmlEnumValue("020")
    VALUE_20("020"),
    @XmlEnumValue("021")
    VALUE_21("021"),
    @XmlEnumValue("022")
    VALUE_22("022"),
    @XmlEnumValue("023")
    VALUE_23("023"),
    @XmlEnumValue("024")
    VALUE_24("024"),
    @XmlEnumValue("025")
    VALUE_25("025"),
    @XmlEnumValue("026")
    VALUE_26("026"),
    @XmlEnumValue("027")
    VALUE_27("027"),
    @XmlEnumValue("028")
    VALUE_28("028"),
    @XmlEnumValue("029")
    VALUE_29("029"),
    @XmlEnumValue("030")
    VALUE_30("030"),
    @XmlEnumValue("031")
    VALUE_31("031"),
    @XmlEnumValue("032")
    VALUE_32("032"),
    @XmlEnumValue("033")
    VALUE_33("033"),
    @XmlEnumValue("034")
    VALUE_34("034"),
    @XmlEnumValue("035")
    VALUE_35("035"),
    @XmlEnumValue("036")
    VALUE_36("036"),
    @XmlEnumValue("037")
    VALUE_37("037"),
    @XmlEnumValue("038")
    VALUE_38("038"),
    @XmlEnumValue("039")
    VALUE_39("039");
    private final String value;

    SubActividad(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SubActividad fromValue(String v) {
        for (SubActividad c: SubActividad.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
