//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.catalogos.hidrocarburos;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Tareas.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="Tareas">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <whiteSpace value="collapse"/>
 *     <enumeration value="0001"/>
 *     <enumeration value="0002"/>
 *     <enumeration value="0003"/>
 *     <enumeration value="0004"/>
 *     <enumeration value="0005"/>
 *     <enumeration value="0006"/>
 *     <enumeration value="0007"/>
 *     <enumeration value="0008"/>
 *     <enumeration value="0009"/>
 *     <enumeration value="0010"/>
 *     <enumeration value="0011"/>
 *     <enumeration value="0012"/>
 *     <enumeration value="0013"/>
 *     <enumeration value="0014"/>
 *     <enumeration value="0015"/>
 *     <enumeration value="0016"/>
 *     <enumeration value="0017"/>
 *     <enumeration value="0018"/>
 *     <enumeration value="0019"/>
 *     <enumeration value="0020"/>
 *     <enumeration value="0021"/>
 *     <enumeration value="0022"/>
 *     <enumeration value="0023"/>
 *     <enumeration value="0024"/>
 *     <enumeration value="0025"/>
 *     <enumeration value="0026"/>
 *     <enumeration value="0027"/>
 *     <enumeration value="0028"/>
 *     <enumeration value="0029"/>
 *     <enumeration value="0030"/>
 *     <enumeration value="0031"/>
 *     <enumeration value="0032"/>
 *     <enumeration value="0033"/>
 *     <enumeration value="0034"/>
 *     <enumeration value="0035"/>
 *     <enumeration value="0036"/>
 *     <enumeration value="0037"/>
 *     <enumeration value="0038"/>
 *     <enumeration value="0039"/>
 *     <enumeration value="0040"/>
 *     <enumeration value="0041"/>
 *     <enumeration value="0042"/>
 *     <enumeration value="0043"/>
 *     <enumeration value="0044"/>
 *     <enumeration value="0045"/>
 *     <enumeration value="0046"/>
 *     <enumeration value="0047"/>
 *     <enumeration value="0048"/>
 *     <enumeration value="0049"/>
 *     <enumeration value="0050"/>
 *     <enumeration value="0051"/>
 *     <enumeration value="0052"/>
 *     <enumeration value="0053"/>
 *     <enumeration value="0054"/>
 *     <enumeration value="0055"/>
 *     <enumeration value="0056"/>
 *     <enumeration value="0057"/>
 *     <enumeration value="0058"/>
 *     <enumeration value="0059"/>
 *     <enumeration value="0060"/>
 *     <enumeration value="0061"/>
 *     <enumeration value="0062"/>
 *     <enumeration value="0063"/>
 *     <enumeration value="0064"/>
 *     <enumeration value="0065"/>
 *     <enumeration value="0066"/>
 *     <enumeration value="0067"/>
 *     <enumeration value="0068"/>
 *     <enumeration value="0069"/>
 *     <enumeration value="0070"/>
 *     <enumeration value="0071"/>
 *     <enumeration value="0072"/>
 *     <enumeration value="0073"/>
 *     <enumeration value="0074"/>
 *     <enumeration value="0075"/>
 *     <enumeration value="0076"/>
 *     <enumeration value="0077"/>
 *     <enumeration value="0078"/>
 *     <enumeration value="0079"/>
 *     <enumeration value="0080"/>
 *     <enumeration value="0081"/>
 *     <enumeration value="0082"/>
 *     <enumeration value="0083"/>
 *     <enumeration value="0084"/>
 *     <enumeration value="0085"/>
 *     <enumeration value="0086"/>
 *     <enumeration value="0087"/>
 *     <enumeration value="0088"/>
 *     <enumeration value="0089"/>
 *     <enumeration value="0090"/>
 *     <enumeration value="0091"/>
 *     <enumeration value="0092"/>
 *     <enumeration value="0093"/>
 *     <enumeration value="0094"/>
 *     <enumeration value="0095"/>
 *     <enumeration value="0096"/>
 *     <enumeration value="0097"/>
 *     <enumeration value="0098"/>
 *     <enumeration value="0099"/>
 *     <enumeration value="0100"/>
 *     <enumeration value="0101"/>
 *     <enumeration value="0102"/>
 *     <enumeration value="0103"/>
 *     <enumeration value="0104"/>
 *     <enumeration value="0105"/>
 *     <enumeration value="0106"/>
 *     <enumeration value="0107"/>
 *     <enumeration value="0108"/>
 *     <enumeration value="0109"/>
 *     <enumeration value="0110"/>
 *     <enumeration value="0111"/>
 *     <enumeration value="0112"/>
 *     <enumeration value="0113"/>
 *     <enumeration value="0114"/>
 *     <enumeration value="0115"/>
 *     <enumeration value="0116"/>
 *     <enumeration value="0117"/>
 *     <enumeration value="0118"/>
 *     <enumeration value="0119"/>
 *     <enumeration value="0120"/>
 *     <enumeration value="0121"/>
 *     <enumeration value="0122"/>
 *     <enumeration value="0123"/>
 *     <enumeration value="0124"/>
 *     <enumeration value="0125"/>
 *     <enumeration value="0126"/>
 *     <enumeration value="0127"/>
 *     <enumeration value="0128"/>
 *     <enumeration value="0129"/>
 *     <enumeration value="0130"/>
 *     <enumeration value="0131"/>
 *     <enumeration value="0132"/>
 *     <enumeration value="0133"/>
 *     <enumeration value="0134"/>
 *     <enumeration value="0135"/>
 *     <enumeration value="0136"/>
 *     <enumeration value="0137"/>
 *     <enumeration value="0138"/>
 *     <enumeration value="0139"/>
 *     <enumeration value="0140"/>
 *     <enumeration value="0141"/>
 *     <enumeration value="0142"/>
 *     <enumeration value="0143"/>
 *     <enumeration value="0144"/>
 *     <enumeration value="0145"/>
 *     <enumeration value="0146"/>
 *     <enumeration value="0147"/>
 *     <enumeration value="0148"/>
 *     <enumeration value="0149"/>
 *     <enumeration value="0150"/>
 *     <enumeration value="0151"/>
 *     <enumeration value="0152"/>
 *     <enumeration value="0153"/>
 *     <enumeration value="0154"/>
 *     <enumeration value="0155"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "Tareas", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/hidrocarburos")
@XmlEnum
public enum Tareas {

    @XmlEnumValue("0001")
    VALUE_1("0001"),
    @XmlEnumValue("0002")
    VALUE_2("0002"),
    @XmlEnumValue("0003")
    VALUE_3("0003"),
    @XmlEnumValue("0004")
    VALUE_4("0004"),
    @XmlEnumValue("0005")
    VALUE_5("0005"),
    @XmlEnumValue("0006")
    VALUE_6("0006"),
    @XmlEnumValue("0007")
    VALUE_7("0007"),
    @XmlEnumValue("0008")
    VALUE_8("0008"),
    @XmlEnumValue("0009")
    VALUE_9("0009"),
    @XmlEnumValue("0010")
    VALUE_10("0010"),
    @XmlEnumValue("0011")
    VALUE_11("0011"),
    @XmlEnumValue("0012")
    VALUE_12("0012"),
    @XmlEnumValue("0013")
    VALUE_13("0013"),
    @XmlEnumValue("0014")
    VALUE_14("0014"),
    @XmlEnumValue("0015")
    VALUE_15("0015"),
    @XmlEnumValue("0016")
    VALUE_16("0016"),
    @XmlEnumValue("0017")
    VALUE_17("0017"),
    @XmlEnumValue("0018")
    VALUE_18("0018"),
    @XmlEnumValue("0019")
    VALUE_19("0019"),
    @XmlEnumValue("0020")
    VALUE_20("0020"),
    @XmlEnumValue("0021")
    VALUE_21("0021"),
    @XmlEnumValue("0022")
    VALUE_22("0022"),
    @XmlEnumValue("0023")
    VALUE_23("0023"),
    @XmlEnumValue("0024")
    VALUE_24("0024"),
    @XmlEnumValue("0025")
    VALUE_25("0025"),
    @XmlEnumValue("0026")
    VALUE_26("0026"),
    @XmlEnumValue("0027")
    VALUE_27("0027"),
    @XmlEnumValue("0028")
    VALUE_28("0028"),
    @XmlEnumValue("0029")
    VALUE_29("0029"),
    @XmlEnumValue("0030")
    VALUE_30("0030"),
    @XmlEnumValue("0031")
    VALUE_31("0031"),
    @XmlEnumValue("0032")
    VALUE_32("0032"),
    @XmlEnumValue("0033")
    VALUE_33("0033"),
    @XmlEnumValue("0034")
    VALUE_34("0034"),
    @XmlEnumValue("0035")
    VALUE_35("0035"),
    @XmlEnumValue("0036")
    VALUE_36("0036"),
    @XmlEnumValue("0037")
    VALUE_37("0037"),
    @XmlEnumValue("0038")
    VALUE_38("0038"),
    @XmlEnumValue("0039")
    VALUE_39("0039"),
    @XmlEnumValue("0040")
    VALUE_40("0040"),
    @XmlEnumValue("0041")
    VALUE_41("0041"),
    @XmlEnumValue("0042")
    VALUE_42("0042"),
    @XmlEnumValue("0043")
    VALUE_43("0043"),
    @XmlEnumValue("0044")
    VALUE_44("0044"),
    @XmlEnumValue("0045")
    VALUE_45("0045"),
    @XmlEnumValue("0046")
    VALUE_46("0046"),
    @XmlEnumValue("0047")
    VALUE_47("0047"),
    @XmlEnumValue("0048")
    VALUE_48("0048"),
    @XmlEnumValue("0049")
    VALUE_49("0049"),
    @XmlEnumValue("0050")
    VALUE_50("0050"),
    @XmlEnumValue("0051")
    VALUE_51("0051"),
    @XmlEnumValue("0052")
    VALUE_52("0052"),
    @XmlEnumValue("0053")
    VALUE_53("0053"),
    @XmlEnumValue("0054")
    VALUE_54("0054"),
    @XmlEnumValue("0055")
    VALUE_55("0055"),
    @XmlEnumValue("0056")
    VALUE_56("0056"),
    @XmlEnumValue("0057")
    VALUE_57("0057"),
    @XmlEnumValue("0058")
    VALUE_58("0058"),
    @XmlEnumValue("0059")
    VALUE_59("0059"),
    @XmlEnumValue("0060")
    VALUE_60("0060"),
    @XmlEnumValue("0061")
    VALUE_61("0061"),
    @XmlEnumValue("0062")
    VALUE_62("0062"),
    @XmlEnumValue("0063")
    VALUE_63("0063"),
    @XmlEnumValue("0064")
    VALUE_64("0064"),
    @XmlEnumValue("0065")
    VALUE_65("0065"),
    @XmlEnumValue("0066")
    VALUE_66("0066"),
    @XmlEnumValue("0067")
    VALUE_67("0067"),
    @XmlEnumValue("0068")
    VALUE_68("0068"),
    @XmlEnumValue("0069")
    VALUE_69("0069"),
    @XmlEnumValue("0070")
    VALUE_70("0070"),
    @XmlEnumValue("0071")
    VALUE_71("0071"),
    @XmlEnumValue("0072")
    VALUE_72("0072"),
    @XmlEnumValue("0073")
    VALUE_73("0073"),
    @XmlEnumValue("0074")
    VALUE_74("0074"),
    @XmlEnumValue("0075")
    VALUE_75("0075"),
    @XmlEnumValue("0076")
    VALUE_76("0076"),
    @XmlEnumValue("0077")
    VALUE_77("0077"),
    @XmlEnumValue("0078")
    VALUE_78("0078"),
    @XmlEnumValue("0079")
    VALUE_79("0079"),
    @XmlEnumValue("0080")
    VALUE_80("0080"),
    @XmlEnumValue("0081")
    VALUE_81("0081"),
    @XmlEnumValue("0082")
    VALUE_82("0082"),
    @XmlEnumValue("0083")
    VALUE_83("0083"),
    @XmlEnumValue("0084")
    VALUE_84("0084"),
    @XmlEnumValue("0085")
    VALUE_85("0085"),
    @XmlEnumValue("0086")
    VALUE_86("0086"),
    @XmlEnumValue("0087")
    VALUE_87("0087"),
    @XmlEnumValue("0088")
    VALUE_88("0088"),
    @XmlEnumValue("0089")
    VALUE_89("0089"),
    @XmlEnumValue("0090")
    VALUE_90("0090"),
    @XmlEnumValue("0091")
    VALUE_91("0091"),
    @XmlEnumValue("0092")
    VALUE_92("0092"),
    @XmlEnumValue("0093")
    VALUE_93("0093"),
    @XmlEnumValue("0094")
    VALUE_94("0094"),
    @XmlEnumValue("0095")
    VALUE_95("0095"),
    @XmlEnumValue("0096")
    VALUE_96("0096"),
    @XmlEnumValue("0097")
    VALUE_97("0097"),
    @XmlEnumValue("0098")
    VALUE_98("0098"),
    @XmlEnumValue("0099")
    VALUE_99("0099"),
    @XmlEnumValue("0100")
    VALUE_100("0100"),
    @XmlEnumValue("0101")
    VALUE_101("0101"),
    @XmlEnumValue("0102")
    VALUE_102("0102"),
    @XmlEnumValue("0103")
    VALUE_103("0103"),
    @XmlEnumValue("0104")
    VALUE_104("0104"),
    @XmlEnumValue("0105")
    VALUE_105("0105"),
    @XmlEnumValue("0106")
    VALUE_106("0106"),
    @XmlEnumValue("0107")
    VALUE_107("0107"),
    @XmlEnumValue("0108")
    VALUE_108("0108"),
    @XmlEnumValue("0109")
    VALUE_109("0109"),
    @XmlEnumValue("0110")
    VALUE_110("0110"),
    @XmlEnumValue("0111")
    VALUE_111("0111"),
    @XmlEnumValue("0112")
    VALUE_112("0112"),
    @XmlEnumValue("0113")
    VALUE_113("0113"),
    @XmlEnumValue("0114")
    VALUE_114("0114"),
    @XmlEnumValue("0115")
    VALUE_115("0115"),
    @XmlEnumValue("0116")
    VALUE_116("0116"),
    @XmlEnumValue("0117")
    VALUE_117("0117"),
    @XmlEnumValue("0118")
    VALUE_118("0118"),
    @XmlEnumValue("0119")
    VALUE_119("0119"),
    @XmlEnumValue("0120")
    VALUE_120("0120"),
    @XmlEnumValue("0121")
    VALUE_121("0121"),
    @XmlEnumValue("0122")
    VALUE_122("0122"),
    @XmlEnumValue("0123")
    VALUE_123("0123"),
    @XmlEnumValue("0124")
    VALUE_124("0124"),
    @XmlEnumValue("0125")
    VALUE_125("0125"),
    @XmlEnumValue("0126")
    VALUE_126("0126"),
    @XmlEnumValue("0127")
    VALUE_127("0127"),
    @XmlEnumValue("0128")
    VALUE_128("0128"),
    @XmlEnumValue("0129")
    VALUE_129("0129"),
    @XmlEnumValue("0130")
    VALUE_130("0130"),
    @XmlEnumValue("0131")
    VALUE_131("0131"),
    @XmlEnumValue("0132")
    VALUE_132("0132"),
    @XmlEnumValue("0133")
    VALUE_133("0133"),
    @XmlEnumValue("0134")
    VALUE_134("0134"),
    @XmlEnumValue("0135")
    VALUE_135("0135"),
    @XmlEnumValue("0136")
    VALUE_136("0136"),
    @XmlEnumValue("0137")
    VALUE_137("0137"),
    @XmlEnumValue("0138")
    VALUE_138("0138"),
    @XmlEnumValue("0139")
    VALUE_139("0139"),
    @XmlEnumValue("0140")
    VALUE_140("0140"),
    @XmlEnumValue("0141")
    VALUE_141("0141"),
    @XmlEnumValue("0142")
    VALUE_142("0142"),
    @XmlEnumValue("0143")
    VALUE_143("0143"),
    @XmlEnumValue("0144")
    VALUE_144("0144"),
    @XmlEnumValue("0145")
    VALUE_145("0145"),
    @XmlEnumValue("0146")
    VALUE_146("0146"),
    @XmlEnumValue("0147")
    VALUE_147("0147"),
    @XmlEnumValue("0148")
    VALUE_148("0148"),
    @XmlEnumValue("0149")
    VALUE_149("0149"),
    @XmlEnumValue("0150")
    VALUE_150("0150"),
    @XmlEnumValue("0151")
    VALUE_151("0151"),
    @XmlEnumValue("0152")
    VALUE_152("0152"),
    @XmlEnumValue("0153")
    VALUE_153("0153"),
    @XmlEnumValue("0154")
    VALUE_154("0154"),
    @XmlEnumValue("0155")
    VALUE_155("0155");
    private final String value;

    Tareas(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Tareas fromValue(String v) {
        for (Tareas c: Tareas.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
