//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.ine10;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_ClaveEntidad.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="t_ClaveEntidad">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="AGU"/>
 *     <enumeration value="BCN"/>
 *     <enumeration value="BCS"/>
 *     <enumeration value="CAM"/>
 *     <enumeration value="CHP"/>
 *     <enumeration value="CHH"/>
 *     <enumeration value="COA"/>
 *     <enumeration value="COL"/>
 *     <enumeration value="DIF"/>
 *     <enumeration value="DUR"/>
 *     <enumeration value="GUA"/>
 *     <enumeration value="GRO"/>
 *     <enumeration value="HID"/>
 *     <enumeration value="JAL"/>
 *     <enumeration value="MEX"/>
 *     <enumeration value="MIC"/>
 *     <enumeration value="MOR"/>
 *     <enumeration value="NAY"/>
 *     <enumeration value="NLE"/>
 *     <enumeration value="OAX"/>
 *     <enumeration value="PUE"/>
 *     <enumeration value="QTO"/>
 *     <enumeration value="ROO"/>
 *     <enumeration value="SLP"/>
 *     <enumeration value="SIN"/>
 *     <enumeration value="SON"/>
 *     <enumeration value="TAB"/>
 *     <enumeration value="TAM"/>
 *     <enumeration value="TLA"/>
 *     <enumeration value="VER"/>
 *     <enumeration value="YUC"/>
 *     <enumeration value="ZAC"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "t_ClaveEntidad")
@XmlEnum
public enum TClaveEntidad {

    AGU,
    BCN,
    BCS,
    CAM,
    CHP,
    CHH,
    COA,
    COL,
    DIF,
    DUR,
    GUA,
    GRO,
    HID,
    JAL,
    MEX,
    MIC,
    MOR,
    NAY,
    NLE,
    OAX,
    PUE,
    QTO,
    ROO,
    SLP,
    SIN,
    SON,
    TAB,
    TAM,
    TLA,
    VER,
    YUC,
    ZAC;

    public String value() {
        return name();
    }

    public static TClaveEntidad fromValue(String v) {
        return valueOf(v);
    }

}
