//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.ine10;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_TipoProc.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="t_TipoProc">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="Ordinario"/>
 *     <enumeration value="Precampaña"/>
 *     <enumeration value="Campaña"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "t_TipoProc")
@XmlEnum
public enum TTipoProc {

    @XmlEnumValue("Ordinario")
    ORDINARIO("Ordinario"),
    @XmlEnumValue("Precampa\u00f1a")
    PRECAMPAÑA("Precampa\u00f1a"),
    @XmlEnumValue("Campa\u00f1a")
    CAMPAÑA("Campa\u00f1a");
    private final String value;

    TTipoProc(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TTipoProc fromValue(String v) {
        for (TTipoProc c: TTipoProc.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
