//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package mx.grupocorasa.sat.common.consumodecombustibles10;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.grupocorasa.sat.common.consumodecombustibles10 package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.grupocorasa.sat.common.consumodecombustibles10
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConsumoDeCombustibles }
     * 
     * @return
     *     the new instance of {@link ConsumoDeCombustibles }
     */
    public ConsumoDeCombustibles createConsumoDeCombustibles() {
        return new ConsumoDeCombustibles();
    }

    /**
     * Create an instance of {@link ConsumoDeCombustibles.Conceptos }
     * 
     * @return
     *     the new instance of {@link ConsumoDeCombustibles.Conceptos }
     */
    public ConsumoDeCombustibles.Conceptos createConsumoDeCombustiblesConceptos() {
        return new ConsumoDeCombustibles.Conceptos();
    }

    /**
     * Create an instance of {@link ConsumoDeCombustibles.Conceptos.ConceptoConsumoDeCombustibles }
     * 
     * @return
     *     the new instance of {@link ConsumoDeCombustibles.Conceptos.ConceptoConsumoDeCombustibles }
     */
    public ConsumoDeCombustibles.Conceptos.ConceptoConsumoDeCombustibles createConsumoDeCombustiblesConceptosConceptoConsumoDeCombustibles() {
        return new ConsumoDeCombustibles.Conceptos.ConceptoConsumoDeCombustibles();
    }

    /**
     * Create an instance of {@link ConsumoDeCombustibles.Conceptos.ConceptoConsumoDeCombustibles.Determinados }
     * 
     * @return
     *     the new instance of {@link ConsumoDeCombustibles.Conceptos.ConceptoConsumoDeCombustibles.Determinados }
     */
    public ConsumoDeCombustibles.Conceptos.ConceptoConsumoDeCombustibles.Determinados createConsumoDeCombustiblesConceptosConceptoConsumoDeCombustiblesDeterminados() {
        return new ConsumoDeCombustibles.Conceptos.ConceptoConsumoDeCombustibles.Determinados();
    }

    /**
     * Create an instance of {@link ConsumoDeCombustibles.Conceptos.ConceptoConsumoDeCombustibles.Determinados.Determinado }
     * 
     * @return
     *     the new instance of {@link ConsumoDeCombustibles.Conceptos.ConceptoConsumoDeCombustibles.Determinados.Determinado }
     */
    public ConsumoDeCombustibles.Conceptos.ConceptoConsumoDeCombustibles.Determinados.Determinado createConsumoDeCombustiblesConceptosConceptoConsumoDeCombustiblesDeterminadosDeterminado() {
        return new ConsumoDeCombustibles.Conceptos.ConceptoConsumoDeCombustibles.Determinados.Determinado();
    }

}
